### ISSUE TITLE
Longest Increasing Subsequence

### ISSUE THREAD

**Issue by Ankitha2130** [AlgoGenesis/C#100]
Given an array of  integers, find the Length of the Longest Strictly Increasing Subsequence.
A sequence of numbers is called "strictly increasing" when each term in the sequence is smaller than the term that comes after it by deleting some or no elements of array.

I will work on providing both brute force approach that takes O(n^2) time and as well as optimized approach that takes O(n*log n) time.

Please assign this issue to me under hacktoberfest, hacktoberfest-accepted, gssoc-ext, and the level labels.

**Comment by kashishchadha** [comment]
Given an array of integers, find the Length of the Longest Strictly Increasing Subsequence.
The optimized approach uses binary search along with a helper array to store potential subsequences. This method is based on the concept of maintaining the smallest possible last element for increasing subsequences of different lengths.
Please assign this issue to me ....
