### ISSUE TITLE
[NEW ALGORITHM] Manacher's Algorithm (Longest Palindromic Substring Algorithm)

### ISSUE THREAD

**Issue by HimanshuM685** [AlgoGenesis/C#1001]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Manacher's Algorithm (Longest Palindromic Substring Algorithm)``  

### About:  
Manacher's Algorithm finds the longest palindromic substring in linear time by transforming the string to handle both even and odd-length palindromes uniformly.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by HimanshuM685** [comment]
@pankaj-bind

**Comment by pankaj-bind** [comment]
@HimanshuM685 assigned
