### ISSUE TITLE
[NEW ALGORITHM] Treaps Algorithm (Binary Search tree algo)

### ISSUE THREAD

**Issue by undertakerme** [AlgoGenesis/C#1006]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
Treaps Algorithm (Binary Search tree algo)
### About:  
Propose a new algorithm to be added to the repository
Use Case: Randomized binary search trees.
Description: A combination of a binary search tree and a heap, treaps maintain a randomized structure that guarantees expected logarithmic time complexity for insertions and deletions.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by undertakerme** [comment]
Use Case: Randomized binary search trees.
Description: A combination of a binary search tree and a heap, treaps maintain a randomized structure that guarantees expected logarithmic time complexity for insertions and deletions.

**Comment by pankaj-bind** [comment]
Do not create a new issue until you complete the previous one.
