### ISSUE TITLE
[NEW ALGORITHM] Gabow's Algorithm for Strongly Connected Components

### ISSUE THREAD

**Issue by sandeepmaddheshiya** [AlgoGenesis/C#1007]
### Name:  
```Gabow's Algorithm```  

### About:  
We propose implementing Gabow's Algorithm for finding Strongly Connected Components (SCC) in a directed graph. This algorithm is a lesser-known but highly efficient alternative to Tarjan's Algorithm. Gabow’s approach uses two stacks to track nodes and efficiently determines SCCs, offering performance advantages in certain cases, particularly when graphs have dense structures or specific connectivity properties. Its runtime complexity remains O(V + E), where V is the number of vertices and E is the number of edges, matching the complexity of Tarjan's algorithm.

This feature will provide a faster solution for SCC detection in graphs where Tarjan's algorithm may not perform as efficiently due to practical constraints.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Contributor in Hactoberfest
- [x] Want to work on it

**Comment by sandeepmaddheshiya** [comment]
@pankaj-bind please assign to me, i'll do it asap!

**Comment by pankaj-bind** [comment]
@sandeepmaddheshiya assigned

**Comment by sandeepmaddheshiya** [comment]
@pankaj-bind I've created a PR please review it.
Thanks!
