### ISSUE TITLE
[NEW ALGORITHM] Random Forest Regression

### ISSUE THREAD

**Issue by Shekhar-Raj** [AlgoGenesis/C#1009]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
<h2> Random Forest Regression</h2>

### About:  
I want to add new Algorithm  Random Forest Regression, Pls assign the issue so that i can contribute successfully

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
@Shekhar-Raj assigned
