### ISSUE TITLE
[NEW ALGORITHM] Hirschberg's Algorithm for Longest Common Subsequence

### ISSUE THREAD

**Issue by sandeepmaddheshiya** [AlgoGenesis/C#1010]
### Name:  
```Hirschberg's Algorithm```  

### About:  
This feature introduces Hirschberg's Algorithm, a space-efficient algorithm for solving the Longest Common Subsequence (LCS) problem. Hirschberg's algorithm uses a divide-and-conquer approach to reduce the space complexity from O(mn) to O(m + n), where m and n represent the lengths of the input sequences. While maintaining the same time complexity as the standard dynamic programming method, this algorithm dramatically reduces memory usage, making it ideal for solving LCS on large inputs.

This optimization will significantly improve performance in memory-constrained environments

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Contributor in Hacktoberfest
- [x] Want to work on it

@pankaj-bind please assign it to me, i'll do it asap!

**Comment by pankaj-bind** [comment]
Do not create new issue until you complete previous one.
