### ISSUE TITLE
[NEW ALGORITHM] Add Fast Fourier Transform (FFT) Algorithm

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#1013]
### Description:
The Fast Fourier Transform (FFT) is an efficient algorithm for computing the discrete Fourier transform (DFT) and its inverse. It reduces the complexity of DFT from \(O(N^2)\) to \(O(N \log N)\), making it crucial for various applications in signal processing, image analysis, and more. Adding the FFT algorithm will provide students and developers with a powerful tool for analyzing frequency components in signals and improving the efficiency of many computational problems.

**Use Cases:**
- Signal processing (audio, communications)
- Image processing (e.g., convolution)
- Solving partial differential equations (PDEs)
- Spectrum analysis in various scientific fields

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Kushagra614** [comment]
Can you please assogn me this issue. I would love to contribute

**Comment by divyalakshmi0** [comment]
Can you assign me this @pankaj-bind

**Comment by pankaj-bind** [comment]
@divyalakshmi0 assigned
