### ISSUE TITLE
[NEW ALGORITHM] - Algorithimic trading algo - Simple moving average

### ISSUE THREAD

**Issue by Kushagra614** [AlgoGenesis/C#1031]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[SMA Strategy]```  

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by Kushagra614** [comment]
I would love to add some Algo Trading Startigies and thier algorithms. please assign me this.
@mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
@Kushagra614 : Surely, I will assign this to you when I get ownership of this repo.

**Comment by Kushagra614** [comment]
Oh 

> @Kushagra614 : Surely, I will assign this to you when I get ownership of this repo.

my bad

**Comment by pankaj-bind** [comment]
@Kushagra614 assigned
