### ISSUE TITLE
[NEW ALGORITHM] Queue Implementation Using an Array

### ISSUE THREAD

**Issue by aditiverma-21** [AlgoGenesis/C#1040]
### Name:  
Queue Implementation Using an Array

### About:  
The Queue structure has an array items to store queue elements, along with two integer indices, front and rear, to keep track of the front and rear of the queue.

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by aditiverma-21** [comment]
Can you assign this to me?

**Comment by pankaj-bind** [comment]
@aditiverma-21 assigned

**Comment by aditiverma-21** [comment]
@pankaj-bind Created the PR
