### ISSUE TITLE
Determine if a Number is Odd or Even using Bit Manipulation

### ISSUE THREAD

**Issue by Kamini8707** [AlgoGenesis/C#1045]
Description:
I would like to add a new feature to the repository: a program to determine if a given number is odd or even using bitwise operations. Instead of using the traditional modulus operator, this program will utilize the bitwise AND operator to perform the check in a more efficient manner.

Feature Details:
The program will take an integer input and check the least significant bit (LSB) using the bitwise AND operator (&).
If the LSB is 1, the number is odd; if it's 0, the number is even.
The time complexity of this solution is O(1), making it a highly efficient approach.

 Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

 Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
@Kamini8707 assigned
