### ISSUE TITLE
Find the Index of the First Occurrence in a String

### ISSUE THREAD

**Issue by madhumitha-b** [AlgoGenesis/C#1050]
---

### Name:  
Find the Index of the First Occurrence in a String

### About:  
I propose to add the "Find the Index of the First Occurrence in a String" problem to the repository. This problem involves locating the index of the first occurrence of a substring (needle) within a given string (haystack). It is a common problem in string manipulation and is useful for illustrating search algorithms.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by SKG24** [comment]
Name Sanat Kumar Gupta
Participation GSSOC'24 ext, hackoctober
Please assign this to me

**Comment by pankaj-bind** [comment]
@madhumitha-b assigned
