### ISSUE TITLE
[UPDATE ALGORITHM]  Implement the divide and conquer with swaps and comparisons

### ISSUE THREAD

**Issue by shivenyadavs** [AlgoGenesis/C#1052]
## Description:
Please describe the changes you want to make to the existing algorithm and why they are necessary.
I want to implement a divide and conquer approach to enhance the existing sorting algorithm, focusing on optimizing it through a combination of swaps and comparisons. This method will allow for a more efficient sorting process, especially for larger datasets, by breaking down the problem into smaller subproblems and solving them recursively. The use of swaps will help in reducing the number of comparisons needed, potentially improving the algorithm's overall time complexity.
## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

## Affected Algorithm:
Mention which algorithm you want to update and the specific directory where you want to change.
I suggest conducting performance benchmarks before and after implementing the changes to measure the improvements in efficiency. Additionally, incorporating a way to visualize the sorting process could be beneficial for users to understand how the divide and conquer strategy works in practice.
## Additional Information:
Any extra details or suggestions related to the update.

**Comment by lakshita10341** [comment]
can u assign me this issue

**Comment by shivenyadavs** [comment]
no actually i more interested in this
