### ISSUE TITLE
[NEW ALGORITHM] Bead Sort

### ISSUE THREAD

**Issue by shivenyadavs** [AlgoGenesis/C#1053]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Bead Sort

### About:  
Propose a new algorithm to be added to the repository
I want to implement Bead Sort, a non-comparative sorting algorithm that models the process of beads falling under gravity. This algorithm visually represents sorting in an engaging way and could be particularly interesting for educational purposes. It effectively sorts positive integers and leverages a unique approach that may help illustrate sorting concepts.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by shivenyadavs** [comment]
@AlgoGenesis can you assign this to me

**Comment by pankaj-bind** [comment]
@shivenyadavs assigned
