### ISSUE TITLE
[NEW ALGORITHM] Tower of Hanoi implementation using Stack

### ISSUE THREAD

**Issue by prishsha** [AlgoGenesis/C#106]
## Description:
I would like to contribute to the AlgoGenesis repo by adding the algorithm for Tower of Hanoi problem using Stack 

## Checklist:
- [x] Contributor in GSSoC-ext

- [x] Want to work on it

## Additional Information:
Tower of Hanoi is a very common question relating to implementation of Stack. While a more straight-forward approach is using recursion, implementation using Stack will help enhance understanding of the topic.

**Comment by kashishchadha** [comment]
i want to contibute in this .I have a good approach for this.
