### ISSUE TITLE
[NEW ALGORITHM] Recursive Inorder Traversal

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [AlgoGenesis/C#1063]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Recursive Inorder Traversal```  

### About:  
Inorder Traversal is a fundamental tree traversal technique used to visit all nodes of a binary tree in a specific order. In Inorder Traversal, the nodes are visited in the following sequence:

Left Subtree
Root Node
Right Subtree

Inorder traversal is particularly useful in scenarios where you need to process nodes in a sorted order, such as in binary search tree operations, expression tree evaluations, and generating sorted outputs of tree data.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by SKG24** [comment]
please assign this to me!
