### ISSUE TITLE
[NEW ALGORITHM] Adding Standard Greedy Algorithms

### ISSUE THREAD

**Issue by sumankr15** [AlgoGenesis/C#107]
## Description:
I want to add new folder having standard Greedy algorithms and its  documentation.
## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
- [x] Willing to add standard greedy algorithms

## Additional Information:
Algorithms which I will be adding are -
1.Indian coin change
2.Activity selection problem
3.Fractional knapsack
4.Optimal Merge Pattern
5.Expedi
6.Maximum and minimum difference

I will be adding these algorithms with its documentation having proper explanations.
Please do add gssoc and hacktoberfest label.

**Comment by pankaj-bind** [comment]
@sumankr15 go for it
