### ISSUE TITLE
Documentation Site 

### ISSUE THREAD

**Issue by yashksaini-coder** [AlgoGenesis/C#1074]
@pankaj-bind @ajay-dhangar My main approach is to create a documentation website, that will be used to render the Markdown files for all the C algorithms, add in the list with proper navigation.

**Comment by yashksaini-coder** [comment]
can you assign this issue to me as GSSoC-ext contributor.

**Comment by 2004san** [comment]
i want to work on this issue @yashksaini-coder

**Comment by pankaj-bind** [comment]
@yashksaini-coder assigned

**Comment by yashksaini-coder** [comment]
hi bro I need one more day nearly done with the site

**Comment by pankaj-bind** [comment]
Yes, you can.

**Comment by yashksaini-coder** [comment]
hi @pankaj-bind can you add me as a collaborator to commit the sites folder setup from the fork
