### ISSUE TITLE
[NEW ALGORITHM]   Binary Tree Algorithm: In-order Traversal

### ISSUE THREAD

**Issue by Sivasaiklu** [AlgoGenesis/C#1082]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:
```[NEW ALGORITHM] Binary Tree Algorithm: In-order Traversal```

### About:
This issue proposes the addition of the **in-order traversal algorithm** for binary trees. This algorithm traverses the left subtree first, visits the root, and then traverses the right subtree. It is particularly useful in binary search trees for retrieving elements in ascending order.

---

### Labels:
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---

This ensures only one algorithm is proposed at a time and follows the specified guidelines.

**Comment by banasmita24** [comment]
Please assign me this. I want address. this new algorithm.
Thank you :)
