### ISSUE TITLE
[NEW ALGORITHM] sliding window algorithm 

### ISSUE THREAD

**Issue by Theboycut05** [AlgoGenesis/C#1084]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]``` 
Sliding window algorithm 

### About:  
Propose a new algorithm to be added to the repository
The sliding window algorithm is a technique used in computer science to process data sequentially, often in a streaming or online fashion. It involves maintaining a window of a fixed size that moves over the data, allowing for efficient processing of large datasets without storing the entire dataset in memory.
Key components of the sliding window algorithm:
 * Window size: The number of elements that are currently within the window at any given time.
 * Data stream: The continuous flow of data elements being processed.
 * Window operations: The specific calculations or actions performed on the elements within the window.
Common use cases of the sliding window algorithm:
 * Maximum contiguous subarray sum: Finding the subarray with the largest sum within a given array.
 * Longest substring without repeating characters: Determining the longest substring in a string that does not contain any repeated characters.
 * Average of a sliding window: Calculating the average value of elements within a sliding window.
 * Data stream analysis: Processing large amounts of data in real-time, such as network traffic analysis or sensor data processing.
Steps involved in implementing the sliding window algorithm:
 * Initialize the window: Create an empty window of the desired size.
 * Process data elements:
   * Add the next data element to the window.
   * Perform the necessary window operations on the elements within the window.
   * If the window size exceeds the desired limit, remove the oldest element from the window.
 * Repeat: Continue processing data elements until the end of the data stream is reached.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by SKG24** [comment]
Hey!
If possible I would also like to contribute
Name sanat kumar gupta
Participation gssoc'24 ext, hackoctober

Thank you

**Comment by coderhetal** [comment]
I m a gssoc extended contributor . Please assign this task to me.

**Comment by Theboycut05** [comment]
@pankaj-bind 
I requested PR you assigned me this already !
