### ISSUE TITLE
[NEW ALGORITHM] Edmonds-Karp algorithm for maximum flow

### ISSUE THREAD

**Issue by Anirudra16** [AlgoGenesis/C#1085]
The Edmonds-Karp algorithm is a method for solving the maximum flow problem in a flow network, which involves finding the maximum flow from a source node to a sink node while respecting edge capacities.

Key Points:
- Flow Network: A directed graph where edges have capacities.
- Goal: Maximize flow from source to sink.
- Breadth-First Search (BFS): Used to find the shortest augmenting path (path with available capacity) from source to sink.
- Residual Graph: A graph showing remaining capacities after considering the current flow.

Steps:
- Start with zero flow on all edges.
- Use BFS to find an augmenting path in the residual graph.
- Increase the flow along this path by the minimum available capacity.
- Update the residual graph and repeat until no more augmenting paths are found.
- The algorithm runs in O(V * E²) time, where V is the number of vertices and E is the number of edges.

Please assign me this as I want to work on it.... @pankaj-bind 

- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
@Anirudra16 assigned

**Comment by lakshmirajvagu** [comment]
@pankaj-bind please assign it to mee pleasee
