### ISSUE TITLE
[NEW ALGORITHM] Brooks' theorem for graph coloring

### ISSUE THREAD

**Issue by Anirudra16** [AlgoGenesis/C#1086]
Brooks' Theorem states that any connected, undirected graph G, G can be colored with at most Δ colors (where Δ is the maximum degree of the graph), except in two special cases: complete graphs and odd cycles, which require Δ + 1 colors.

Key Points:

- Graph Coloring: Assign colors to vertices such that no two adjacent vertices share the same color.
- Bound: For most graphs, the chromatic number is at most equal to the maximum vertex degree.
- Exceptions: Complete graphs and odd cycles.

Applications:

- Scheduling problems
- Register allocation in compilers
- Resource management

Please assign me this as I want to work on it @pankaj-bind 

- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create new issues until your previous one complete, wait until you’re assigned.
