### ISSUE TITLE
Add quiz on each algorithm and show results

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [AlgoGenesis/C#1088]
Add quiz on each algorithm and show results
it helps the viewers to test what they learnt 

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level3```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by killerjoker73** [comment]
Please assign this to me
