### ISSUE TITLE
[NEW ALGORITHM] Depth First Search and Breadth First Search Using Tree

### ISSUE THREAD

**Issue by SatyaJaiss** [AlgoGenesis/C#109]
## Description:
I Would like to add Depth First Search Algorithm Using Tree. I can provide you either in C or C++, whatever you want.

@sanjay-kv Kindly Assign to me

## Checklist:
- [] Contributor in GSSoC-ext
- [] Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by Biswajeet124** [comment]
I would like to work on this project. Please assign it to me.
