### ISSUE TITLE
[NEW ALGORITHM] Floyd’s Tortoise and Hare Algorithm

### ISSUE THREAD

**Issue by anushkaa-dubey** [AlgoGenesis/C#1093]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Floyd’s Tortoise and Hare Algorithm

### About:  
Propose a new algorithm to be added to the repository
Floyd’s Cycle Detection Algorithm is a pointer-based technique to detect cycles in a linked list. If a linked list contains a cycle, two pointers moving at different speeds will eventually meet. This algorithm is widely known for its simplicity and efficiency, operating in O(n) time and O(1) space.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ X] Contributor in GSSoC-ext
- [ X] Want to work on it

**Comment by anushkaa-dubey** [comment]
Please assign this issue to me.

**Comment by jashwanthbavandlapalli** [comment]
Please assign this issue to me @Aditijainnn

**Comment by pankaj-bind** [comment]
Do not create new issues until your previous one complete, wait until you’re assigned.

**Comment by anushkaa-dubey** [comment]
Please assign this issue to me
