### ISSUE TITLE
[NEW ALGORITHM] Reservoir Sampling Algorithm

### ISSUE THREAD

**Issue by anushkaa-dubey** [AlgoGenesis/C#1094]
### Name:  
Reservoir Sampling Algorithm

### About:  
Propose a new algorithm to be added to the repository
Reservoir sampling is an algorithm for randomly selecting a subset of k elements from a stream or large dataset of unknown size n. It ensures that every element has an equal probability of being chosen, even if the dataset is enormous or continuously arriving (like a data stream).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create new issues until your previous one complete, wait until you’re assigned.
