### ISSUE TITLE
Skyline Problem

### ISSUE THREAD

**Issue by Aditijainnn** [AlgoGenesis/C#1098]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
Skyline Problem

### About:  
Propose a new algorithm to be added to the repository
The Skyline algorithm computes the outline or silhouette of a set of overlapping rectangles in a 2D plane by processing their edges and maintaining a priority queue of active heights.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by jashwanthbavandlapalli** [comment]
Please assign me this @Aditijainnn

**Comment by pankaj-bind** [comment]
@Aditijainnn assigned
