### ISSUE TITLE
N-ary Search

### ISSUE THREAD

**Issue by Priyanshu1035** [AlgoGenesis/C#1099]
### Name:  
```N-ary Search```  

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
    Kindly assign this issue to me.
- [Y] Contributor in GSSoC-ext
- [Y] Want to work on it

**Comment by killerjoker73** [comment]
I would like to be assigned this task as part of GSSoC, as I am a passionate competitive programmer with a strong interest in contributing to open-source projects. Through my experience in solving algorithmic challenges, I have developed a solid foundation in data structures, algorithms, and problem-solving.

**Comment by lakshmirajvagu** [comment]
@pankaj-bind please assign it to me
