### ISSUE TITLE
Addition of Depth First Search in Searching Algos.

### ISSUE THREAD

**Issue by Shariq2003** [AlgoGenesis/C#11]
@pankaj-bind 
I am going to add the Linear Search Algorithm in the Searching Algorithms.
With the proper Objective and Explaination, with proper code in C.

Please Assign this to me.

**Comment by pankaj-bind** [comment]
@Shariq2003 Go for it.

**Comment by Shariq2003** [comment]
@pankaj-bind i have added that, and also check the DFS too,
If both of them meets the criteria then please accept the Pull requests

Also please add Lebels to this Tasks.
thanking you
