### ISSUE TITLE
[NEW ALGORITHM] Doubly Linked List, Singly Linked List, Circular Linked List

### ISSUE THREAD

**Issue by SatyaJaiss** [AlgoGenesis/C#110]
## Description:
I Would like to add the algorithms of Doubly Linked List, Singly Linked List and Circular Linked List.

@pankaj-bind  Kindly assign it to me
## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Linked Lists are the important concept for the DSA.

**Comment by mehul-m-prajapati** [comment]
@SatyaJaiss I am not owner this repo... @pankaj-bind will assign it

**Comment by ARYAN-ANSUMAN-SAHOO** [comment]
I want to contribute to this issue please assign me this task

**Comment by Biswajeet124** [comment]
I would like to work on this project. Please assign it to me.
