### ISSUE TITLE
[NEW ALGORITHM] Reverse Integer

### ISSUE THREAD

**Issue by Susmita0202** [AlgoGenesis/C#1104]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]  Reverse Integer```  

### About:  
Given a signed 32 bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32 bit integer range [-2^31, 2^31-1], then return 0.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes ] Contributor in GSSoC-ext
- [ yes] Want to work on it

**Comment by Susmita0202** [comment]
Please assign me this issue
@pankaj-bind

**Comment by coderhetal** [comment]
I m a gssoc extended contributor .Please assign this to me.

**Comment by pankaj-bind** [comment]
@Susmita0202 assigned

**Comment by lakshmirajvagu** [comment]
@pankaj-bind please assign it to me
