### ISSUE TITLE
[UPDATE ALGORITHM] Adding node deletion method in linked Lits

### ISSUE THREAD

**Issue by rahulbamnuya** [AlgoGenesis/C#1106]
## Description:
I would like to add how to delete an node in singly linked list in all cases like 
a. if delete node is terminal.
b. if delete node is head 
c. is delete node in other place

## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

## Affected Algorithm:
Mention which algorithm you want to update and the specific directory where you want to change.
LinkedList
## Additional Information:
Any extra details or suggestions related to the update.

**Comment by pankaj-bind** [comment]
Do not create new issues until your previous one complete, wait until you’re assigned.
