### ISSUE TITLE
[UPDATE ALGORITHM]  I would like to add an algo through which we can find first unique element in array

### ISSUE THREAD

**Issue by rahulbamnuya** [AlgoGenesis/C#1109]
## Description:
I would like to add an algo through which we can find first unique element in array.

## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

## Affected Algorithm:
Mention which algorithm you want to update and the specific directory where you want to change.

## Additional Information:
Any extra details or suggestions related to the update.

**Comment by pankaj-bind** [comment]
Do not create new issues until your previous one complete, wait until you’re assigned.
