### ISSUE TITLE
[NEW ALGORITHM]  PageRank Algorithm

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [AlgoGenesis/C#1114]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
 PageRank Algorithm 

### About:  
this algo is about Graph Algorithm

---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create new issues until your previous one complete, wait until you’re assigned.

**Comment by SanikaBhalerao1345** [comment]
@pankaj-bind I have completed my previous issue and it is merger too 
Of Heavy -light algorithm
