### ISSUE TITLE
[NEW ALGORITHM] Lexicographically Smallest Rotation 

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#1115]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   Lexicographically Smallest Rotation 

### About:  
The Lexicographically Smallest Rotation algorithm determines the smallest possible string that can be obtained by rotating a given string. This algorithm checks all possible rotations and returns the one that comes first in lexicographical order.

Example Input:

S = "bca"
Example Output:

"acb"
This algorithm is useful for applications like circular pattern recognition and DNA sequence analysis.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [ YES] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create new issues until your previous one complete, wait until you’re assigned.
