### ISSUE TITLE
[NEW ALGORITHM]  Non-Overlapping Interval Merging

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#1116]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Non-Overlapping Interval Merging

### About:  
The Non-Overlapping Interval Merging algorithm selects the maximum number of non-overlapping intervals from a given list of intervals. The algorithm uses a greedy approach by sorting intervals based on their end times, ensuring that the maximum number of non-overlapping intervals is selected.

Example Input:

Intervals = [(1, 3), (2, 4), (3, 5), (6, 8)]
Example Output:

3
This algorithm is useful in scheduling problems, timeline-based applications, and other interval-based scenarios.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [YES ] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create new issues until your previous one complete, wait until you’re assigned.
