### ISSUE TITLE
[NEW ALGORITHM] Valid  Parentheses 

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1123]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Valid Parentheses```  

### About:  
Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.

An input string is valid if:

Open brackets must be closed by the same type of brackets.
Open brackets must be closed in the correct order.
Every close bracket has a corresponding open bracket of the same type.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes]Want to work on it
 Please assign me the issue so that I can contribute 
@pankaj-bind

**Comment by coderhetal** [comment]
I m a gssoc extended contributor .Please assign this task to me for the cpp code .

**Comment by Dipanita45** [comment]
Please assign me this issue
