### ISSUE TITLE
[NEW ALGORITHM] Rotate Right by k in linked list

### ISSUE THREAD

**Issue by SKG24** [AlgoGenesis/C#1126]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Rotate Right by k in linked list
```[NEW ALGORITHM]```  

### About:  
I would like to add a new feature to the repository that implements a function to rotate a linked list to the right by k places, given a pointer to the head of the list. For example, if the input is head = [1, 2, 3, 4, 5] and k = 2, the output should be [4, 5, 1, 2, 3]. 

Approach: 
The rotateRight function uses a two-step approach: first, it calculates the length of the linked list and determines the effective rotations needed by taking k % len. Then, it identifies the new head by traversing to the appropriate node, relinks the list, and adjusts the pointers to complete the rotation. This method ensures efficiency and handles edge cases effectively.

---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

Name: Sanat Kumar Gupta

**Comment by SKG24** [comment]
Please assign this to me.
Thank you!

**Comment by SKG24** [comment]
I have other algorithms too. Should i create new issue for them?

**Comment by pankaj-bind** [comment]
@SKG24 assigned

**Comment by pankaj-bind** [comment]
> I have other algorithms too. Should i create new issue for them?

Do not. Until this issue is resolved and PR gets merged.
