### ISSUE TITLE
[NEW ALGORITHM] Principal Component Analysis (PCA)

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#1134]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   Principal Component Analysis (PCA)

### About:  
Principal Component Analysis (PCA) is a widely used dimensionality reduction technique in machine learning and data analysis. It helps reduce the number of features in a dataset by projecting it onto a lower-dimensional subspace, while preserving as much variability (information) as possible. PCA transforms correlated features into a set of linearly uncorrelated components called principal components, which can be used for visualization, noise reduction, and speeding up machine learning models.

Explanation:
Purpose: The purpose of PCA is to reduce the dimensionality of the dataset while retaining the most important variance in the data.
Steps:
1.Standardize the data (mean centering).
2.Compute the covariance matrix of the data.
3.Compute the eigenvalues and eigenvectors of the covariance matrix.
4.Select the top k eigenvectors based on the highest eigenvalues to form the principal components.
5.Transform the data using the selected eigenvectors.

PCA is useful for feature extraction, visualization of high-dimensional data, and noise reduction, making it a key tool in machine learning pipelines.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [ YES] Want to work on it

**Comment by coderhetal** [comment]
I m gssoc extended contributor . Please assign this task to me .
