### ISSUE TITLE
Make a Plateform to hold this all Algorthms at a single place.

### ISSUE THREAD

**Issue by Shariq2003** [AlgoGenesis/C#114]
As all these algorithms are in a folder it may be somehow and most of the time too much difficult to interact as a user.
What if we can move all these Algo to a single platform Named as AlgoHUB or something else that the admin likes.

@sanjay-kv @pankaj-bind Initailly I am going to make a landing Page that will list all the Algos on a single page as a list of Cards.

I know this is going to be a big issue, that's why I am going to break this into smaller issues after when you approve this idea.

**Comment by sanjay-kv** [comment]
@Shariq2003 for future queries on assigning issue, you need not tag me, because I don't have privilege to assign issue. 
i will be only managing labels.

**Comment by pankaj-bind** [comment]
@Shariq2003 It we have plan for it, but we'll do in future.
