### ISSUE TITLE
[NEW ALGORITHM] Sum of Digits using Recursion

### ISSUE THREAD

**Issue by iAmDiksha** [AlgoGenesis/C#115]
## Description:
The "Sum of Digits" problem involves calculating the total of all individual digits in a given integer using a recursive approach.

## Checklist:
- [✔ ] Contributor in GSSoC-ext
- [✔ ] Want to work on it
- [✔] Contributor in Hacktoberfest

**Comment by ARYAN-ANSUMAN-SAHOO** [comment]
I want to contribute to this issue please assign me this task

**Comment by kashishchadha** [comment]
i want to contribute to this issue .. i have better approach and skill pls assign me this

**Comment by pankaj-bind** [comment]
@iAmDiksha Try it
