### ISSUE TITLE
[NEW ALGORITHM] To Find the class of an IP Address

### ISSUE THREAD

**Issue by abhinov956tech-developer** [AlgoGenesis/C#1153]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Find the class of an IP Address
```[NEW ALGORITHM]```  

### About:  This algorithm finds the IP address entered by the user and identifies its class (A, B, C, D, or E).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [ YES ] Want to work on it

**Comment by killerjoker73** [comment]
Please assign this to me

**Comment by abhinov956tech-developer** [comment]
@pankaj-bind Please assign to me this. I'll do it asap
