### ISSUE TITLE
[NEW ALGORITHM] Optimal Binary Search Tree

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#1159]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Optimal Binary Search Tree

### About:  
The Optimal Binary Search Tree algorithm is used to construct a binary search tree from a given set of nodes with associated frequencies (probabilities of accessing them). The goal is to build a binary search tree with the minimal expected search cost. This problem is highly relevant in the context of database query optimization and compiler design.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [ YES] Want to work on it

**Comment by supreetkaursareen** [comment]
Can you assign it to me?

**Comment by pankaj-bind** [comment]
Do not create unnecessary multiple issues
