### ISSUE TITLE
Trie Data Structure (Prefix Tree)

### ISSUE THREAD

**Issue by AmanKumar1115** [AlgoGenesis/C#116]
@pankaj-bind  I want add details about trie data structure.

I will also add following question :
1. Implement Trie
2. Longest Common Prefix
3. Word Break

**Comment by pankaj-bind** [comment]
@AmanKumar1115 Ok

**Comment by AmanKumar1115** [comment]
@pankaj-bind  Can merge my pull  request for  Add implementation of Kosaraju's Algorithm #105
