### ISSUE TITLE
Johnson's Algorithm

### ISSUE THREAD

**Issue by Saurabhsing21** [AlgoGenesis/C#1162]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Johnson's Algorithm```  

### About:  
Purpose: Solves the all-pairs shortest paths problem in sparse graphs.
Details: Johnson’s Algorithm uses a combination of Bellman-Ford and Dijkstra to compute shortest paths efficiently for sparse graphs.
Usage: Appropriate when dealing with large graphs with few edges.
Example in C: Johnson’s Algorithm requires understanding and implementation of both Bellman-Ford and Dijkstra in combination.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
@Saurabhsing21 assigned
