### ISSUE TITLE
Add Max Heap Implementation

### ISSUE THREAD

**Issue by karthikyandrapu** [AlgoGenesis/C#1164]
### About:

1. The program implements a **Max Heap** data structure. A max heap is a binary tree where the value of each node is greater than or equal to its children, ensuring that the maximum value is always at the root.
2. It provides basic operations like inserting elements, removing the maximum element, and retrieving the top (maximum) element.
3. **Heapify operations**: Elements are inserted or removed while maintaining the heap property through **up-heapify** (for insertions) and **down-heapify** (for removals).
4. The program is interactive, allowing users to add elements to the heap, display the top element, and pop elements, adjusting the heap size dynamically.
   
### Labels:  
```gssoc-ext, hacktoberfest```

### Assignees:  
- [ ] Contributor in GSSoC-ext  
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
@karthikyandrapu assigned
