### ISSUE TITLE
[NEW ALGORITHM] (Flash Sort Code & README.md)

### ISSUE THREAD

**Issue by VahantSharma** [AlgoGenesis/C#1166]
### Description

- I would like to add a new algorithm that implements the Flash Sort algorithm to efficiently sort an array of integers. 
- Flash Sort is a hybrid algorithm that combines features of distribution sorting and insertion sort to achieve improved time complexity for specific types of datasets. 
- This functionality aims to sort arrays by efficiently classifying and swapping elements into their correct positions and then applying a final insertion sort pass to fine-tune the ordering.

---

### Proposed Changes:

1. Algorithm Implementation: Add the code for the Flash Sort algorithm.

      Step 1: Find the minimum and maximum elements in the array.
      Step 2: Create buckets based on the value range of the array.
      Step 3: Distribute elements into their respective buckets.
      Step 4: Use a permutation-based approach to move elements into the correct 
     positions.
      Step 5: Apply insertion sort to finalize the sorting process.

2. Add README.md file:
      
      (1) Explanation: Include a detailed explanation of the Flash Sort concept.
      (2) Step-by-step Guide: Provide a guide on how to use the Flash Sort algorithm, including code examples and usage instructions.

---
### CheckList:

 - [x] Contributor in GSSoC-ext.
 - [x] Want to work on this issue.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

**Comment by basavarajakj** [comment]
@VahantSharma  could you please assign me I will start to work on this

**Comment by VahantSharma** [comment]
@basavarajakj I had already created a PR and solved the issue.
