### ISSUE TITLE
[NEW ALGORITHM]  Convex Hull (Computational Geometry)

### ISSUE THREAD

**Issue by abishek1740P** [AlgoGenesis/C#1167]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### About:  
The Convex Hull problem is a fundamental problem in computational geometry, where given a set of points in a 2D plane, the goal is to find the smallest convex polygon that contains all the points. This polygon is called the convex hull of the points.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1, hactoberfest-accepted```

---

### Assignees:  
- [.] Contributor in GSSoC-ext
- [.] Want to work on it

**Comment by pankaj-bind** [comment]
@abishek1740P assigned
