### ISSUE TITLE
[NEW ALGORITHM] Implementation of queue using stack

### ISSUE THREAD

**Issue by aditiverma-21** [AlgoGenesis/C#1169]
A queue can be implemented using two stacks. 
I am a gssoc contributor.
I am interested to do this task.

**Comment by aniruddhaadak80** [comment]
Create Program.c #1170 , please check.

**Comment by nikhilyadav-20** [comment]
please assign this problem to me

**Comment by pankaj-bind** [comment]
@aniruddhaadak80 we prefer first come first serve

**Comment by aditiverma-21** [comment]
@pankaj-bind please assign this to me so that I can add PR.

**Comment by pankaj-bind** [comment]
@aditiverma-21 assigned

**Comment by aditiverma-21** [comment]
@pankaj-bind Please review the PR and let me know
