### ISSUE TITLE
[NEW ALGORITHM] Graham's Scan Algorithm in C

### ISSUE THREAD

**Issue by Sivasaiklu** [AlgoGenesis/C#1173]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### About:  

This issue proposes the addition of the Convex Hull algorithm using Graham's Scan. The Convex Hull problem is essential in computational geometry, where the goal is to find the smallest convex polygon that encloses a given set of points in a 2D plane. Graham's Scan algorithm solves this problem with a time complexity of O(n log n) by sorting the points and processing them with a stack-based approach to ensure a counterclockwise traversal.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by supreetkaursareen** [comment]
@Sivasaiklu can you assign it to me?

**Comment by Sivasaiklu** [comment]
> @Sivasaiklu can you assign it to me?

@supreetkaursareen I cant assign, Project Admin have to assign, I am also a contributor

**Comment by pankaj-bind** [comment]
@Sivasaiklu assigned
