### ISSUE TITLE
[NEW ALGORITHM] Monotonic Stack Questions section

### ISSUE THREAD

**Issue by Pradyuman554** [AlgoGenesis/C#1176]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.
---

### Name:  
```[NEW ALGORITHM] Monotonic Stack``` 
---

### Propose adding a new algorithm for the Monotonic Stack, which maintains elements in a sorted order (increasing or decreasing) as they are processed. It is useful for solving problems related to ranges, like finding the next greater or smaller element in O(n) time. This addition will expand the repository's collection of efficient data structure algorithms.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```
---

### Assignees:  
- [YES] Contributor in GSSoC-ext
- [YES] Want to work on it

**Comment by Pradyuman554** [comment]
@T-Fathima Please assign this task to me

**Comment by pankaj-bind** [comment]
Do not create unnecessary multiple issues
