### ISSUE TITLE
[NEW ALGORITHM] Best Time to Buy and Sell Stock in Dynamic Programming.

### ISSUE THREAD

**Issue by Lokesh11868** [AlgoGenesis/C#1177]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Best Time to Buy and Sell Stock in Dynamic Programming.```  

### About:  
Given an array where each element represents the stock price on a given day, find the maximum profit you can achieve by making at most one transaction (buying one stock and selling one stock).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by aniruddhaadak80** [comment]
@pankaj-bind please assign this to me
