### ISSUE TITLE
[NEW ALGORITHM] Add new algorithms to queue section.

### ISSUE THREAD

**Issue by SurajSG23** [AlgoGenesis/C#118]
Hey, i noticed that in queue file there were not many algorithms , i would really like to add more algos like Concurrent Queue, Double Priority Queue ,Drop-Out Queue and few more.

![image](https://github.com/user-attachments/assets/33726b91-427d-44ac-8eff-919d6c148dda)

i would like to update your file under GSSoC and Hacktober fest

**Comment by pankaj-bind** [comment]
@SurajSG23, you're assigned
