### ISSUE TITLE
[NEW ALGORITHM] Add Hashmap Data Structure

### ISSUE THREAD

**Issue by Riya7045** [AlgoGenesis/C#1181]
# ``` Hashmap```  

## About:  
We need to implement a hashmap (hash table) data structure to support efficient key-value storage and retrieval. The hashmap will offer basic functionalities like insertion, search, and deletion, with collision handling via chaining using linked lists. This implementation should work for integer keys and values as the primary use case.

#### Hashmap Structure:

Define a hashmap structure that includes an array of pointers (buckets).
Each bucket should point to a linked list to handle collisions (chaining).

#### Hash Function:

Create a hash function that maps integer keys to an index based on the table size using modulo (% operator).

#### Basic Operations:
Insert: Add a key-value pair to the hashmap. Handle collisions by inserting the new entry into a linked list.
Search: Retrieve a value based on a given key. If the key is not found, return a default error code (e.g., -1).
Delete: Remove a key-value pair from the hashmap, handling re-linking of nodes in the linked list for collision cases.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by lakshita10341** [comment]
can u assign me this issue?

**Comment by pankaj-bind** [comment]
@Riya7045 assigned

**Comment by Riya7045** [comment]
ok i will start working on this issue.
