### ISSUE TITLE
[NEW ALGORITHM] Graph Algorithm

### ISSUE THREAD

**Issue by SumaLatha2023** [AlgoGenesis/C#1183]
### Name:  
```[Floyd-Warshall Algorithm]```  

### About:  
Propose a new algorithm to be added to the repository

This is an all-pairs shortest path algorithm for weighted graphs. It can be a valuable addition to the Graph Algorithms section, focusing on dynamic programming.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by SumaLatha2023** [comment]
assign this issue to me..

**Comment by pankaj-bind** [comment]
https://github.com/AlgoGenesis/C/blob/main/Mathematical%20Algorithms/Shortest%20Path%20Algorithms/Floyd-Warshall%20algorithm/Program.c
