### ISSUE TITLE
Add a  folder of Graph related algorithms

### ISSUE THREAD

**Issue by Ankitha2130** [AlgoGenesis/C#119]
Includes all graph related algorithms like BFS, DFS, Detecting cycle in directed and undirected graph, Topological sort, shortest path, Prim's algorithm, Dijkstra's algorithm, Kosaraju's algorithm, Kruskal's algorithm, Bellman Ford and Tarjan's algorithm.

Please assign this issue to me under hacktoberfest-accepted tag.

**Comment by pankaj-bind** [comment]
@Ankitha2130 create new issue after checking what are missing, some of them you mentioned are already present
