### ISSUE TITLE
[NEW ALGORITHM] Dynamic Threshold Clustering (DTC)

### ISSUE THREAD

**Issue by basavarajakj** [AlgoGenesis/C#1193]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Dynamic Threshold Clustering```  

### About:  
Propose a new algorithm to be added to the repository
1. The algorithm adjusts the threshold for forming clusters based on the density of points in a local neighborhood.
2. It allows the use of various distance metrics (Euclidean, Manhattan, etc.) to accommodate different types of data.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Please don't raise a PR until you are assigned.
