### ISSUE TITLE
[NEW ALGORITHM] Implementation of BST, AVL trees and Red-Black trees

### ISSUE THREAD

**Issue by srii5477** [AlgoGenesis/C#120]
## Description:
I would like to implement creation, insertion, deletion and traversal in binary search trees, AVL trees and red-black trees.
Please assign this to me under the hacktober-accepted label.
## Checklist:
- [Y] Contributor in GSSoC-ext
- [Y] Want to work on it

**Comment by pankaj-bind** [comment]
@srii5477 you can start

**Comment by srii5477** [comment]
Please add the hacktoberfest-accepted label
