### ISSUE TITLE
[NEW ALGORITHM] Wiggle Subsequence Using 1D Array 

### ISSUE THREAD

**Issue by SarthVader2004** [AlgoGenesis/C#1200]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Wiggle Subsequence Algorithm```  

### About:  
The Wiggle Subsequence algorithm finds the length of the longest subsequence in a given array where the differences between successive numbers alternate between positive and negative. It is commonly solved using greedy techniques and dynamic programming with a time complexity of O(n).

This algorithm will enhance the repository’s collection of sequence-related algorithms and offers valuable insights for problems involving alternating patterns.

---

### Labels:  
```new algorithm, hacktoberfest```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by SarthVader2004** [comment]
@pankaj-bind please assign this issue to me!

**Comment by pankaj-bind** [comment]
@SarthVader2004 assigned

**Comment by pankaj-bind** [comment]
no update
