### ISSUE TITLE
Add Sliding window 

### ISSUE THREAD

**Issue by RahulPrasadYadav** [AlgoGenesis/C#1201]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Sliding window ]```  

### About:  
the purpose of a sliding window, in various fields like computer science, signal processing, and statistics, is to process data in a fixed-size window that moves or "slides" over a larger dataset. This technique is useful for efficiently handling problems that involve continuous streams of data or large datasets where processing the entire dataset at once is impractical.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X ] Contributor in GSSoC-ext
- [X ] Want to work on it

**Comment by pankaj-bind** [comment]
duplicate https://github.com/AlgoGenesis/C/pull/1128
