### ISSUE TITLE
[NEW ALGORITHM]  Add Interesting DP probelm : Domino and Tromino Tiling

### ISSUE THREAD

**Issue by SimranShaikh20** [AlgoGenesis/C#1202]
---

### Name:  
Dynamic Programming 

Problem Statments is here : 

You have two types of tiles: a 2 x 1 domino shape and a tromino shape. You may rotate these shapes.
Given an integer n, return the number of ways to tile an 2 x n board. Since the answer may be very large, return it modulo 109 + 7.

In a tiling, every square must be covered by a tile. Two tilings are different if and only if there are two 4-directionally adjacent cells on the board such that exactly one of the tilings has both squares occupied by a tile.

 

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---
@pankaj-bind assign me this issue!

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@SimranShaikh20 assigned
