### ISSUE TITLE
[NEW ALGORITHM] Addition of priority Queue

### ISSUE THREAD

**Issue by Salini-sat** [AlgoGenesis/C#1203]
### Name: Priority Queue  
```[NEW ALGORITHM]```  

### About:  
A priority queue is a type of queue that arranges elements based on their priority values. Elements with higher priority values are typically retrieved or removed before elements with lower priority values. Each element has a priority value associated with it. When we add an item, it is inserted in a position based on its priority value.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] I'm a contributor in GSSoC-ext
- [ ] I want to work on it
@pankaj-bind please assign me this

**Comment by Ritika-K7** [comment]
Hi @pankaj-bind ,
I hope you are doing well.
I'm a contributor in  GSSoC-ext. Please assign this to me.
