### ISSUE TITLE
[NEW ALGORITHM] DFA to NFA Conversion

### ISSUE THREAD

**Issue by Bhupendrakumar20** [AlgoGenesis/C#1219]
## Issue will be closed if:

1. You mention more than one algorithm. Create a separate issue for each once the current one is completed.
2. You propose an algorithm that is already present or has been mentioned in a previous issue.
3. You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  DFA to NFA Conversion

### About:  
The DFA to NFA conversion uses the Subset Construction algorithm to transform a Deterministic Finite Automaton (DFA) into a Non-Deterministic Finite Automaton (NFA).

**Steps**:

- Initialize the DFA transition table.
- Identify all possible state subsets.
- Generate NFA transitions from DFA states to each subset.
- Define final states based on DFA final states.

---

### Labels:  
``` new algorithm, gssoc-ext, hacktoberfest, level2

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

**Comment by Bhupendrakumar20** [comment]
Kindly assign this task to me

**Comment by pankaj-bind** [comment]
@Bhupendrakumar20 assigned
