### ISSUE TITLE
[NEW ALGORITHM] Square root Algorithm.

### ISSUE THREAD

**Issue by Harishankar14** [AlgoGenesis/C#122]
## Description:
Hey, i would like to work on Square root algorithm, Under square root algorithm, there would be three sections.
1.Combining algos.
2. Integer partitions.
3. Mo's algorithm.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

Please do assign me this.

**Comment by Uhalatha5** [comment]
@Harishankar14 Hi, I would love to contribute to #122 Square root algorithm as a GSSOC'24 contributor. Could you please assign this issue to me? I’m excited to improve the user experience and make the game more interactive. Thanks!

**Comment by pankaj-bind** [comment]
@Harishankar14 go for it
