### ISSUE TITLE
[NEW ALGORITHM] Naive Pattern Matching Algorithm

### ISSUE THREAD

**Issue by Bhupendrakumar20** [AlgoGenesis/C#1220]
## Issue will be closed if:

> You mention more than one algorithm. Create a separate issue for each algorithm once the current one is completed.
> You propose an algorithm that is already present or has been mentioned in a previous issue.
> You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Naive Pattern Matching Algorithm

### About:  
 The Naive Pattern Matching Algorithm searches for occurrences of a "pattern" string within a "text" string by sliding the pattern one by one and checking for matches. It checks from the start of the text, moving right if there's no match, until the end of the text is reached. 

**Time complexity:** 
𝑂(𝑚×𝑛) , where m is the length of the text and n is the length of the pattern.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level 2```

---

### Assignees:  
- [ yes] Contributor in GSSoC-ext
- [yes] Want to work on it

**Comment by Bhupendrakumar20** [comment]
kindly assign this task to me

**Comment by pankaj-bind** [comment]
Do not create unnecessary multiple issues
