### ISSUE TITLE
[NEW ALGORITHM] Red-Black Tree Implementation

### ISSUE THREAD

**Issue by shriyadindi** [AlgoGenesis/C#1221]
Red-Black Tree Implementation

Description: Red-Black Trees are a type of self-balancing binary search tree. Nodes in this tree have an additional "color" property that ensures the tree remains balanced during insertions and deletions.
Key Skills: Memory management, pointer manipulation, balancing conditions.
Complexity: High for both implementation and balancing rules (like color rotations).

```new algorithm, gssoc-ext, hacktoberfest, level2```

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Ritika-K7** [comment]
Hi @shriyadindi 
Please assign this to me. I would like to work on this.
