### ISSUE TITLE
[NEW ALGORITHM] Aho-Corasick String Matching Algorithm

### ISSUE THREAD

**Issue by shriyadindi** [AlgoGenesis/C#1222]
Aho-Corasick String Matching Algorithm

Description: The Aho-Corasick algorithm is used for searching multiple patterns within a text. It builds a Trie of keywords and uses failure links to efficiently find all patterns in a single pass.
Key Skills: Trie data structure, linked lists for failure links, efficient pattern matching.
Complexity: High, requiring solid understanding of Tries and finite automata.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create unnecessary multiple issues
