### ISSUE TITLE
[NEW ALGORITHM] Convex Hull using Graham’s Scan or Andrew's Monotone Chain

### ISSUE THREAD

**Issue by shriyadindi** [AlgoGenesis/C#1223]
Convex Hull using Graham’s Scan or Andrew's Monotone Chain

Description: Convex Hull algorithms find the smallest convex boundary around a set of points, useful in computational geometry.
Key Skills: Sorting, geometric calculations, understanding of stack-based structures.
Complexity: Moderate; geometric logic and stack usage can be challenging in C.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create unnecessary multiple issues
