### ISSUE TITLE
[NEW ALGORITHM] : Armstrong Number

### ISSUE THREAD

**Issue by VanshGarg06** [AlgoGenesis/C#1225]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
To find the Armstrong number in given range from 1 to n.

### About:  
Armstrong Numbers is one of the famous problem that is asked in most of the interviews. Armstrong numbers are the numbers in which the sum of the cube of the digits is equal to the number itself.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
- [ ]

**Comment by BarryByte** [comment]
@pankaj-bind Please assign this issue to me .

**Comment by VanshGarg06** [comment]
@pankaj-bind Please assign this issue to me as soon as possible so that i can open new issue for other algorithm as i have an idea.

**Comment by ShirshenduR** [comment]
please assign me this issue

**Comment by pankaj-bind** [comment]
@VanshGarg06 assigned
