### ISSUE TITLE
[NEW ALGORITHM] SVM Algorithm in Machine Learning

### ISSUE THREAD

**Issue by alo7lika** [AlgoGenesis/C#1229]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
**SVM Algorithm in Machine Learning**

### About:  
This issue proposes the addition of the Support Vector Machine (SVM) algorithm to the repository. SVM is a powerful supervised learning algorithm commonly used for classification tasks. It works by finding the optimal hyperplane that separates data points of different classes in a feature space. This algorithm is particularly effective for both linear and non-linear classification problems, thanks to its ability to utilize various kernel functions.

### Implementation Details:
The implementation will include:
- A brief explanation of the SVM algorithm and its working principles.
- Sample code implementations in one or more programming languages (e.g., Python, C++).
- An overview of the algorithm's time complexity and performance considerations.
- Example applications of SVM in real-world scenarios.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by alo7lika** [comment]
Assign me the task @pankaj-bind

**Comment by alo7lika** [comment]
> Assign me the task @pankaj-bind

@pankaj-bind

**Comment by pankaj-bind** [comment]
@alo7lika assigned
