### ISSUE TITLE
[NEW ALGORITHM] Minimum Machines for Maximum Output

### ISSUE THREAD

**Issue by Rishav123raj** [AlgoGenesis/C#1232]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Minimum Machines for Maximum Output]```  

### About:  
You are given a list of tasks, each requiring a certain amount of time to complete. You have multiple machines available, each with a specific speed that determines how fast it can complete tasks. Your goal is to determine the minimum number of machines needed to complete all tasks within a given time frame.

Input:
tasks: An array of integers where each element represents the time required for a task.
machines: An array of integers where each element represents the speed of a machine (higher means faster).
max_time: The maximum allowed time to complete all tasks.

Output:
An integer representing the minimum number of machines required to complete all tasks within max_time. If it is impossible, return -1.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level3```

---

### Assignees:  
- [ Yes] Contributor in GSSoC-ext
- [Yes ] Want to work on it

**Comment by Rishav123raj** [comment]
Please assign me this task @pankaj-bind

**Comment by pankaj-bind** [comment]
@Rishav123raj assigned
