### ISSUE TITLE
[NEW ALGORITHM] Leaf-Similar Trees 

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1233]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Leaf-similar Trees ```  

### About:  
Consider all the leaves of a binary tree, from left to right order, the values of those leaves form a leaf value sequence.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it 

Please assign me the issue 
@pankaj-bind

**Comment by Dipanita45** [comment]
Please please assign me the issue so that I can contribute 🙏 
@pankaj-bind

**Comment by pankaj-bind** [comment]
@Dipanita45 assigned

**Comment by Dipanita45** [comment]
Please reassign me 
@pankaj-bind
