### ISSUE TITLE
[NEW ALGORITHM] Addition of  Two-Way String-Matching Algorithm under String Algorithms

### ISSUE THREAD

**Issue by pratheekv39** [AlgoGenesis/C#1234]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Two-Way String-Matching Algorithm
### About:  
Propose a new algorithm to be added to the repository
I want to add this new algorithm under Strings Algorithms
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pratheekv39** [comment]
@pankaj-bind Can you please look into Issue #1100 ( PR #1208 ) of mine . Was it merged or was it closed ?? Thanks...

**Comment by pankaj-bind** [comment]
@pratheekv39 assigned
