### ISSUE TITLE
[NEW ALGORITHM] Implement Function to Check if a Tree is a BST or not

### ISSUE THREAD

**Issue by Kamini8707** [AlgoGenesis/C#1236]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Implement Function to Check if a Tree is a BST or not

Description: I would like to contribute by implementing a function to check if a binary tree is a binary search tree (BST). This function will ensure that for every node in the tree, all nodes in the left subtree are less than the node, and all nodes in the right subtree are greater.

Approach: The approach will involve recursively validating each node's value against an allowable range:
->Traverse the tree using recursion.
->For each node, confirm it lies within an allowed range.
->Update this range as we progress through the tree to validate BST properties.

Expected Output: The function should return true if the tree meets BST properties, false otherwise.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
@Kamini8707 assigned
