### ISSUE TITLE
[NEW ALGORITHM] Word Search in a 2D Grid Using Backtracking in C

### ISSUE THREAD

**Issue by Bhoomysingh10** [AlgoGenesis/C#1238]
#  Word Search in a 2D Grid Using Backtracking in C

### About:  
This algorithm solves the Word Search problem in a 2D grid using a backtracking approach. The objective is to determine if a given word can be constructed from adjacent cells in the grid, moving vertically or horizontally.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
@Bhoomysingh10 assigned

**Comment by Bhoomysingh10** [comment]
@pankaj-bind Kindly check !
