### ISSUE TITLE
[NEW ALGORITHM] I would like to enhance String Algorithms by adding the following new Algorithms i.e., Apostolico–Giancarlo Algorithm, BNDM (Backward Nondeterministic Dawg Matching), Bitap Algorithm (Approximate String Matching), Commentz-Walter Algorithm, Shift-Or Algorithm, Finite State Automaton Algorithm, Ukkonen’s Algorithm, Two-Way String-Matching Algorithm, Crochemore’s Algorithm, Zhu-Takaoka Algorithm.

### ISSUE THREAD

**Issue by pratheekv39** [AlgoGenesis/C#124]
## Description:

I would like to enhance String Algorithms by adding the following Algorithms:

1. Apostolico–Giancarlo Algorithm  
   - Description: An extension of the Boyer-Moore algorithm optimized for multiple pattern matching, allowing efficient backtracking.
   - Time Complexity: O(n + m)

2. BNDM (Backward Nondeterministic Dawg Matching)  
   - Description: A bitwise pattern matching algorithm that is an improvement over the BMH algorithm, especially effective for short patterns.
   - Time Complexity: O(nm)

3. Bitap Algorithm (Approximate String Matching)  
   - Description: Uses bitwise operations to perform approximate pattern matching, allowing a specified number of errors (insertions, deletions, or substitutions).
   - Time Complexity: O(nm)

4. Commentz-Walter Algorithm  
   - Description: A variation of the Boyer-Moore algorithm that improves efficiency when searching for multiple patterns simultaneously.
   - Time Complexity: O(n + m)

5. Shift-Or Algorithm  
   - Description: A bitwise algorithm that matches patterns by shifting a bitmask, making it effective for small alphabets.
   - Time Complexity: O(n)

6. Finite State Automaton Algorithm  
   - Description: Preprocesses the pattern into a finite state machine and then scans the text for matches in linear time.
   - Time Complexity: O(n + m)

7. Ukkonen’s Algorithm  
   - Description: Constructs a suffix tree in an online manner, which is efficient for solving a variety of string-related problems like pattern matching.
   - Time Complexity: O(n)

8. Two-Way String-Matching Algorithm  
   - Description: Combines prefix and suffix searches, allowing linear-time pattern matching in large texts.
   - Time Complexity: O(n)

9. Crochemore’s Algorithm  
   - Description: A hybrid algorithm that preprocesses both the text and pattern to detect matches using compact border arrays.
   - Time Complexity: O(n + m)

10. Zhu-Takaoka Algorithm  
   - Description: An extension of Boyer-Moore that uses two characters at a time to reduce the number of comparisons, improving average-case performance.
   - Time Complexity: O(n)

## Checklist:
- [ ✅] Contributor in GSSoC-ext
- [✅ ] Want to work on it

I have checked all issues for duplicates  and these algorithms have not yet been added . 
@pankaj-bind Please approve this task and assign it to me . I would love to work on it.

**Comment by mehul-m-prajapati** [comment]
@pratheekv39 : The description is way too long. Please divide these tasks into separate issues.

**Comment by pratheekv39** [comment]
@mehul-m-prajapati  I will create a new issue splitting the tasks
