### ISSUE TITLE
 Shortest distance between two cells in a matrix or grid

### ISSUE THREAD

**Issue by abhinov956tech-developer** [AlgoGenesis/C#1246]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Shortest distance between two cells in a matrix or grid
```[NEW ALGORITHM]```  

### About:  
In terms of pathfinding, the shortest distance between two cells in a matrix can be calculated using algorithms like Breadth-First Search (BFS).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by abhinov956tech-developer** [comment]
@pankaj-bind Please assign it to me. I really want to work on it

**Comment by pankaj-bind** [comment]
@abhinov956tech-developer assigned

**Comment by pankaj-bind** [comment]
no update
