### ISSUE TITLE
[NEW ALGORITHM] Reversing the linked list (reversing the links)

### ISSUE THREAD

**Issue by Tanyajain2006** [AlgoGenesis/C#1251]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Reversing the linked list
```[NEW ALGORITHM]```  

### About:  
Reversing the linked list basically wants to reverse the links of node by keeping the position of nodes same.
ex- 1->2->3->4->5->NULL
after reversal: NULL<-1<-2<-3<-4<-5

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Tanyajain2006** [comment]
Reversing the linked list in singly, circular singly, doubly and circular doubly linked list.

**Comment by Ritika-K7** [comment]
@Tanyajain2006 @pankaj-bind 
Please assign this to me . I would Like to work on this.

**Comment by Tanyajain2006** [comment]
> @Tanyajain2006 @pankaj-bind Please assign this to me . I would Like to work on this.

Hi Ritika, I'm so sorry. I have already done this. When the project admin agrees, I just have to create a pull request, that's it

**Comment by Tanyajain2006** [comment]
Hello sir, you just assigned it to me and now you have closed it. So,
should I now not work on it?
