### ISSUE TITLE
[NEW ALGORITHM] Intersection of two Arrays

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [AlgoGenesis/C#1255]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Intersection of Two Arrays]```  

### About:  
Two 1-D Arrays will be taken a new Array consisting of the common elements will be formed.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Arghya-Chakraborty0812** [comment]
@pankaj-bind Please assign this issue to me.

**Comment by pankaj-bind** [comment]
@Arghya-Chakraborty0812 assigned
