### ISSUE TITLE
[NEW ALGORITHM] Duck Number

### ISSUE THREAD

**Issue by ShirshenduR** [AlgoGenesis/C#1259]
## Issue will be closed if:

> 1) You mention more than one algorithm. Please create separate issues for each algorithm after the current one is completed.  
> 2) You propose an algorithm that already exists or is mentioned in a previous issue.  
> 3) You create a new issue without completing your previous one.

**Note:** These guidelines will be strictly followed. Non-compliance may result in the immediate closure of your issue.

---

### Name:  
```Duck Number```  

### About:  
Introduce an algorithm to identify **Duck Numbers**. A Duck Number is a positive number that contains at least one zero in any digit except the first. For example, 102 and 2405 are Duck Numbers, while 321 and 125 are not (since they either don’t have zeros or have one as the leading digit).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Interested contributors  

---

**Comment by ShirshenduR** [comment]
please assign me this issue

**Comment by pankaj-bind** [comment]
@ShirshenduR assigned
