### ISSUE TITLE
[NEW ALGORITHM] kadane's algorithm

### ISSUE THREAD

**Issue by sruthi070** [AlgoGenesis/C#126]
## Description:
Maximum subarray sum using kadane's algorithm

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Chandravan** [comment]
@sruthi070  please assign this issue to me. I'd love to work on it. Thank you!"

**Comment by harish08102004** [comment]
Hey @sruthi070 I can work on this.

**Comment by sruthi070** [comment]
@pankaj-bind please assign me this under gssoc extd

**Comment by pankaj-bind** [comment]
@sruthi070 you can start
