### ISSUE TITLE
[UPDATE ALGORITHM] Recursion / Next Permutation

### ISSUE THREAD

**Issue by o-CodeBlitz-o** [AlgoGenesis/C#1263]
## Description:
First of all I would like to address that the existing Algorithm is written in C++ so I would like to change it in C.

## Original C++ Code 

The original code generated all permutations of the array and then sorted them. After sorting, it checked each permutation until it found the current permutation and then picked the next one. This approach, while functional, has a few significant inefficiencies:

1. **Generating All Permutations**: Generating all possible permutations of an array of size \(n\) has a time complexity of \(O(n!)\), which is extremely slow for larger arrays.

2. **Sorting All Permutations**: After generating permutations, the code sorts them, adding another \(O(n! log(n!))\) complexity.

3. **Finding the Next Permutation**: Finally, it iterates through the sorted permutations to find the current permutation and the next one, which takes \(O(n!)\) time in the worst case.

## Optimized Approach

To find the next permutation, we can eliminate the need for generating all permutations and sorting them by directly using a more efficient algorithm that runs in \(O(n)\) time. Here’s how:

### Steps in the Optimized Code

1. **Find the Pivot**:
   - Traverse the array from the end to find the first index ("i") where ( {arr}[i] < {arr}[i + 1] ).
   - This step determines the position ("i") where we need to make the smallest change to reach the next lexicographical permutation.
   - **Why?**: The last increasing order identifies the position where a change is required to get to the next permutation.

2. **Find the Rightmost Successor**:
   - If such an index "i" is found, then from the end of the array, locate the smallest element that is larger than ("{arr}[i]") and swap them.
   - **Why?**: Swapping with the smallest larger element ensures the smallest change to reach the next permutation.

3. **Reverse the Suffix**:
   - Reverse the portion of the array from \(i + 1\) to the end of the array. This gives the smallest lexicographical arrangement for that segment, ensuring we get the next permutation.
   - **Why?**: Reversing the suffix places the elements in ascending order, providing the smallest possible permutation from this point onward.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Affected Algorithm:
Recursion / Next Permutation

## Additional Information:
Please assign me this issue @pankaj-bind

**Comment by pankaj-bind** [comment]
@o-CodeBlitz-o assigned
