### ISSUE TITLE
Binary Tree construction from preorder and postorder traversals

### ISSUE THREAD

**Issue by DPS-2912** [AlgoGenesis/C#1266]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Binary Tree construction from preorder and postorder traversals

### About:  
Given two arrays:
Preorder Traversal (pre): The order of nodes visited in preorder traversal (Root-Left-Right).
Postorder Traversal (post): The order of nodes visited in postorder traversal (Left-Right-Root).

You need to reconstruct the binary tree that corresponds to these traversals. The challenge lies in the fact that multiple binary trees can yield the same preorder and postorder traversals, but for a given tree structure, there is a unique reconstruction.

The algorithm will effectively reconstruct the binary tree from its preorder and postorder traversals using recursion and careful tracking of subtree sizes.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@DPS-2912 assigned
