### ISSUE TITLE
[NEW ALGORITHM] 

### ISSUE THREAD

**Issue by swayum1004** [AlgoGenesis/C#1268]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
Added Maximum Alternating Subsequence Sum

### About:  
Propose a new algorithm to be added to the repository
This program finds the maximum alternating subsequence sum for a given input array where alternating subsequence sum is difference btw sum of elements at even indices and sum of elements at odd indices within the subsequence

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest-accepted,hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
no update
