### ISSUE TITLE
Stone Paper Scissor Via Recursion 

### ISSUE THREAD

**Issue by MithanshuHedau** [AlgoGenesis/C#1272]
### About:  

The Stone-Paper-Scissors game implemented in C++ is a simple yet engaging interactive program where the user competes against the computer in a hand game that involves three choices: rock (r), paper (p), and scissors (s). The game begins by prompting the user for the number of rounds to play, initializing counters for both the user and the computer's wins. The core gameplay is managed through a recursive function called playGame, which handles each round by allowing the user to input their choice while the computer randomly selects its move. After each round, the winner is determined based on the game rules, and the corresponding win counter is updated. The recursion continues until all rounds are completed, at which point the program checks the win counters and announces the overall winner. This implementation effectively demonstrates the principles of recursion, making it an excellent exercise for understanding game logic and function calls in programming.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [✅ ] Contributor in GSSoC-ext
- [✅ ] Want to work on it

**Comment by MithanshuHedau** [comment]
@pankaj-bind please assign me this issue , for my Contribution in that

**Comment by pankaj-bind** [comment]
assigned
