### ISSUE TITLE
[NEW ALGORITHM] Add Minimum Deletions to Make Array Divisible by Array's GCD

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#1275]
## Description:
The goal of this algorithm is to calculate the minimum number of deletions required to make all elements of an array divisible by the array’s greatest common divisor (GCD). This problem is useful for optimizing data in cases where uniformity (divisibility) is required for all elements, such as in modular arithmetic operations and data processing pipelines.

## The algorithm:

- Calculates the GCD of the entire array.
- Counts the number of elements not divisible by the GCD.
- Outputs the count as the minimum deletions required to achieve full divisibility by the GCD.

## Use Cases:

- Data Validation: Ensuring all data entries in a list conform to a certain factor.
- Optimized Computations: Preparing data for processing pipelines where uniformity (e.g., divisibility) is required.
- Array Operations in Number Theory: Useful in modular arithmetic contexts where uniform divisibility can simplify computations.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
