### ISSUE TITLE
[NEW ALGORITHM] Anagram Check under String Algorithms

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [AlgoGenesis/C#1280]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Anagram Check```  

### About:  
It checks if two strings are anagrams, i.e. if they contain the same characters in the same frequency but in a different order.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
