### ISSUE TITLE
[NEW ALGORITHM] Random Forest Algorithm In Machine Learning

### ISSUE THREAD

**Issue by inkerton** [AlgoGenesis/C#1281]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Random Forest Algorithm ]```  

### About:  
 An ensemble learning method that combines multiple decision trees to improve accuracy and reduce overfitting.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
do not create unnecessary issues

**Comment by inkerton** [comment]
How Is this unnecessary I saw this has a folder named Machine Learning algos which can be implemented In C. I have a minor specialization in ML so these are easier for me . You closed all my issues which type of algos are you looking for I will look them up then @pankaj-bind

**Comment by inkerton** [comment]
I would like to know what was unnecessary in my issues ???!!!!
@pankaj-bind

**Comment by inkerton** [comment]
@MastanSayyad 
This repo has a folder for ML algos and I am best working with those but he closed all issues as unnecessary without any reasoning. Adding algos already present might be unnecessary but this is beyond the limit not.
I know you guys are going strict on top 25 people but this is just straight out rubbish behaviour to close all issue no reasoning , no statement nothing .

I would love a reson atleast. I have No PR in this repo nor any other contributor has the same issue raised.
