### ISSUE TITLE
[NEW ALGORITHM] Gradient Boosting Algorithm in ML

### ISSUE THREAD

**Issue by inkerton** [AlgoGenesis/C#1282]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Gradient Boosting]```  

### About:  
Another ensemble method that builds models sequentially, with each model correcting the errors of the previous one. C implementation requires careful handling of iterative optimization and residual calculation.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
do not create unnecessary issues

**Comment by inkerton** [comment]
@MastanSayyad I need a reasoning for why this unnecessary
