### ISSUE TITLE
[NEW ALGORITHM] CatBoost Algorithm

### ISSUE THREAD

**Issue by inkerton** [AlgoGenesis/C#1284]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[CatBoost ALGORITHM]```  

### About:  
A relatively new gradient boosting framework that handles categorical features effectively. C implementation is possible using the CatBoost library or custom implementations.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
do not create unnecessary issues

**Comment by inkerton** [comment]
@MastanSayyad I need a reasoning for why this unnecessary
