### ISSUE TITLE
[NEW ALGORITHM] Single-Layer Perceptron 

### ISSUE THREAD

**Issue by inkerton** [AlgoGenesis/C#1289]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Single-Layer Perceptron ALGORITHM]```  

### About:  
A Single-Layer Perceptron (SLP) is a fundamental building block of artificial neural networks. It's a simple model that can be used for binary classification tasks.   

How it works:

Input Layer: Receives input data, which can be a set of numerical values.   
Weights and Bias: Each input is multiplied by a weight, and these weighted inputs are summed together. A bias term is added to this sum.   
Activation Function: The sum is passed through an activation function, which introduces non-linearity. A common activation function is the step function.   
Output Layer: The output of the activation function is the final output of the perceptron, typically a binary value (0 or 1).
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
do not create unnecessary issues

**Comment by inkerton** [comment]
@MastanSayyad I need a reasoning for why this unnecessary
