### ISSUE TITLE
[NEW ALGORITHM] DBSCAN (Density-Based Spatial Clustering of Applications with Noise)

### ISSUE THREAD

**Issue by inkerton** [AlgoGenesis/C#1290]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[DBSCAN (Density-Based Spatial Clustering of Applications with Noise)]```  

### About:  
DBSCAN (Density-Based Spatial Clustering of Applications with Noise) is a popular clustering algorithm that groups data points based on their density and proximity to each other. It is particularly effective in discovering clusters of arbitrary shapes and handling noise in the data.

Key Concepts:

Density-Based Clustering: DBSCAN relies on the concept of density to identify clusters. It assumes that clusters are regions of high point density separated by regions of low density.
Core Points: A point is considered a core point if it has at least a minimum number of points (MinPts) within a specified radius (ε).
Border Points: A point is a border point if it is not a core point but is within the ε-neighborhood of a core point.
Noise Points: Points that are neither core nor border points are classified as noise or outliers.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
do not create unnecessary issues
