### ISSUE TITLE
[NEW ALGORITHM] Bagging Algorithm

### ISSUE THREAD

**Issue by inkerton** [AlgoGenesis/C#1291]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Bagging ALGORITHM]```  

### About:  
Bagging, short for Bootstrap Aggregating, is an ensemble learning technique that involves training multiple models on different subsets of the training

 data. These subsets are created by sampling with replacement, meaning that a data point can be selected multiple times in a single subset.   

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
do not create unnecessary issues

**Comment by inkerton** [comment]
@MastanSayyad I need a reasoning for why this unnecessary
