### ISSUE TITLE
[NEW ALGORITHM] Kernel Density Estimation (KDE)

### ISSUE THREAD

**Issue by inkerton** [AlgoGenesis/C#1292]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Kernel Density Estimation (KDE) ALGORITHM]```  

### About:  
A non-parametric method for estimating the probability density function of a random variable.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
do not create unnecessary issues

**Comment by inkerton** [comment]
@MastanSayyad I need a reasoning for why this unnecessary
