### ISSUE TITLE
Add  Order Statistic Trees (Augmented Splay Trees)Algorithm to Splay Trees Documentation

### ISSUE THREAD

**Issue by T-Fathima** [AlgoGenesis/C#1296]
**Title:** Add Section on Order Statistic Trees (Augmented Splay Trees) to Splay Trees Documentation

**Body:**

**Description:**  
I would like to propose adding a new section on **Order Statistic Trees (Augmented Splay Trees)** to the existing Splay Trees documentation. This section will provide insights into how splay trees can be augmented to maintain additional information that allows for efficient order statistics operations.

**Proposed Content:**
1. **Introduction to Order Statistic Trees**
   - Definition and importance in data structures.
  
2. **Augmentation of Splay Trees**
   - How splay trees can be modified to support order statistics.
   - Explanation of maintaining subtree sizes for each node.

3. **Operations Supported**
   - Finding the k-th smallest/largest element.
   - Rank queries.
   - Insertions and deletions in augmented trees.

4. **Complexity Analysis**
   - Time complexity of operations in augmented splay trees.
  
5. **Examples and Use Cases**
   - Practical applications where order statistics are useful.

**Rationale:**  
Including this section will enhance the comprehensiveness of the Splay Trees documentation and provide readers with valuable insights into advanced tree structures and their applications.

I would like to work on it.
Please assign it to me under gssoc-ext and hacktoberfest.

**Comment by pankaj-bind** [comment]
assigned
