### ISSUE TITLE
[NEW ALGORITHM] Bit Manipulation - Count Set Bits

### ISSUE THREAD

**Issue by SumaLatha2023** [AlgoGenesis/C#1299]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Count the Number of Set Bits]```  

### About:  
This algorithm, also known as Hamming Weight or Population Count, counts the number of 1-bits in the binary representation of a given integer. 
Bitwise operations are used to efficiently count the set bits in O(number of set bits) time complexity, making it an effective solution for applications that require frequent bit-level manipulation, such as cryptography, network address manipulation, and compression.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by SumaLatha2023** [comment]
Kindly assign me this issue so that I can start working on it ..

**Comment by pankaj-bind** [comment]
assigned
