### ISSUE TITLE
Updating sorting algorithms

### ISSUE THREAD

**Issue by sumankr15** [AlgoGenesis/C#13]
I would recommend to broaden the scope of sorting algos by adding all the standard sorting algos , like selection sort, merge sort, insertion sort , quick sort  , heap sort , and many more.
I will make sure to test it on Linux (Ubuntu) os.
I am really willing to contribute to this project.
Looking forward for your approval and assignment so I could start working on it.
(Please add gssoc-ext 24 and hacktoberfest label) -(if assigned)

**Comment by pankaj-bind** [comment]
@sumankr15 Suit up, it’s code-crunching time!

**Comment by simmi-verma** [comment]
I am participating in gssoc-ext for the first time. Could you please assign me to this task?

**Comment by sumankr15** [comment]
@simmi-verma this task was assigned to me by the project-mentor because I raised the issue. As you are new contributor you could raise issue about adding algorithms which are still left .(check out code ) 
Wishing you Good Luck.

**Comment by sumankr15** [comment]
@pankaj-bind  i have completed adding sorting algorithms . Please have a look at my pull request. 
named:- (sorting algorithms added #78)
