### ISSUE TITLE
[NEW ALGORITHM] Addition of Colussi Algorithm under String Algorithms

### ISSUE THREAD

**Issue by pratheekv39** [AlgoGenesis/C#1308]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Colussi Algorithm

### About:  
Propose a new algorithm to be added to the repository
Colussi Algorithm is a string algorithm which partitions the set of pattern positions into two disjoint subsets; the positions in the first set are scanned from left to right and when no mismatch occurs the positions of the second subset are scanned from right to left;
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it
@pankaj-bind please assign this ASAP , I will immediately work on it

**Comment by pankaj-bind** [comment]
assigned
