### ISSUE TITLE
[NEW ALGORITHM] Buchberger's Algorithm

### ISSUE THREAD

**Issue by AE-Hertz** [AlgoGenesis/C#1309]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Buchberger's Algorithm```  

### About:  
Propose a new algorithm to be added to the repository
Used in computational algebra to find a Gröbner basis for a system of polynomial equations, enabling the solving of polynomial systems and ideal membership problems.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by sahare-mayur-0071** [comment]
Hello @sanjay-kv I wont to work on this issue. Assign me this issue

**Comment by pankaj-bind** [comment]
assigned
