### ISSUE TITLE
[NEW ALGORITHM] Partition Sort

### ISSUE THREAD

**Issue by karthikyandrapu** [AlgoGenesis/C#1311]
### Name: Partition Sort
```Partition Sort```  

### About:
1. The program implements a **Partition Sort** algorithm. This is a variation of the Quick Sort algorithm that recursively sorts an array by selecting a pivot element and dividing the array into two parts around this pivot. Elements less than or equal to the pivot are on one side, while elements greater than the pivot are on the other.
2. **Partition Function**: The `partition` function selects the first element as the pivot and rearranges the array elements around it.
3. **Recursive Sorting**: The `partitionSort` function is recursively called on the divided segments, continuing to sort until the array is fully ordered.
4. **Interactive Display**: The program generates a random array, displays it, applies the Partition Sort algorithm, and then displays the sorted result.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
