### ISSUE TITLE
[NEW ALGORITHM] Viterbi Algorithm for Hidden Markov Models

### ISSUE THREAD

**Issue by amanver45** [AlgoGenesis/C#1313]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Viterbi Algorithm for Hidden Markov Models]```  

### About:  
 Use the Viterbi Algorithm to decode the most probable sequence of hidden states in a Hidden Markov Model (HMM). This algorithm is useful in applications like speech recognition and bioinformatics.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by amanver45** [comment]
@pankaj-bind can you assign me this issue

**Comment by pankaj-bind** [comment]
assigned
