### ISSUE TITLE
[NEW ALGORITHM] FCFS CPU Scheduling Algorithm 

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1314]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
FIRST COME FIRST SERVE CPU SCHEDULING ALGORITHM

### About:  
The First-Come, First-Served (FCFS) algorithm is a simple, non-preemptive scheduling method used in operating systems. It processes tasks in the exact order they arrive, without priority. Once a task starts executing, it runs until completion.The C program implements First-Come, First-Served (FCFS) scheduling for processes. It defines a Process structure to store details like burst time, arrival time, start time, and completion time. The program sorts processes based on their arrival times using qsort(), ensuring they are executed in the correct order. After scheduling, it calculates turnaround time and waiting time for each process, printing the results in a formatted output.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
