### ISSUE TITLE
[NEW ALGORITHM] Knuth-Morris-Pratt (KMP)

### ISSUE THREAD

**Issue by byteom** [AlgoGenesis/C#1320]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Knuth-Morris-Pratt (KMP)]```  

### About:  
Propose a new algorithm to be added to the repository

Efficient Pattern Matching: The main goal of KMP is to search for a substring (pattern) in a text efficiently without revisiting characters in the text, which minimizes the number of comparisons.

Applications in Search Engines and Text Editors: The KMP algorithm is often used in applications like search engines, text editors, and computational biology to quickly locate substrings within large bodies of text.

DNA Sequence Matching: KMP is helpful in bioinformatics for sequence matching and DNA pattern analysis, where it finds specific genetic patterns within large genome sequences.

Network Security: In cybersecurity, KMP can be used in intrusion detection systems to search for known attack signatures in network traffic data.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Contributor in Hacktoberfest 
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
