### ISSUE TITLE
[NEW ALGORITHM] : Evaluation of Postfix expression 

### ISSUE THREAD

**Issue by VanshGarg06** [AlgoGenesis/C#1332]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Evaluating the postfix Expression entered by taking user input

### About:  
The System uses postfix or prefix expression for and computational evaluation but it is difficult to be interpreted by human easily. Postfix Expression evaluation is important to verify the results got from the system. Postfix and Prefix expression are evaluated and computed using Stack Data structure. 

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

Please assign this issue to me @pankaj-bind  as soon as possible so that i can raise a new issue for other algorithm.

**Comment by Tanyajain2006** [comment]
@VanshGarg06 @pankaj-bind I would like to work on it.

**Comment by VanshGarg06** [comment]
Hey Pankaj Kumar Bind, this problem is not solved and raised the issue for
the same even checked the whole repository unable to find the same problem
solved by any other person raising the same again do assign it to me as i
raised it first.
