### ISSUE TITLE
[NEW ALGORITHM] Graph Coloring

### ISSUE THREAD

**Issue by yashksaini-coder** [AlgoGenesis/C#1335]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Graph coloring]```  

### About:  
Assign colors to the vertices of a graph such that no two adjacent vertices share the same color. The goal is often to minimize the number of colors used.
Applications: Scheduling problems, register allocation in compilers, and frequency assignment.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by yashksaini-coder** [comment]
@pankaj-bind can you assign me this issue I would like to work on it.

**Comment by yashksaini-coder** [comment]
@pankaj-bind bro can I directly raise a PR, for this issue ??

**Comment by pankaj-bind** [comment]
assigned

**Comment by yashksaini-coder** [comment]
@pankaj-bind raised the PR #1376 for the issue fix
