### ISSUE TITLE
[NEW ALGORITHM] Disjoint Set (Union-Find)

### ISSUE THREAD

**Issue by byteom** [AlgoGenesis/C#1336]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Disjoint Set (Union-Find)]```  

### About:  
Propose a new algorithm to be added to the repository

Propose a new algorithm to be added to the repository
Efficient Group Management: It is used to keep track of elements that are split into different groups or connected components, making it easy to find and merge groups without duplicating elements.

Detecting Cycles in Graphs: Disjoint Set is essential in graph algorithms, especially in detecting cycles within an undirected graph. If two vertices belong to the same set and an edge is formed between them, it indicates a cycle.

Kruskal’s Minimum Spanning Tree (MST): Union-Find is crucial in Kruskal’s algorithm, where it helps to ensure that adding an edge doesn’t form a cycle, allowing the algorithm to construct the MST efficiently.

Dynamic Connectivity: In networks (social networks, computer networks, etc.), Union-Find can help determine whether two nodes are in the same connected component, enabling dynamic connectivity operations.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Contributer in Hacktoberfest 
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
