### ISSUE TITLE
[NEW ALGORITHM] Floyd-Warshall Algorithm

### ISSUE THREAD

**Issue by sudhajyothi** [AlgoGenesis/C#134]
## Description:
Floyd-Warshall Algorithm

The Floyd-Warshall algorithm is a classic algorithm in computer science for finding the shortest paths between all pairs of vertices in a weighted graph. It can handle both directed and undirected graphs and is capable of managing negative weight edges (but not negative weight cycles).

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Use Cases: The algorithm is used in network routing, pathfinding in games, and finding transitive closure in graph theory.

**Comment by Chaitra-kshirsagar** [comment]
I would like to work on it, please consider assigning it to me
