### ISSUE TITLE
[NEW ALGORITHM] Clone a linked list with Random connection 

### ISSUE THREAD

**Issue by SKG24** [AlgoGenesis/C#1344]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Clone a linked list with Random connection 
```[NEW ALGORITHM]```  

### About:  
Given a linked list where each node has a next pointer to the next node in the list and a random pointer that can point to any node in the list (or be NULL), create a deep copy (clone) of the list. The cloned list should have nodes with the same values and maintain the same next and random pointers structure as the original list.

**Explanation of Solution**
We will use an unordered_map to store the mapping from each node in the original list to its corresponding node in the cloned list. This will help us efficiently set up the next and random pointers for the nodes in the copied list.

- Mapping Nodes: In the first traversal, we create a new node for each node in the original list and map it to the original node in the unordered_map.
- Setting Pointers: In the second traversal, we set the next and random pointers for each cloned node. Using the unordered_map, we can efficiently look up and set these pointers to ensure the cloned list has the same structure as the original.
- Returning the Cloned Head: Finally, we return the cloned node that corresponds to the original list’s head.

---

### Labels:  
new algorithm, gssoc-ext, hackoctoberfest, level1

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
