### ISSUE TITLE
Increasing Triplet Subsequence

### ISSUE THREAD

**Issue by vivek-anand-singh** [AlgoGenesis/C#1348]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Increasing Triplet Subsequence```  

### About:  
Given an integer array `nums`, return `true` if there exists a triple of indices `(i, j, k)` such that `i < j < k` and `nums[i] < nums[j] < nums[k]`. If no such indices exist, return `false`.

**Example 1**:
- **Input**: `nums = [1,2,3,4,5]`
- **Output**: `true`
- **Explanation**: Any triplet where `i < j < k` is valid.

**Example 2**:
- **Input**: `nums = [5,4,3,2,1]`
- **Output**: `false`
- **Explanation**: No triplet exists.

**Example 3**:
- **Input**: `nums = [2,1,5,0,4,6]`
- **Output**: `true`
- **Explanation**: The triplet `(3, 4, 5)` is valid because `nums[3] == 0 < nums[4] == 4 < nums[5] == 6`.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by vivek-anand-singh** [comment]
@pankaj-bind I have searched the repository and couldn't find any file containing the `Increasing Triplet Subsequence` problem, so it doesn’t appear to be a duplicate. 

I would like to work on this issue if it’s approved. Please let me know if there are any additional details or guidelines you'd like me to follow. Thank you!

![image](https://github.com/user-attachments/assets/9599f2bf-4460-4585-abdb-300601ea6709)

**Comment by vivek-anand-singh** [comment]
Can you please assign this issue to me ? I would like to work on this

@pankaj-bind

**Comment by pankaj-bind** [comment]
assigned
