### ISSUE TITLE
[NEW ALGORITHM] addition of Page Replacement algorithm

### ISSUE THREAD

**Issue by apoorvasj** [AlgoGenesis/C#1349]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```FIFO Algorithm```  

### About:  
The FIFO Algorithm (First In First Out) is the simplest page replacement algorithm where the page that has resided in memory for the longest amount of time is replaced.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ✔️] Contributor in GSSoC-ext
- [✔️ ] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me this issue
