### ISSUE TITLE
Infix to Postfix Algorithms

### ISSUE THREAD

**Issue by Salini-sat** [AlgoGenesis/C#135]
## Description:
Infix to postfix conversion and evaluation using stack 
It comes under applications of stack algorithm

## Checklist:
- I Contributor in GSSoC-ext
- I Want to work on it

## Additional Information:
Postfix notation, also known as Reverse Polish Notation (RPN), is used to make it easier for computers to evaluate expressions. Here are some advantages of postfix notation

**Comment by Salini-sat** [comment]
@pankaj-bind I want to work on it. Please assign me this

**Comment by shuvojitss** [comment]
I am a Contributor in GSSoC-ext. Please assign it to me

**Comment by AakritiSaxena32** [comment]
I would love to work on the Infix to Postfix Conversion task. I have experience in C and data structures like stacks, and I believe I can complete this task efficiently. Please assign it to me.

**Comment by pankaj-bind** [comment]
@Salini-sat you can start
