### ISSUE TITLE
DFS via Recursion

### ISSUE THREAD

**Issue by souvikpramanikgit** [AlgoGenesis/C#1354]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```DFS via Recursion```  

### About:  
Propose a new algorithm to be added to the repository

**Problem** : Traverse or search for a node in a tree or graph.
**Recursive Solution** : Visit each node and recursively explore its children or neighboring nodes.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by tannuiscoding** [comment]
Hey, please assign me this issue. I know how to do it. I'll raise a PR by evening.

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
