### ISSUE TITLE
[NEW ALGORITHM] Johnson’s algorithm for All-pairs shortest paths

### ISSUE THREAD

**Issue by Deepika14145** [AlgoGenesis/C#1356]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Johnson’s Algorithm for All-Pairs Shortest Paths

### About:  
Propose a new algorithm to be added to the repository:
 Johnson’s Algorithm is used to find the shortest paths between all pairs of nodes in a weighted graph, which may include negative weights but no negative weight cycles. It is particularly effective when dealing with sparse graphs.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

Please assign me this issue @pankaj-bind

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
