### ISSUE TITLE
[NEW ALGORITHM] Pollard’s Rho Algorithm for Prime Factorization

### ISSUE THREAD

**Issue by Deepika14145** [AlgoGenesis/C#1358]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Pollard’s Rho Algorithm for Prime Factorization

### About:  
Propose a new algorithm to be added to the repository:
Pollard's Rho Algorithm is an efficient probabilistic algorithm for finding non-trivial factors of a composite number, especially useful for large numbers. It is a Monte Carlo algorithm, which means it has a chance of failing or taking a long time but generally performs very well in practice.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

Please assign me this issue @pankaj-bind

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
