### ISSUE TITLE
Add Traversal Algorithms and Shortest Path Algorithms for Graph

### ISSUE THREAD

**Issue by souvikpramanikgit** [AlgoGenesis/C#1366]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```
   1. Traversal Algorithms
   2. Shortest Path Algorithms
```  

### About:  
Propose a new algorithm to be added to the repository

**Traversal Algorithms**

1. Depth-First Search (DFS): Explores as far as possible along each branch before backtracking. Typically implemented recursively or using a stack.
2. Breadth-First Search (BFS): Explores all vertices at the present depth before moving on to vertices at the next depth level. Typically implemented using a queue.

**Shortest Path Algorithms**

1. Dijkstra's Algorithm: Finds the shortest path from a source vertex to all other vertices in a graph with non-negative edge weights.
Bellman-Ford Algorithm: Finds the shortest path from a source vertex to all other vertices, and works with graphs that may have negative weight edges.
2. Floyd-Warshall Algorithm: Solves the all-pairs shortest path problem for graphs with both positive and negative edge weights (without negative cycles).
3. A (A-star) Algorithm*: Finds the shortest path in graphs with heuristic-based optimizations, often used in pathfinding problems (e.g., game development).
4. Johnson's Algorithm: Solves the all-pairs shortest path problem for sparse graphs using a combination of Bellman-Ford and Dijkstra's algorithms.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me this issue

**Comment by souvikpramanikgit** [comment]
but it is not available in the graph folder.
