### ISSUE TITLE
[NEW ALGORITHM]: Palindrome String /Reversed String

### ISSUE THREAD

**Issue by VanshGarg06** [AlgoGenesis/C#1368]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
The string entered by the user when reversed and if reversed string is equal to the original string then it is said to be a palindromic string and even show the reversed string(collection of character alphabet).

### About:  
The string is sometimes needs to be reversed specifically in case of solving the palindromic string problem in which when the string is reversed and the string is compared to the original string.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me this issue

**Comment by pankaj-bind** [comment]
Do not create multiple issues

**Comment by VanshGarg06** [comment]
Really sorry for creating multiple issues but I am raising new issue
because it's really time taking that I raise a issue and then next day you
will assigned to me and some times  you closed the issue even without
consideration that's why I had already written that I am raising multiple
issues do assign it to me.
