### ISSUE TITLE
[NEW ALGORITHM] : Shortest Remaining Time First Algorithm

### ISSUE THREAD

**Issue by VanshGarg06** [AlgoGenesis/C#1370]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Shortest Remaining Time First Algorithm for job scheduling

### About:  
Job scheduling is one of the important method of CPU by the scheduler as processes keep coming into the system and it needs to choose the process that needs to be executed first. From different Process Scheduling Algorithms, One of the famous algorithm is Shortest Remaining Time First Algorithm which is the preemptive version of Shortest Job First Algorithm. In this algorithm, the average waiting time and average turn around time is also reduced in comparison to other algorithms. This algorithm chooses process with less burst time first.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by gurnoorkaur-13** [comment]
please assign me this issue

**Comment by pankaj-bind** [comment]
Do not create multiple issues

**Comment by VanshGarg06** [comment]
Do let me know that should I raise the to this repository or not because
you are just closing all my issues not even taking them into consideration.
Even after following your rules.
