### ISSUE TITLE
Site update: Add Contributors carousel

### ISSUE THREAD

**Issue by yashksaini-coder** [AlgoGenesis/C#1387]
Adding different Repositories of the AlgoGenesis to be showcased on the website as seen below

![image](https://github.com/user-attachments/assets/611d5c46-add3-4935-9dbc-95a1d2427e34)

My approach is to add postcss with card-components to add other repos to be showcased in the page

@pankaj-bind can you assign me this issue as gssoc & hacktoberfest contributor

**Comment by pankaj-bind** [comment]
assigned
