### ISSUE TITLE
[NEW ALGORITHM] BASIC PROGRAMMING FOR BEGINNERS WHICH HELPS TO UNDERSTAND ABOUT C LANGUAGE

### ISSUE THREAD

**Issue by AbhinaySngh** [AlgoGenesis/C#139]
## Description:
Basic topics for beginners 

## Checklist:
- [ X] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by AbhinaySngh** [comment]
@pankaj-bind Please assign me this issue.

**Comment by benishasharma** [comment]
@pankaj-bind Hi! I’d love to contribute to this issue by providing clear and beginner-friendly C programming concepts and examples. Please assign this task to me, and I'll ensure it's done effectively!
