### ISSUE TITLE
[NEW ALGORITHM] Add Mo's Algorithm for Efficient Range Queries

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#1392]
**Title:** Add Mo's Algorithm for Efficient Range Queries

**Description:**
Mo's Algorithm is an offline algorithm used to optimize the processing of multiple range queries on a static array. By using a clever block decomposition approach, it minimizes redundant computations for overlapping range queries, making it ideal for large datasets where querying the entire array repeatedly would be inefficient.

This feature will allow users to perform complex range queries such as sum, frequency, or XOR operations in significantly reduced time, especially for arrays where updates are rare or non-existent.

**Use Cases:**
- Efficiently answering multiple range sum queries.
- Calculating the frequency of elements within specified ranges.
- Optimizing XOR queries over multiple overlapping ranges in an array.

**Proposed Solution:**
1. **Block Decomposition:** Divide the array into blocks of √N size.
2. **Query Sorting:** Sort the queries based on block and ending index, which allows minimizing redundant computations.
3. **Query Processing:** Process each query by only updating necessary blocks, thus achieving optimal time complexity.

**Complexity**:
- **Time Complexity**: O((N + Q) * √N), where \( N \) is the array length and \( Q \) is the number of queries.
- **Space Complexity**: O(N), for storing array blocks and additional data structures.

This algorithm will be beneficial for users working with large datasets and is frequently applied in competitive programming for its efficient handling of static arrays.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by ayushdubey570** [comment]
hey @divyalakshmi0 please assign me this issue.

**Comment by ayushdubey570** [comment]
hey @mehul-m-prajapati  please asign me this issue

**Comment by ayushdubey570** [comment]
> sure @ayushdubey570 , please make me an owner for this repo

I must have mistaken you as mentor for this repo. sorry for tagging you!!

**Comment by pankaj-bind** [comment]
@divyalakshmi0 assigned
