### ISSUE TITLE
[NEW ALGORITHM] : Swim in Rising Water (GRAPHS)

### ISSUE THREAD

**Issue by ananydev** [AlgoGenesis/C#1396]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:   Swim in Rising Water (GRAPHS)

```[NEW ALGORITHM]```  
### About:  
Propose a new algorithm to be added to the repository

Step 1: Initialize the Min-Heap and Visited Set
Create a min-heap (priority queue) where each entry is a tuple of the form (current_time, x, y), representing the minimum time current_time needed to reach cell (x, y).
Insert the starting cell (0, 0) with its elevation value as the initial current_time.
Initialize a set or 2D list to mark visited cells to avoid re-processing them.

Step 2: Define Directional Movement
Define the four possible moves to neighboring cells:
Up: (-1, 0)
Down: (1, 0)
Left: (0, -1)
Right: (0, 1)

Step 3: Dijkstra-like Search (Using Min-Heap)
While the min-heap is not empty:

Extract the cell with the minimum time (i.e., (current_time, x, y)) from the min-heap.
If this cell is (n-1, n-1), we have reached the bottom-right corner, and the current_time at this cell is the answer.
If the cell (x, y) is already visited, skip it to avoid redundant processing.
Mark the cell (x, y) as visited.
For each of the four possible directions (up, down, left, right):

Calculate the new cell coordinates (new_x, new_y).
Check if the new coordinates are within the grid boundaries and have not been visited.
Compute the new_time as the maximum of current_time and grid[new_x][new_y]. This ensures that the water level is high enough to swim into the next cell.
Push (new_time, new_x, new_y) into the min-heap if new_time is valid.

Step 4: Return the Result
Once we reach the bottom-right corner, the current_time value at this cell represents the minimum time required to swim from the top-left to the bottom-right corner. This is our result.

: 

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by ananydev** [comment]
hello !! pls update

**Comment by ananydev** [comment]
kindly assign me

**Comment by pankaj-bind** [comment]
assigned
