### ISSUE TITLE
[NEW ALGORITHM]  Bentley-Ottmann Algorithm for Line Segment Intersection

### ISSUE THREAD

**Issue by IkkiOcean** [AlgoGenesis/C#1397]
### Name:  
Bentley-Ottmann Algorithm for Line Segment Intersection 

### About:  

the Bentley-Ottmann algorithm to efficiently detect all intersection points between a set of line segments in a 2D plane. This algorithm is particularly useful for handling multiple line segments and finding intersection points in O((n + k) log n) time complexity, where n is the number of line segments and k is the number of intersections.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@IkkiOcean assigned
