### ISSUE TITLE
[NEW ALGORITHM]  Van Emde Boas Tree

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [AlgoGenesis/C#1399]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
 Van Emde Boas Tree

### About:  
A specialized tree structure that allows for extremely fast insertion, deletion, and membership testing. It operates close to constant time and is often useful when working with a universe of integers

---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues
