### ISSUE TITLE
[NEW ALGORITHM] Cantor's Pairing Function

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [AlgoGenesis/C#1402]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Cantor's Pairing Function  

### About:  
This function uniquely encodes two non-negative integers into a single non-negative integer, allowing for a simple and invertible way of pairing numbers. It’s often used in mathematical applications or data compression.

---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues
