### ISSUE TITLE
[NEW ALGORITHM] Numerical Integration with Adaptive Quadrature

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [AlgoGenesis/C#1403]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Numerical Integration with Adaptive Quadrature  

### About:  
This algorithm dynamically adjusts the interval size based on error estimates, making it suitable for functions with high variability. Adaptive quadrature is rarely implemented due to its complex error management but is highly efficient for precise integration.

---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues
