### ISSUE TITLE
[NEW ALGORITHM] : Detect Cycle and Remove cycle in a Linked List

### ISSUE THREAD

**Issue by VanshGarg06** [AlgoGenesis/C#1404]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Detect the cycle and Remove the cycle in a Linked List

### About:  
In a linked List when any node is not pointing to NULL next and pointing to any other previous node of list then there is a cycle in the list and to remove the same we need to find the start of the cycle and then the node which is pointing to any other previous node and make its next pointer to null.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

@pankaj-bind Please assign this issue to me under hacktoberfest and gssoc-ext with necessary labels assigned and assign it to me @VanshGarg06 as soon as possible.

**Comment by pankaj-bind** [comment]
Do not create multiple issues
