### ISSUE TITLE
Layered Permutation and Mixing Hash (LPMH) Algorithm

### ISSUE THREAD

**Issue by sivanandhinisellamuthu** [AlgoGenesis/C#1412]
# Bucket Hashing: Layered Permutation and Mixing Hash (LPMH)

## Overview
**Layered Permutation and Mixing Hash**The Layered Permutation and Mixing Hash (LPMH) algorithm is designed to offer enhanced security and high-speed hashing with increased resistance to collisions, targeting applications in cryptography and data integrity.
 It employs a combination of permutation and mixing techniques across multiple layers to create a robust hash output that is resistant to various forms of attacks, including collision attacks. This algorithm is particularly useful in applications where data integrity and confidentiality are critical.

## Key Features
- **Enhanced Collision Handling**: Minimizes the likelihood of hash collisions, making it more secure for sensitive applications.
- **Speed Optimized for Modern Hardware**:  Compatible with multi-core processing, enabling parallel hashing and GPU compatibility.
- **Parallelizable Design**: Efficient for parallel processing, optimizing performance on modern CPUs and GPUs.
- **High Avalanche Effect**: Small changes in input produce drastically different outputs.

## Why LPMH?
The Layered Permutation and Mixing Hash (LPMH) algorithm is essential for enhancing data integrity, security, and efficiency across various applications. One of its key features is improved collision resistance, significantly reducing the likelihood that different inputs will produce the same hash output, which is crucial for databases and cryptographic applications. LPMH also achieves a more uniform distribution of hash values through its layered permutations, preventing clustering and ensuring optimal performance in data retrieval systems. 

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by sivanandhinisellamuthu** [comment]
Please assign me this issue; I will implement the code in Java.

**Comment by sivanandhinisellamuthu** [comment]
Hello mentors and GSSoC team! 👋

I’ve completed the implementation of the **Layered Permutation and Mixing Hash (LPMH)** algorithm in Java as discussed. You can view the code here: https://github.com/sivanandhinisellamuthu/LPMH-Algorithm/tree/main

Please review it and let me know if any modifications or improvements are required. Thank you!

**Comment by divyalakshmi0** [comment]
@sivanandhinisellamuthu you have implement this in C language!!

**Comment by sivanandhinisellamuthu** [comment]
Hi @GSSoC-EXTENDED-Team,

I have completed the implementation of the Layered Permutation and Mixing Hash (LPMH) algorithm in C, as requested. The code is ready for review, and I would appreciate any feedback or suggestions for improvement.

Here’s the link to my repository with the C implementation: https://github.com/sivanandhinisellamuthu/LPMH-Algorithm/tree/main

Thank you!

**Comment by pankaj-bind** [comment]
@sivanandhinisellamuthu raise a PR if you have completed

**Comment by pankaj-bind** [comment]
no update
