### ISSUE TITLE
[NEW ALGORITHM]  Deadlock Detection using Resource Allocation Graph

### ISSUE THREAD

**Issue by o0PHOENIX0o** [AlgoGenesis/C#1417]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Deadlock Detection using Resource Allocation Graph

### About:  
Deadlock detection in computer systems can be efficiently managed using a Resource Allocation Graph (RAG). In RAG, nodes represent processes and resources, with directed edges indicating the request and allocation of resources. If a process requests a resource, a directed edge is drawn from the process node to the resource node; if the resource is allocated, the edge goes from the resource to the process. Deadlocks occur when there's a cycle in this graph, meaning a circular dependency among processes and resources, which prevents processes from proceeding. By regularly analyzing the RAG for cycles, systems can detect deadlocks

---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---
### Additional Information
Please assign me this issue @pankaj-bind

**Comment by pankaj-bind** [comment]
assigned
