### ISSUE TITLE
[NEW ALGORITHM] Finding Duplicates in an 1-D Array

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [AlgoGenesis/C#1418]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Finding Duplicates in an 1-D Array```  

### About:  
Finding Duplicfates in a 1-D Array.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues
