### ISSUE TITLE
[UPDATE ALGORITHM] 

### ISSUE THREAD

**Issue by PremaDongare** [AlgoGenesis/C#142]
## Description:
I want to make some changes in Bellmanford algorithm.

## Checklist:
- [ ] Want to work on it

## Affected Algorithm:
Bellmanford

**Comment by AHSANATIQ98** [comment]
can you assign this to me?

**Comment by shuvojitss** [comment]
I am a Contributor in GSSoC-ext. Please assign it to me

**Comment by PremaDongare** [comment]
I want to make some changes in le logic of code
