### ISSUE TITLE
[NEW ALGORITHM] Add Artificial Neural Network(ANN) in Machine Learning

### ISSUE THREAD

**Issue by isnehamondal** [AlgoGenesis/C#1425]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Add Artificial Neural Network(ANN) in Machine Learning section

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- Contributor in GSSoC-ext
- Want to work on it

**Comment by isnehamondal** [comment]
Hello @pankaj-bind sir,

This is the previous issue that I created to work on this but due to technical issue I couldn’t do it, so I myself closed it and created a new one #1430 
But again due to some problem I couldn’t do that.

I have actually completed the task and was about to open a pull request but due to some technical problems, I couldn’t communicate to you or send a pull request. I apologise for the inconvenience. Can you please open the issue again? I will be grateful to you. Thanks!

**Comment by manastiwari99** [comment]
I would like to work please assign it to me

**Comment by pankaj-bind** [comment]
@isnehamondal assigned
