### ISSUE TITLE
[NEW ALGORITHM] -N-Queens Problem with Symmetry Breaking

### ISSUE THREAD

**Issue by sambedan1** [AlgoGenesis/C#1427]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
N-Queens Problem with Symmetry Breaking

### About:  
Propose a new algorithm to be added to the repository
The goal is to place N queens on an N x N chessboard such that no two queens threaten each other. The symmetry breaking technique involves placing the first queen in the first half of the board only, effectively reducing the number of solutions we need to explore
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
