### ISSUE TITLE
[NEW ALGORITHM] The Peak Element Finding Algorithm.(1D array Concept)

### ISSUE THREAD

**Issue by sambedan1** [AlgoGenesis/C#1428]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
The Peak Element Finding Algorithm.(1D array Concept)

### About:  
Propose a new algorithm to be added to the repository
A peak element in an array is an element that is greater than or equal to its neighbors. The uniqueness of this algorithm lies in its efficient divide-and-conquer approach, which allows you to find a peak in O(log n) time complexity.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by thmshreyas** [comment]
Hi @sambedan1 Can i work on this issue. I have a solution that you may  like .

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
