### ISSUE TITLE
[NEW ALGORITHM] Add ANN(artificial neural network)

### ISSUE THREAD

**Issue by isnehamondal** [AlgoGenesis/C#1430]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Add artificial neural network in machine learning section

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- Contributor in GSSoC-ext
- Want to work on it

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
no update

**Comment by isnehamondal** [comment]
> no update


Hello @pankaj-bind sir, 
I have actually completed the task and was about to open a pull request but due to some technical problems, I couldn’t communicate to you or send a pull request. I apologise for the inconvenience. Can you please open this issue again?
