### ISSUE TITLE
[NEW ALGORITHM] Longest Consecutive Sequence

### ISSUE THREAD

**Issue by vivek-anand-singh** [AlgoGenesis/C#1432]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Longest Consecutive Sequence```  

### About:  
Given an unsorted array of integers nums, Return the length of the longest consecutive elements sequence.

### Example:

Example 1:

Input: `nums = [100, 4, 200, 1, 3, 2]`  
Output: `4`  
Explanation: The longest consecutive elements sequence is `[1, 2, 3, 4]`. Therefore, its length is `4`.

Example 2:

Input: `nums = [0, 3, 7, 2, 5, 8, 4, 6, 0, 1]`  
Output: `9`  
Explanation: The longest consecutive elements sequence is `[0, 1, 2, 3, 4, 5, 6, 7, 8]`. Therefore, its length is `9`.

### Constraints:

- `0 <= nums.length <= 10^5`
- `-10^9 <= nums[i] <= 10^9`

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by Indrajeety993648** [comment]
@pankaj-bind I would like to work on this issue could you please assign this issue to me
