### ISSUE TITLE
[NEW ALGORITHM] Smith-Waterman Algorithm under String Algorithms

### ISSUE THREAD

**Issue by pratheekv39** [AlgoGenesis/C#1436]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
Smith-Waterman Algorithm
### About:  
Propose a new algorithm to be added to the repository
Addition of Smith-Waterman Algorithm under String Algorithms
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it
@pankaj-bind Kindly , assign it to me ASAP . I will start working on it .

**Comment by pankaj-bind** [comment]
@pratheekv39 assigned
