### ISSUE TITLE
[NEW ALGORITHM] RC4 (Rivest Cipher 4)

### ISSUE THREAD

**Issue by ananyag309** [AlgoGenesis/C#1437]
---

### Name:  
RC4 (Rivest Cipher 4)

### About:  
 A stream cipher that encrypts individual bits or bytes of data.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
