### ISSUE TITLE
[NEW ALGORITHM] :Hopcroft-Karp Algorithm for Maximum Matching in Bipartite Graphs,

### ISSUE THREAD

**Issue by Richajaishwal0** [AlgoGenesis/C#1450]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Implement Hopcroft-Karp Algorithm for Maximum Matching in Bipartite Graphs```  

### About:  
Add an implementation of the Hopcroft-Karp Algorithm, an efficient method for finding maximum matching in bipartite graphs. This algorithm optimizes matching by using breadth-first and depth-first searches to layer the graph and augment multiple paths simultaneously. It’s especially useful in large-scale bipartite matching scenarios, like job assignments and resource allocation.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me
