### ISSUE TITLE
[NEW ALGORITHM] Regular Expression Matching

### ISSUE THREAD

**Issue by Susmita0202** [AlgoGenesis/C#1451]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]Regular Expression Matching```  

### About:  
Propose a new algorithm to be added to the repository
Given an input string s and a pattern p, implement regular expression matching with support for '.' and '*' where:

'.' Matches any single character.​​​​
'*' Matches zero or more of the preceding element.
The matching should cover the entire input string (not partial).

 
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [Yes ] Contributor in GSSoC-ext
- [ Yes] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me

**Comment by Susmita0202** [comment]
Please assign me @pankaj-bind
