### ISSUE TITLE
[NEW ALGORITHM] BFS (Breadth-First Search) Traversal in a Binary Tree

### ISSUE THREAD

**Issue by itsHarsh2** [AlgoGenesis/C#1455]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
 BFS (Breadth-First Search) Traversal in a Binary Tree  

### About:  

BFS is particularly useful in applications requiring level-order processing, such as finding the shortest path in unweighted graphs or searching through tree structures. Its efficiency is rooted in its O(n) time complexity, where n is the number of nodes, as each node is processed exactly once. The space complexity is O(w), where w is the maximum width of the tree, corresponding to the maximum number of nodes at any level. By effectively leveraging BFS, systems can maintain organized and efficient data processing across hierarchical structures.

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Roopun** [comment]
I would like to work on it

**Comment by itsHarsh2** [comment]
Bro find your own issue.
