### ISSUE TITLE
[NEW ALGORITHM] Segregate Even and Odd (numeric) node | Linked List

### ISSUE THREAD

**Issue by SKG24** [AlgoGenesis/C#1458]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Segregate Even and Odd node
```[NEW ALGORITHM]```  

### About:  
In this question, we are supposed to segregate the even numbered nodes from odd numbered nodes in such a way that odd numbered nodes are before even nodes. 

**Example**
Input: 1->2->3->4->5->6
Output: 1->3->5->2->4->6
---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@SKG24 assigned

**Comment by pankaj-bind** [comment]
@Riddhi12349

**Comment by SKG24** [comment]
please assign it back to me. Got busy with my course work. I am done with algorithm just have to make PR. I will do this by evening

**Comment by SKG24** [comment]
can i create pr or not??

**Comment by Riddhi12349** [comment]
Pr created , Please review urgently
