### ISSUE TITLE
[NEW ALGORITHM] Implement Robin Hood Hashing in Hashmap for Optimized Probe Length Management

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#1462]
**Title**: Implement Robin Hood Hashing in Hashmap for Optimized Probe Length Management

**Description**:
Robin Hood Hashing is a unique technique within open addressing that improves the performance of hash tables by balancing the load factor and reducing clustering. This hashing method rearranges elements based on their probe distance: if a new element encounters an existing one with a shorter probe length, they swap positions. This approach ensures that "poorer" elements (those with longer probe distances) get closer to their ideal positions.

### Key Points:
- **Redistribution Logic**: Ensures that elements with the longest probe distances move towards their ideal position by swapping with others.
- **Load Balancing**: Reduces clustering, helping maintain efficient access times even under high load factors.
- **Efficiency**: Optimizes average search time, especially under conditions where hashing operations would typically slow down due to clustering.

### Implementation Tasks:
1. **Hash Table Setup**: Initialize a hash table with open addressing, using a consistent hash function.
2. **Insertion with Robin Hood Logic**:
   - Calculate the probe distance for each element.
   - On collision, compare probe distances; if the new element has a longer distance, swap it with the existing one.
   - Continue probing for the next available slot as per this logic.
3. **Search Function**: Implement search logic that considers potential displacements.
4. **Delete Function**: Ensure elements can be removed and reinserted as needed without breaking the probe-distance ordering.

### Benefits:
- **Stable Access Times**: Balances load and minimizes maximum probe length, resulting in consistent access times.
- **Effective Load Management**: Useful for applications with high load factors, minimizing clustering in scenarios with dense data storage.

This addition will significantly enhance the hash table’s performance, especially in scenarios where maintaining consistent access speed under high load is essential.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me

**Comment by pankaj-bind** [comment]
assigned
