### ISSUE TITLE
[NEW ALGORITHM] SJFS CPU Scheduling Algorithm

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1465]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Shortest Job First Algorithm

### About:  
The Shortest Job First (SJF) algorithm selects the process with the shortest execution time to run next, aiming to minimize average waiting time. There are two types: Non-Preemptive (where a process runs fully once started) and Preemptive, also called Shortest Remaining Time First (SRTF), where shorter jobs can interrupt ongoing processes. SJF is efficient in reducing turnaround time but can cause starvation for longer processes if shorter ones keep arriving. It’s widely used in batch systems where job durations are known in advance.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me
