### ISSUE TITLE
[NEW ALGORITHM] Real-Time Anomaly Detection in Time Series Data using Rolling Z-Scores

### ISSUE THREAD

**Issue by skanarul8002** [AlgoGenesis/C#1467]
**Issue will be closed if:**
- You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.
- You propose an algorithm that is already present or has been mentioned in a previous issue.
- You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name
**Real-Time Anomaly Detection in Time Series Data using Rolling Z-Scores**

### About
This algorithm identifies anomalies in time series data in real-time by calculating rolling Z-scores, where each data point’s deviation from a rolling mean and standard deviation is assessed. Anomalies are flagged based on a threshold, which can be tuned based on the specific application.

### Labels
**new algorithm, gssoc-ext, hacktoberfest, level1**

### Assignees
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by skanarul8002** [comment]
i would like to work on this issue.

**Comment by pankaj-bind** [comment]
assigned
