### ISSUE TITLE
[NEW ALGORITHM]  Sliding Window 

### ISSUE THREAD

**Issue by itsHarsh2** [AlgoGenesis/C#1468]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
 Sliding Window  

### About:  

The sliding window algorithm is a useful technique for solving problems that involve arrays or lists, especially when you're looking for a contiguous subarray or a subset of elements that meet certain criteria. It allows you to efficiently find solutions without the need for nested loops, which can lead to higher time complexity.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
