### ISSUE TITLE
[NEW ALGORITHM] Multilevel Feedback Queue Scheduling

### ISSUE THREAD

**Issue by itsHarsh2** [AlgoGenesis/C#1469]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Multilevel Feedback Queue Scheduling

### About:  

Multilevel Feedback Queue Scheduling (MLFQ) is a CPU scheduling algorithm designed to optimize process management by allowing processes to move between multiple queues based on their behavior and requirements. Each queue has a different priority and a distinct time quantum, which defines how long a process can execute before being preempted.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me

**Comment by pankaj-bind** [comment]
Do not create multiple issues.

**Comment by itsHarsh2** [comment]
multiple issue h pr sb unique dale h , koi present nhi h site me .Samjhe bhai ise lia dale the😊

**Comment by itsHarsh2** [comment]
dimag mt kharab kre .assign nhi krne to mt kre .
