### ISSUE TITLE
[NEW ALGORITHM] : Selection Sort

### ISSUE THREAD

**Issue by Soumyodeep-Das** [AlgoGenesis/C#147]
---
name: Add New Algorithm
about: Propose a new algorithm to be added to the repository
title: "[NEW ALGORITHM] Selection Sort"
labels: new algorithm, gssoc-ext
assignees: ''
---

## Description:
The Selection Sort algorithm sorts an array by repeatedly selecting the minimum element from the unsorted part and swapping it with the first element of the unsorted part. It maintains two subarrays in a given array: 
1. The sorted subarray, which is built up from left to right.
2. The remaining unsorted subarray.

Key Steps:
- Traverse the array and select the smallest element from the unsorted subarray.
- Swap the selected element with the first unsorted element.
- Move the boundary of the sorted subarray one position to the right and repeat the process.

**Complexity:**
- **Time Complexity:** O(n²) in all cases (best, worst, and average), since it involves two nested loops.
- **Space Complexity:** O(1), as the sorting is done in-place without requiring additional memory.

This algorithm is simple and intuitive, though not very efficient for large datasets. It's useful for teaching basic sorting principles.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Selection Sort is a comparison-based sorting algorithm, and while it may not be as efficient as other algorithms like Merge Sort or Quick Sort for larger datasets, it is easy to implement and understand, making it a popular choice for teaching the basics of sorting.

**Comment by Soumyodeep-Das** [comment]
@sanjay-kv kindly add the hacktoberfest label also.

**Comment by Soumya03007** [comment]
can i work on it ?

**Comment by pankaj-bind** [comment]
@Soumyodeep-Das you can start
