### ISSUE TITLE
[NEW ALGORITHM] B-tree

### ISSUE THREAD

**Issue by itsHarsh2** [AlgoGenesis/C#1470]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
B-tree

### About :  
A B-tree is a self-balancing tree data structure that maintains sorted data and allows efficient search, sequential access, insertion, and deletion operations. It is particularly well-suited for systems that read and write large blocks of data, such as databases and filesystems.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
