### ISSUE TITLE
[NEW ALGORITHM]  Priority Queue

### ISSUE THREAD

**Issue by sarthaxtic** [AlgoGenesis/C#1472]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Priority Queue```  

### About:  
Priority queue is an abstract data type(ADT) in the computer science which is designed to the operate much like the regular queue except that each element has the certain priority. 

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by manikbhatt18** [comment]
I want to work on this and create an algorithm for priority queue

**Comment by pankaj-bind** [comment]
assigned
