### ISSUE TITLE
[NEW ALGORITHM] Optimized Merge of Two BSTs into a Balanced BST Using Two Stacks

### ISSUE THREAD

**Issue by Akash-Adhya** [AlgoGenesis/C#1474]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
 Optimized Merge of Two BSTs into a Balanced BST Using Two Stacks

### About:  
This approach efficiently merges two Binary Search Trees (BSTs) into a single balanced BST to optimize search operations. By using two stacks, we perform an in-order traversal of both trees simultaneously, merging nodes directly into a sorted array without the overhead of fully converting each BST. After merging, we construct a balanced BST from the sorted array by recursively setting middle elements as roots, ensuring height balance. This method optimizes both space and time complexity, ensuring a robust and efficient merge.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
