### ISSUE TITLE
[NEW ALGORITHM] : Prefix to Postfix Conversion

### ISSUE THREAD

**Issue by Mansi-Tanwar** [AlgoGenesis/C#1475]
### Name:  
```[NEW ALGORITHM]```  :  Prefix to Postfix Conversion

### About:  
![image](https://github.com/user-attachments/assets/3b6db8ed-8c7f-44be-8b94-f55d76033cd1)

I searched in pull request section and also the issues but didn't find any for this algo. I would love to add this if you assign the task to me.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by khwaishchawla** [comment]
Assign me this issue

**Comment by Mansi-Tanwar** [comment]
@pankaj-bind please assign the task to me

**Comment by pankaj-bind** [comment]
https://github.com/AlgoGenesis/C/tree/main/Prefix-To-Postfix
