### ISSUE TITLE
[NEW ALGORITHM] Kruskal’s Algorithm - Minimum Spanning Tree

### ISSUE THREAD

**Issue by yashksaini-coder** [AlgoGenesis/C#1477]
### Name:  
```[NEW ALGORITHM] Kruskal’s Algorithm - Minimum Spanning Tree```  

### About:  
Kruskal’s Algorithm is a greedy algorithm used to find the Minimum Spanning Tree (MST) of a connected, undirected graph. It works by sorting all edges by their weights and adding them one by one to the MST, ensuring no cycles are formed. This algorithm is efficient for sparse graphs and widely used in network design, where connecting nodes with minimum cost is crucial.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```  

---

### Assignees:  
- [X] Contributor in GSSoC-ext  
- [ ] Want to work on it  

---

## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

**Comment by surbhisharma004** [comment]
i would like to work this issue.

**Comment by yashksaini-coder** [comment]
> i would like to work this issue.

Hi @surbhisharma004 I have raised this issue, if you want you can later raise an issue to improve my algorithm,

**Comment by yashksaini-coder** [comment]
@pankaj-bind there's no issue for this
