### ISSUE TITLE
[NEW ALGORITHM] Convolutional Neural Networks (CNNs)

### ISSUE THREAD

**Issue by ananyag309** [AlgoGenesis/C#1479]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Convolutional Neural Networks (CNNs)```  

### About:  
Convolutional Neural Networks (CNNs) are a class of deep neural networks specifically designed to process data with a grid-like structure, such as images. CNNs are highly effective in tasks like image classification, object detection, and recognition due to their ability to capture spatial hierarchies in data through convolutional layers.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by Riddhi12349** [comment]
Please assign me

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
