### ISSUE TITLE
[NEW ALGORITHM] Fractal Generation (Mandelbrot Set)

### ISSUE THREAD

**Issue by shubhagarwal1** [AlgoGenesis/C#148]
## Description:
Implementing fractal generation is a visually interesting project that combines complex numbers and recursion. The Mandelbrot set, a famous fractal, is a great example. You can generate this fractal and display it on the screen, using ASCII art or graphical libraries.
Please assign this to me 
## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@shubhagarwal1 ok, you can start
