### ISSUE TITLE
[MERGING TWO SORTED ARRAY USING PRIORITY QUEUE] 

### ISSUE THREAD

**Issue by DinkyRajpoot56** [AlgoGenesis/C#1484]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[MERGING TWO SORTED ARRAY USING PRIORITY QUEUE] ```  

### About: 
Priority Queue Approach
To solve this problem, merge two sorted [arrays](https://www.naukri.com/code360/library/introduction-to-array) using a  [priority queue](https://www.naukri.com/code360/library/heap-and-priority-queue). We will create a min priority queue, and we will push elements of both the array. After that, we will take out elements from the priority queue one by one, and we will insert that element into our final array, and then we will return the array. 

Algorithm
To solve this problem, merge sorted arrays using a priority queue. We first need to create a function mergeTwoArrays() that takes two parameters: the first array and the second array.
In the function, we will declare a priority queue that will store all the elements of both arrays. 
We will now take out the top element of the priority queue one by one and store it in the final array till the priority queue is not empty.
Now we will return the array.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by khwaishchawla** [comment]
assign me this issue

**Comment by pankaj-bind** [comment]
assigned
