### ISSUE TITLE
[NEW ALGORITHM] Rearrange Array

### ISSUE THREAD

**Issue by HUN-sp** [AlgoGenesis/C#1485]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Rearrange Array```  

Given an array `A` of size `N`, rearrange the array such that each element at index `i` becomes `A[A[i]]` with O(1) extra space.

#### Constraints:
- 1 <= N <= 5×10^4
- 0 <= A[i] <= N - 1
- The elements of `A` are distinct.
- `N * N` does not overflow for a signed integer.

#### Input Format:
- The argument `A` is an array of integers.

#### Examples:
1. **Input**: `[1, 0]`
   **Return**: `[0, 1]`
   
2. **Input**: `[0, 2, 1, 3]`
   **Return**: `[0, 1, 2, 3]`

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by HUN-sp** [comment]
@pankaj-bind I would Like to work on this issue

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
