### ISSUE TITLE
[NEW ALGORITHM] Lexicographically Previous Permutation

### ISSUE THREAD

**Issue by Indrajeety993648** [AlgoGenesis/C#1487]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Lexicographically Previous Permutation```

### About:  
```Propose an algorithm to find the lexicographically previous permutation of a given string. If the previous permutation does not exist, return "None".```

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---

### Description:

```markdown
Given a string `s`, find the lexicographically previous permutation of `s`. If `s` is sorted in ascending order, then there is no lexicographically previous permutation.

#### Constraints:
- 1 ≤ |s| ≤ 10^3

#### Expected Time Complexity:
- `O(|s|)`

#### Expected Auxiliary Space:
- `O(1)`

#### Example 1:
- **Input**: `s = "4321"`
- **Output**: `"4312"`
- **Explanation**: The lexicographically previous permutation of `"4321"` is `"4312"`.

#### Example 2:
- **Input**: `s = "1234"`
- **Output**: `"None"`
- **Explanation**: Since `"1234"` is sorted in ascending order, no previous permutation exists.

---

### Solution Outline

1. Start from the right end of the string and look for the first character that is in decreasing order.
2. Swap this character with the largest character on its right that is smaller than it.
3. Reverse the portion of the string to the right of the original position of this character.
4. If no such character is found (string is sorted in ascending order), return `"None"`.

#### Time Complexity:
- `O(|s|)`

#### Space Complexity:
- `O(1)`

---

**Comment by Indrajeety993648** [comment]
@pankaj-bind Would Like to work on this issue

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
