### ISSUE TITLE
[NEW ALGORITHM] Array Manipulation

### ISSUE THREAD

**Issue by Indrajeety993648** [AlgoGenesis/C#1488]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Array Manipulation```

### About:  
```Propose an algorithm to perform a series of operations on an array and find the maximum value after all operations are completed.```

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---

### Description:

```markdown
Starting with a 1-indexed array of zeros, apply a series of operations where each operation adds a specified value to each element within a given range. After all operations are performed, return the maximum value in the array.

#### Function Signature:
- `arrayManipulation(int n, int queries[q][3]) -> int`

#### Parameters:
- `int n`: The number of elements in the array.
- `int queries[q][3]`: A 2D array where each `queries[i]` contains three integers `a`, `b`, and `k` representing the start index, end index (inclusive), and value to be added within that range.

#### Constraints:
- Array indices are 1-based.
- The function should handle large arrays efficiently.

#### Example Input:
n = 5 queries = [ [1, 2, 100], [2, 5, 100], [3, 4, 100] ]
 

#### Example Output:
- `200`

#### Explanation:
1. After the first operation, the array becomes: `[100, 100, 0, 0, 0]`
2. After the second operation, the array becomes: `[100, 200, 100, 100, 100]`
3. After the third operation, the array becomes: `[100, 200, 200, 200, 100]`
4. The maximum value in the array is `200`.

#### Solution Outline:
1. Use a difference array approach:
   - For each operation, increment the start index and decrement the index after the end.
   - Calculate the prefix sum of the array to get the final values after all operations.
2. Return the maximum value from the resultant array.

#### Time Complexity:
- `O(n + q)`

#### Space Complexity:
- `O(n)`

---

**Comment by Indrajeety993648** [comment]
@pankaj-bind Would Like to work on this issue

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
