### ISSUE TITLE
[NEW ALGORITHM] Two-Stack Enqueue and Dequeue (Lazy Transfer)

### ISSUE THREAD

**Issue by yashksaini-coder** [AlgoGenesis/C#1498]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Lazy Transfer Stack to Queue Conversion```

### About:  
Propose a new algorithm to convert a stack to a queue using the **Lazy Transfer** approach with two stacks.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

--- 

@pankaj-bind can you assign this issue to me

**Comment by pankaj-bind** [comment]
assigned
