### ISSUE TITLE
[NEW ALGORITHM] Add Rank-Balanced AVL Trees to AVL Trees Folder

### ISSUE THREAD

**Issue by T-Fathima** [AlgoGenesis/C#1499]
### Name:  
Rank-Balanced AVL Trees

### About:  
Implement an advanced variant of AVL trees known as Rank-Balanced AVL Trees in the AVL trees folder. Rank-Balanced AVL Trees use a rank-based balancing criterion, where each node has an associated rank, and rotations are performed based on rank differences between nodes. This variant is useful for maintaining balance with potentially fewer rotations compared to traditional AVL trees.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
no update
