### ISSUE TITLE
[NEW ALGORITHM] Priority CPU Scheduling Algorithm

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1506]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Priority CPU Scheduling Algorithm

### About:  
The Priority CPU Scheduling algorithm schedules processes based on priority rather than arrival time or burst time. In priority scheduling, each process is assigned a priority, and the CPU is allocated to the process with the highest priority (often the lowest priority number, where 1 is the highest priority).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by Ritika-K7** [comment]
Please assign this issue to me .I would like to work on it .

**Comment by AshmitaBarthwal** [comment]
@Ritika-K7 You can raise Your Own separate Issue of your choice , Since I have raised this Issue So I would like to work on it.

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Please assign this issue to me
