### ISSUE TITLE
[NEW ALGORITHM] Reflection Transformation (Addition Geometric Transformation Algorithms)

### ISSUE THREAD

**Issue by Arushi2S** [AlgoGenesis/C#1512]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```
Reflection Transformation  

### About:  
Propose a new algorithm to be added to the repository
This transformation mirrors a point across the specified axis (X, Y, or Z). Depending on the chosen axis, the corresponding coordinates are negated to reflect the point across that axis, creating a symmetrical effect.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
no update

**Comment by Arushi2S** [comment]
I will do it by tomorrow

**Comment by Arushi2S** [comment]
Can I re open this issue
