### ISSUE TITLE
ADD CICD Workflows for GITHUB Automation

### ISSUE THREAD

**Issue by AnushkaChouhan25** [AlgoGenesis/C#1515]
Implement Continuous Integration and Continuous Deployment (CI/CD) workflows for automating tasks on GitHub. This will streamline the development process by automating testing, builds, and deployments on every code push or pull request.

- Auto Comment on Issue
- Auto Comment on PR
- Auto Comment on PR Merge
- Close Issues on PR Merge
- Comment on Issue Close
- Auto Label Issues
- Auto Label PRs

**Comment by Scholarscribe** [comment]
@AnushkaChouhan25 please add labels of gssoc-ext, hacktoberfest and level to this issue.
