### ISSUE TITLE
Naive Bayes Classifier Algorithm in Machine Learning

### ISSUE THREAD

**Issue by alo7lika** [AlgoGenesis/C#1519]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Naive Bayes Classifier Algorithm in Machine Learning]```  

### About:  
Propose a new algorithm to be added to the repository. The Naive Bayes Classifier is a simple yet powerful probabilistic classifier based on applying Bayes' theorem with strong (naive) independence assumptions between the features. It is particularly useful for classification tasks where the dimensionality of the input is high.

### Algorithm Overview:
- **Type**: Supervised Learning
- **Applications**: Text classification, spam detection, sentiment analysis, and more.
- **Core Concept**: The classifier calculates the posterior probability for each class given the input features, using the formula:
  
  \[
  P(C|X) = \frac{P(X|C) \cdot P(C)}{P(X)}
  \]

  where:
  - \( P(C|X) \) is the posterior probability of class \( C \) given the features \( X \),
  - \( P(X|C) \) is the likelihood of features given class \( C \),
  - \( P(C) \) is the prior probability of class \( C \),
  - \( P(X) \) is the prior probability of features \( X \).

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

### Implementation Plan:
1. **Research** the Naive Bayes algorithm to understand its mathematical foundations and use cases.
2. **Implement** the Naive Bayes algorithm in C, ensuring that it supports binary and multi-class classification.
3. **Test** the implementation with various datasets to ensure accuracy and efficiency.
4. **Document** the algorithm's usage, including installation and examples.

### References:
- Add relevant literature or documentation links to support your implementation and understanding of the algorithm.

**Comment by alo7lika** [comment]
@pankaj-bind assign me the task

**Comment by alo7lika** [comment]
> @pankaj-bind assign me the task

@pankaj-bind

**Comment by pankaj-bind** [comment]
assigned
