### ISSUE TITLE
Wave Sort Algorithm 

### ISSUE THREAD

**Issue by Prarthana-35** [AlgoGenesis/C#152]
Description:
The wave sort works on the principle as follows :
 
arr[0] >= arr[1] <= arr[2] >= arr[3] <= arr[4]

this sorts the array in a wave form. 

Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it 

Can I work on this ? Could you assign this task and the labels for the task @pankaj-bind

**Comment by Prarthana-35** [comment]
Can you please add the level for this @pankaj-bind

**Comment by pankaj-bind** [comment]
@Prarthana-35 you can start
