### ISSUE TITLE
Library Sort

### ISSUE THREAD

**Issue by Subashree-selvaraj** [AlgoGenesis/C#1526]
Description 
Library Sort is a comparison-based sorting algorithm, also known as Gapped Insertion Sort. It enhances the traditional insertion sort by creating gaps within the array to reduce the number of shifts required when inserting elements. This makes it more efficient for larger datasets compared to the standard insertion sort.

Kindly assign it to me under gssoc'24 ext

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
