### ISSUE TITLE
[NEW ALGORITHM] Bron-Kerbosch Algorithm for undirected graph

### ISSUE THREAD

**Issue by IkkiOcean** [AlgoGenesis/C#1529]
### Name:  
Bron-Kerbosch Algorithm

### About:  

The Bron-Kerbosch Algorithm is a recursive, backtracking algorithm, widely used in fields such as social network analysis, bioinformatics, and community detection, where identifying clusters or highly interconnected subgroups is valuable. It’s efficient for finding all cliques in sparse graphs and often outperforms brute-force approaches due to its pruning techniques.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
