### ISSUE TITLE
[UPDATE ALGORITHM]  I Have a slightly odd proposal.

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [AlgoGenesis/C#153]
## Description:
I see that this is a C only repository , but I feel most prefer c++ aswell and making a seperate folder where all C++ is present can prove to be very helpful for everybody.

## Checklist:
- [X] Contributor in GSSoC-ext
- [x] Want to work on it

## Affected Algorithm:
Searching Algorithm
Sorting Algorithms
StackQueues

Please do consider this request.

**Comment by harish08102004** [comment]
Hey @T-Rahul-prabhu-38 I can work on this.

**Comment by pankaj-bind** [comment]
@T-Rahul-prabhu-38 we have separate repository for those but those are not part of GSSoC.
