### ISSUE TITLE
[NEW ALGORITHM] Remove all occurence 

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1536]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Remove all occurrence```  

### About:
  If you want to remove all occurrences of a specific character (or a substring) from a given string in C, you can do this by creating a new string and copying only the characters that you want to keep. Below is a C program that demonstrates how to remove all occurrences of a specified character from a string.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

 Please assign me the issue 
@pankaj-bind

**Comment by Dipanita45** [comment]
Please assign me the issue 
@pankaj-bind

**Comment by Dipanita45** [comment]
Please assign me the issue 
@pankaj-bind

**Comment by pankaj-bind** [comment]
assigned
