### ISSUE TITLE
[NEW ALGORITHM]: Postfix to Infix Conversion 

### ISSUE THREAD

**Issue by Mansi-Tanwar** [AlgoGenesis/C#1539]
### Name:  
```[NEW ALGORITHM] : Postfix to Infix ```  

### About:  

![image](https://github.com/user-attachments/assets/bb8e4307-38ff-46c3-b6b1-94fc0e0e2c4c)

I explored the GitHub repo. There was code for infix to postfix, but neither the code for postfix to infix nor any pull requests for this algorithm were present. If you assign this task to me, I would love to complete it. Thank You.  

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Mansi-Tanwar** [comment]
@pankaj-bind please assign the task to me.

**Comment by Mansi-Tanwar** [comment]
@pankaj-bind please assign the task to me.

**Comment by pankaj-bind** [comment]
assignec

**Comment by Mansi-Tanwar** [comment]
#1570
