### ISSUE TITLE
[NEW ALGORITHM] Min Stack

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#1541]
### Name:  
```[NEW ALGORITHM]```  Design a Data Structure SpecialStack that supports all the stack operations like push(), pop(), isEmpty(), isFull() and an additional operation getMin() which should return minimum element from the SpecialStack. All these operations of SpecialStack must have a time and space complexity of O(1). 

### About:  
A famous stack data structure problem that perfroms all operations with least time complexity.

### Input:
push() , pop() , getmin(), operation to choose.

### Output:
The corresponding opertaion.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

### Adiitional Information:
Please assign me this issue I want to work on it.

**Comment by pankaj-bind** [comment]
assigned
