### ISSUE TITLE
SMWAK Algorithm Via Recursion 

### ISSUE THREAD

**Issue by MithanshuHedau** [AlgoGenesis/C#1543]
### About:  
The SMAWK algorithm is an efficient method for finding row minima in totally monotone matrices, a specific type of matrix where entries decrease or stay constant along each row and column. Developed for optimizing complex search operations, this algorithm leverages a unique recursive approach, reducing computation time to O(m+n) for an m×n matrix, making it ideal for applications in computational geometry, dynamic programming, and machine learning. With SMAWK, developers gain a powerful tool for solving matrix-based problems more effectively, significantly improving the performance of algorithms that depend on finding minimum values in large, structured datasets
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [✅ ] Contributor in GSSoC-ext
- [✅] Want to work on it

**Comment by MithanshuHedau** [comment]
Please assign me with this issue , so i can contribute in that

**Comment by pankaj-bind** [comment]
assigned
