### ISSUE TITLE
Implement Function to Find Inorder Successor and Predecessor in BST 

### ISSUE THREAD

**Issue by Kamini8707** [AlgoGenesis/C#1545]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

 Name:  
Implement Function to Find Inorder Successor and Predecessor in BST

### About:  
Description: I would like to contribute a C implementation for finding the Inorder Successor and Predecessor in a Binary Search Tree (BST). This feature is beneficial for users working with tree traversal and node navigation in various applications, such as database indexing and memory management.

Proposed Solution: The solution includes:
1. A findPredecessor function to locate the Inorder Predecessor of a given node, helping in left-subtree traversal.
2. A findSuccessor function to locate the Inorder Successor of a given node, assisting in right-subtree traversal.
3. A main function that demonstrates and tests the functionality on an example BST.
The code will feature clear comments and structured logic for ease of understanding.

Justification: Adding this feature to the project will enhance its functionality, especially for users who require traversal tools in their BST implementations. This can be helpful for educational purposes as well as practical applications in systems that rely on hierarchical data structures.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
assigned

**Comment by Kamini8707** [comment]
Please merge it.
