### ISSUE TITLE
[NEW ALGORITHM] Banker's Algorithm

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1549]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Banker's Algorithm

### About:  
The Banker's Algorithm is a resource allocation and deadlock avoidance algorithm used in operating systems. It ensures that resources are allocated only if the system can stay in a safe state, meaning all processes can complete without causing deadlock. The algorithm checks if the requested resources can be granted by calculating a "safe sequence," where each process can obtain its maximum required resources and release them after completion. If such a sequence exists, the system is considered safe. Otherwise, the request is denied to avoid entering an unsafe state.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
