### ISSUE TITLE
[NEW ALGORITHM] Rotation of Array under 1D array

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [AlgoGenesis/C#1552]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Rotation of Array```  

### About:  
This helps shift elements left or right by a specified number of positions, with elements wrapping around the 1D array.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by surbhisharma004** [comment]
@rajdeepchakraborty-rc i would like to work on this issue. kindly assign me this issue.

**Comment by pankaj-bind** [comment]
assigned

**Comment by rajdeepchakraborty-rc** [comment]
Thanks for assigning the issue

**Comment by rajdeepchakraborty-rc** [comment]
@pankaj-bind Please review the PR.
