### ISSUE TITLE
Library sort

### ISSUE THREAD

**Issue by Subashree-selvaraj** [AlgoGenesis/C#1555]
### Description
Library Sort is a comparison-based sorting algorithm, also known as Gapped Insertion Sort. It enhances the traditional insertion sort by creating gaps within the array to reduce the number of shifts required when inserting elements. This makes it more efficient for larger datasets compared to the standard insertion sort.

Kindly assign it to me under gssoc'24 ext

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
assigned

**Comment by Subashree-selvaraj** [comment]
@pankaj-bind  raised PR ! Kindly check it
