### ISSUE TITLE
Principal Component Analysis (PCA) In Machine Learning

### ISSUE THREAD

**Issue by alo7lika** [AlgoGenesis/C#1558]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
**Principal Component Analysis (PCA) In Machine Learning**

### About:  
I propose adding the Principal Component Analysis (PCA) algorithm to the repository. PCA is a powerful dimensionality reduction technique used in machine learning that transforms data into a lower-dimensional space while preserving as much variance as possible. This will be beneficial for users looking to preprocess their data for various machine learning tasks.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by alo7lika** [comment]
@pankaj-bind Assign me the task

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
no update
