### ISSUE TITLE
[NEW ALGORITHM] Markov Chain Monte Carlo (MCMC) Algorithm

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#1559]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Markov Chain Monte Carlo (MCMC) Algorithm
### About:  
Propose to add the Markov Chain Monte Carlo (MCMC) algorithm to the repository. MCMC is a probabilistic algorithm used in statistical sampling and machine learning. It is useful for drawing samples from complex probability distributions and is widely applied in Bayesian inference and statistical modeling.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [ YES] Want to work on it

**Comment by pankaj-bind** [comment]
assigned

**Comment by 13Sharad** [comment]
@pankaj-bind please merged this pull request.
