### ISSUE TITLE
[NEW ALGORITHM] Sweep Line Algorithm for Convex Hull

### ISSUE THREAD

**Issue by Bhupendrakumar20** [AlgoGenesis/C#1562]
## Issue will be closed if:

1. You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.
2. You propose an algorithm that is already present or has been mentioned in a previous issue.
3. You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Sweep Line Algorithm for Convex Hull```  

### About:  
Propose the implementation of the Sweep Line Algorithm for calculating the Convex Hull of a given set of points in a 2D plane. This algorithm is efficient and has a time complexity of O(n log n), making it suitable for inclusion in the repository.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```  

---

### Assignees:  
- [ ] Contributor in GSSoC-ext  
- [ ] Want to work on it  

---

**Comment by Bhupendrakumar20** [comment]
@pankaj-bind kindly review the issue and assigned if possible

**Comment by pankaj-bind** [comment]
assigned
