### ISSUE TITLE
[NEW ALGORITHM] Hungarian Algorithm for Assignment Problem

### ISSUE THREAD

**Issue by Bhupendrakumar20** [AlgoGenesis/C#1569]
**Issue will be closed if:**
- You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.
- You propose an algorithm that is already present or has been mentioned in a previous issue.
- You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

**Name:**  
[NEW ALGORITHM] Hungarian Algorithm for Assignment Problem

**About:**  
Propose the implementation of the **Hungarian Algorithm** to solve the assignment problem, where tasks are assigned to agents to either minimize the total cost or maximize the profit, given an \( n \times n \) cost matrix. The Hungarian Algorithm, with a time complexity of \( O(n^3) \), ensures an optimal solution and is widely used in optimization problems in areas like logistics and operational research.

**Labels:**  
new algorithm, gssoc-ext, hacktoberfest, level1

**Assignees:**  
Contributor in GSSoC-ext  
Want to work on it

---

**Comment by Bhupendrakumar20** [comment]
@pankaj-bind kindly review the issue ...and possibly kindly assigned it to me

**Comment by pankaj-bind** [comment]
assigned
