### ISSUE TITLE
[NEW ALGORITHM] Shortest Remaining Time CPU Scheduling 

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1575]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   SHORTEST REMAINING TIME CPU SCHEDULING ALGORITHM 

### About:  
Shortest Remaining Time First (SRTF) is a preemptive version of the Shortest Job First (SJF) scheduling algorithm. In SRTF, the CPU always executes the process that has the smallest remaining time. If a new process arrives with a shorter remaining time than the current process, the CPU will switch to execute this new process.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by khwaishchawla** [comment]
@pankaj-bind kindly assign me the issue

**Comment by pankaj-bind** [comment]
add explanation of this algorithm

**Comment by khwaishchawla** [comment]
@pankaj-bind done with required changes

**Comment by pankaj-bind** [comment]
assigned
