### ISSUE TITLE
[NEW ALGORITHM] Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by SKG24** [AlgoGenesis/C#1581]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Intersection of Two Linked Lists]```  

### About:  
Propose a new algorithm to be added to the repository
Given the heads of two singly linked-lists headA and headB, return the node at which the two lists intersect. If the two linked lists have no intersection at all, return null.

Input:  listA = [4,1,8,4,5], listB = [5,6,1,8,4,5]

![Screenshot 2024-11-02 at 10 27 43 PM](https://github.com/user-attachments/assets/6d5a145a-58a4-42cc-9bd9-e393a8e3c580)
Output: Intersected at '8'

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by manastiwari99** [comment]
I would like to work please assign it to me

**Comment by pankaj-bind** [comment]
assigned
