### ISSUE TITLE
[NEW ALGORITHM]  PageRank Algorithm

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#1588]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
PageRank Algorithm

### About:  
The PageRank algorithm, originally developed by Larry Page and Sergey Brin, is a method for ranking web pages based on their importance in the context of the web's link structure. It operates on the premise that more important pages are likely to receive more links from other pages.

In this implementation, the algorithm can be applied to directed graphs, where nodes represent web pages and edges represent hyperlinks between them. The rank of a page is determined by the ranks of the pages linking to it, scaled by the number of outbound links from those pages.

Key features of the PageRank algorithm include:

 >Damping Factor: This factor accounts for the probability that a user will continue clicking on links rather than jumping to a new page. A common value is 0.85.
 >Convergence: The algorithm iteratively adjusts page ranks until they stabilize, which is achieved when the change in ranks between iterations falls below a certain threshold.
 >Applications: Beyond web page ranking, PageRank can also be used in social network analysis to determine the influence of users based on their connections.
This implementation will provide a foundational understanding of the PageRank algorithm and serve as a valuable resource for those interested in graph theory and social network analysis

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [YES ] Want to work on it

**Comment by manastiwari99** [comment]
I would like to work please assign it to me

**Comment by pankaj-bind** [comment]
assigned
