### ISSUE TITLE
[NEW ALGORITHM] Handshaking Lemma and Interesting Tree Properties

### ISSUE THREAD

**Issue by Deepika14145** [AlgoGenesis/C#1593]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Handshaking Lemma and Interesting Tree Properties

### About:  
Propose a new algorithm to be added to the repository:
[Handshaking lemma](https://www.geeksforgeeks.org/handshaking-lemma-and-interesting-tree-properties/) is about an undirected graph. In every finite undirected graph, an even number of vertices will always have an odd degree. The handshaking lemma is a consequence of the degree sum formula (also sometimes called the handshaking lemma) 

\sum_{u \epsilon v} deg(v) = 2\left | E \right |

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

Please assign me this task @pankaj-bind

**Comment by manastiwari99** [comment]
I would like to work Please assign it to me

**Comment by pankaj-bind** [comment]
assigned
