### ISSUE TITLE
 Divide and Conquer Maximum Subarray Problem

### ISSUE THREAD

**Issue by Subashree-selvaraj** [AlgoGenesis/C#1596]
The Maximum Subarray Problem is a classical algorithmic problem that involves finding the contiguous subarray within a one-dimensional array of numbers which has the largest sum. This problem can be efficiently solved using the Divide and Conquer approach.

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by manastiwari99** [comment]
I would like to work Please assign it to me

**Comment by Subashree-selvaraj** [comment]
I have raised the issue so kindly assign it to me
