### ISSUE TITLE
 Common Recursion Problems 

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [AlgoGenesis/C#16]
1.Factorial of a Number 
2.Tower of Hanoi  
3. Permutations of a String

**Comment by pankaj-bind** [comment]
@Adarsh-Chaubey03, issue #16 is yours.

**Comment by Adarsh-Chaubey03** [comment]
> @Adarsh-Chaubey03, issue #16 is yours.

I am a contributor of GSSoC- Extd

**Comment by simmi-verma** [comment]
I have experience solving various array algorithms . As a current contributor to GSSoC-Extd.  I’d love to contribute by adding implementations for some key algorithms,
