### ISSUE TITLE
[NEW ALGORITHM] Branch and Bound

### ISSUE THREAD

**Issue by priyanka350** [AlgoGenesis/C#160]
## Description:
Addition of Branch and Bound algorithm and its applications in C program.

## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

## Additional Information:
Branch and Bound algorithm for solving optimization problems by systematically exploring and pruning branches of the solution space to find the optimal solution.

Please assign this issue to me.

**Comment by pankaj-bind** [comment]
@priyanka350 you can start.
