### ISSUE TITLE
[NEW ALGORITHM] Island Perimeter 

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1608]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Island Perimeter```  

### About:  
You are given row x col grid representing a map where grid[i][j] = 1 represents land and grid[i][j] = 0 represents water.

Grid cells are connected horizontally/vertically (not diagonally). The grid is completely surrounded by water, and there is exactly one island (i.e., one or more connected land cells).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ yes] Contributor in GSSoC-ext
- [ yes] Want to work on it
- 
Please assign me this issue 
@pankaj-bind

**Comment by pankaj-bind** [comment]
assigned
