### ISSUE TITLE
[NEW ALGORITHM] Add Levenshtein Distance Algo [DP]

### ISSUE THREAD

**Issue by NK-Works** [AlgoGenesis/C#1611]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Levenshtein Distance

### About:  
The Levenshtein distance algorithm, also known as edit distance, measures the minimum number of single-character edits required to change one string into another. These edits can be insertions, deletions, or substitutions.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
