### ISSUE TITLE
[NEW ALGORITHM] Bee  Algorithm

### ISSUE THREAD

**Issue by AE-Hertz** [AlgoGenesis/C#1614]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Bee  Algorithm```  

### About:  
Propose a new algorithm to be added to the repository
To add this algorithm so users can learn about this algo too. and its a complex algo , and its is used for various optimization task.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
