### ISSUE TITLE
[NEW ALGORITHM] Ripple Effect Scheduling (RES) Algorithm

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1616]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Ripple Effect Scheduling (RES) Algorithm

### About:  
The Ripple Effect Scheduling (RES) algorithm prioritizes tasks based on their priority level, aiming to minimize disruptions to lower-priority tasks. It first sorts tasks by priority and calculates waiting and turnaround times. A "ripple effect" adjustment slightly reduces waiting time for lower-priority tasks when preceded by higher-priority tasks. This approach ensures high-priority tasks are handled efficiently while minimizing the impact on lower-priority ones.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
