### ISSUE TITLE
[NEW ALGORITHM] Addition of Doubly Linked list algorithms

### ISSUE THREAD

**Issue by Upendra48** [AlgoGenesis/C#162]
## Description:
I would like to contribute by implementing the following algorithms for Doubly Linked Lists:

* Insertion: At the start, at the end, and at a specific position.
* Deletion: Remove nodes at the beginning, at the end or by position.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

Looking forward for your approval and assignment so I could start working on it.
(Please add **gssoc-ext 24** and **hacktoberfest** label)

**Comment by Supraja-Gao** [comment]
@Upendra48 please assign this issue to me. I would like to work on this issue

**Comment by Upendra48** [comment]
Hi, @Supraja-Gao
I am not the admin, and I am waiting for the admin to assign this issue to me, 
I request you to find some other issue to start contributing.
Good luck for it!
