### ISSUE TITLE
[NEW ALGORITHM] Zigzag Conversion

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1631]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Zigzag Conversion```  

### About:  
The string "PAYPALISHIRING" is written in a zigzag pattern on a given number of rows like this: (you may want to display this pattern in a fixed font for better legibility)

P   A   H   N
A P L S I I G
Y   I   R
And then read line by line: "PAHNAPLSIIGYIR"

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

Please merge my pull request and label me 
@pankaj-bind

**Comment by pankaj-bind** [comment]
assigned
