### ISSUE TITLE
[NEW ALGORITHM]: Implementation of circular array

### ISSUE THREAD

**Issue by Richajaishwal0** [AlgoGenesis/C#1648]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Circular array

### About:  
A circular array is a linear data structure that connects the end of the array back to the beginning, forming a circle. This allows for efficient use of space by enabling the reuse of vacant positions created by deletions. In a circular array, the concept of the "next" index wraps around to the beginning when the end of the array is reached, facilitating operations like insertion and deletion without shifting elements. It is commonly used in applications like circular queues and ring buffers, where a fixed-size buffer is required to manage streaming data or tasks in a cyclic manner.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues until your previous issue is resolved.
