### ISSUE TITLE
[NEW ALGORITHM]  ADDITION OF CIRCULAR LINKED LIST 

### ISSUE THREAD

**Issue by Riya7045** [AlgoGenesis/C#165]
### **Description:**
I am proposing an algorithm to implement a Circular Linked List.
Algorithm Overview:
Insertion: Nodes can be inserted at the beginning, end, or any specific position. 
Traversal: The list can be traversed in both directions (forward and backward), and the traversal continues in a circular manner.
Deletion: Nodes can be deleted from any position.

### **Checklist:**

- [ ]  Contributor in GSSoC-ext
- [ ]  Want to work on it

## Additional Information:
Please assign this issue to me @sanjay-kv  .
(Please add gssoc-ext 24 and hacktoberfest label and also level 1 or level 2 or level 3 label)

**Comment by shuvojitss** [comment]
I am a Contributor in GSSoC-ext. Please assign it to me

**Comment by pankaj-bind** [comment]
@Riya7045 you can start

**Comment by Riya7045** [comment]
ok i will start working on this
