### ISSUE TITLE
[NEW ALGORITHM] Implement Pigeonhole Principle-Based Sorting Algorithm

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#1650]
**Issue Title:** Implement Pigeonhole Principle-Based Sorting Algorithm

**Description:**
This task involves implementing a sorting algorithm based on the pigeonhole principle, an often-overlooked but powerful concept in combinatorics. The pigeonhole principle asserts that if there are more items than containers, at least one container must hold multiple items. In sorting, this principle is applied by mapping values to unique "pigeonholes" (or bins) based on their range or specific properties, making it highly efficient for certain types of data. 

The Pigeonhole Sorting algorithm is most suitable for datasets where values lie within a small, fixed range, allowing each value to be directly placed into an array bucket, which makes it faster than comparison-based sorts like quicksort or mergesort for constrained ranges.

**What It Will Do:**
The implementation will involve:
1. Identifying the minimum and maximum values in the dataset to determine the range.
2. Creating a set of "pigeonholes" (bins) based on this range.
3. Iteratively placing each item in the dataset into its corresponding pigeonhole.
4. Retrieving items in sorted order by reading from the pigeonholes.

**Benefits:**
This algorithm is efficient for integer-based sorting with a constrained range and will provide a unique solution for handling data in specific scenarios, such as preparing data for radix sort or simplifying histogram-like problems. Implementing this algorithm will also introduce users to the pigeonhole principle, a useful concept in both combinatorics and computer science.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
https://github.com/AlgoGenesis/C/tree/main/Sorting%20Algorithms/Pigeon%20Hole%20Sort
