### ISSUE TITLE
[NEW ALGORITHM] LONGEST REMAINING TIME FIRST CPU SCHEDULING

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1655]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  LONGEST REMAINING TIME FIRST CPU SCHEDULING 

### About:  
Propose a new algorithm to be added to the repository
The Longest Remaining Time First (LRTF) scheduling algorithm is a preemptive version of the Longest Job First (LJF) scheduling. In LRTF, the process with the longest remaining burst time is chosen to execute next, and it can be preempted if a new process arrives with a longer remaining burst time.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by khwaishchawla** [comment]
@pankaj-bind i want to work on this issue

**Comment by pankaj-bind** [comment]
assigned
