### ISSUE TITLE
[NEW ALGORITHM] Merged Two Sorted Linked List

### ISSUE THREAD

**Issue by SKG24** [AlgoGenesis/C#1657]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Merge Two Sorted Linked List]```  

### About:  
Propose a new algorithm to be added to the repository

Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.
We are supposed to return the head of the merged linked list.

Input: list1 = [1,2,4], list2 = [1,3,4]
Output: [1,1,2,3,4,4]

---

### Labels:  
```new algorithm, gssoc-ext, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
