### ISSUE TITLE
[NEW ALGORITHM] Flux Memory Balancer Algorithm

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1658]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   Flux Memory Balancer (FMB) algorithm

### About:  
The Flux Memory Balancer (FMB) algorithm dynamically allocates memory to processes based on their priority and memory requirements, ensuring efficient utilization of available memory. Higher-priority processes receive their requested memory first, while lower-priority processes may receive reduced memory if total demand exceeds capacity. If necessary, FMB redistributes memory by incrementally reducing allocations from lower-priority processes. This flux mechanism ensures memory stability and priority alignment in constrained environments.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Please assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
