### ISSUE TITLE
[NEW ALGORITHM] UNIFORM COST SEARCH (UCS)

### ISSUE THREAD

**Issue by surbhisharma004** [AlgoGenesis/C#1660]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  UNIFORM COST SEARCH (UCS)

### About:  
Propose a new algorithm to be added to the repository
Uniform Cost Search (UCS) is an algorithm used to find the shortest path in a graph by always expanding the least costly path first. It’s similar to Dijkstra’s algorithm and is optimal for finding the minimum-cost path to a target, as it prioritizes nodes based on cumulative path cost rather than depth or heuristic.  Dijkstra’s is a specific instance used for all reachable nodes with non-negative weights, whereas UCS is more general and can be used to find the least costly path to a specific goal with various edge weights.
It’s best suited for cases where paths have different costs, and the goal is to minimize total travel or resource cost.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
