### ISSUE TITLE
[NEW ALGORITHM] Interleaving Strings

### ISSUE THREAD

**Issue by NK-Works** [AlgoGenesis/C#1663]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Interleaving Strings```  

### About:  

The Interleaving Strings problem is a dynamic programming problem where we determine if a string C can be formed by interleaving two other strings A and B while preserving the order of characters in both strings.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
