### ISSUE TITLE
[NEW ALGORITHM] Merge Linked List at Alternate Positions

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#1673]
### Issue Title
Merge Linked List at Alternate Positions

### Issue Description
**Description:**
Implement a function that merges one linked list into another at alternate positions. Given two linked lists, the function should insert nodes of the second list into the first list at every alternate position. After merging, the nodes of the second list that are not merged should remain unchanged.

**Requirements:**
1. Write a function `mergeAlternatePositions(head1, head2)` where `head1` is the head of the first linked list, and `head2` is the head of the second linked list.
2. The function should merge `head2` into `head1` at alternate positions.
3. If one linked list is longer than the other, the extra nodes of the longer list should remain unaffected.

**Example:**
For example, given:
- `List1: 1 -> 2 -> 3 -> 4`
- `List2: 9 -> 8 -> 7`

After merging, `List1` should become `1 -> 9 -> 2 -> 8 -> 3 -> 7 -> 4`, and `List2` should be unaffected for any remaining nodes.

**Expected Complexity:**
- Time Complexity: O(n), where `n` is the length of the shorter linked list.
- Space Complexity: O(1), as the merge should be performed in-place.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by divyaaa16** [comment]
@divyalakshmi0  please assign me this issue , I would like to work on this

**Comment by divyaaa16** [comment]
@pankaj-bind Please assign me this issue
