### ISSUE TITLE
[NEW ALGORITHM]: Want to add Find Missing Number in Array problem in bit manipulation folder

### ISSUE THREAD

**Issue by Jivanjamadar** [AlgoGenesis/C#1674]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Find Missing Number in Array problem
```[NEW ALGORITHM]```  

### About:  

The **Find Missing Number in Array** problem is a classic bit manipulation and arithmetic problem. In problem solution I are implementing XOR method to solve it effectively.

**Problem:**
Given an array of integers containing numbers from 1 to N, where N is the length of the array plus one, find the missing number. There’s exactly one missing number, and all other numbers are unique and present exactly once.

**_Input:_**
```
int nums[] = {1, 2, 4, 5};  // Array with one missing number
int n = 5;  // The range is from 1 to 5

```
**_output_**
```
Missing number is: 3
```
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by Jivanjamadar** [comment]
@pankaj-bind assign this issue to me

**Comment by pankaj-bind** [comment]
assigned
