### ISSUE TITLE
[NEW ALGORITHM] Daily Temperature 

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1677]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]. Daily Temperatures```  

### About:  
Given an array of integers temperatures represents the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the ith day to get a warmer temperature. If there is no future day for which this is possible, keep answer[i] == 0 instead.

 
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it
  
Please assign me this issue 
@pankaj-bind

**Comment by theonlybigmiao** [comment]
@pankaj-bind I‘m interested in it.Please assign it to me.

**Comment by Dipanita45** [comment]
Please assign me this issue 
@pankaj-bind
