### ISSUE TITLE
[NEW ALGORITHM] Find Minimum and Maximum in Array under Recursion

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [AlgoGenesis/C#1678]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Find Minimum and Maximum in Array]```  

### About:  
Use recursion to find the minimum and maximum elements in a given array.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by theonlybigmiao** [comment]
I think I can try it.

**Comment by theonlybigmiao** [comment]
I think I can try it.Please assign it to me.

**Comment by rajdeepchakraborty-rc** [comment]
@pankaj-bind Please review the issue and assign it to me.

**Comment by pankaj-bind** [comment]
assigned
