### ISSUE TITLE
[NEW ALGORITHM] UNROLL LINKED LIST

### ISSUE THREAD

**Issue by aditiverma-21** [AlgoGenesis/C#1679]
### About:  Unrolled linked lists are a variation where each node stores an array of elements rather than a single element, thus reducing the number of nodes and improving cache performance.
Potential Use Case: Efficient for applications requiring high cache performance, such as graphics rendering, or where linked lists are too slow due to frequent memory allocation.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by divyaaa16** [comment]
Hello! I would love to work on this issue , can you please assign this to me?

**Comment by divyaaa16** [comment]
@aditiverma-21 Please can you assign this issue to me?

**Comment by aditiverma-21** [comment]
@divyaaa16 I was assigned and I created the PR

**Comment by aditiverma-21** [comment]
@pankaj-bind please assign

**Comment by divyaaa16** [comment]
@aditiverma-21 Okh , But there are no assignees to this issue so I messaged

**Comment by aditiverma-21** [comment]
Okay @divyaaa16 
I created this issue and want to work on it

**Comment by aditiverma-21** [comment]
@pankaj-bind please assign

**Comment by pankaj-bind** [comment]
Do not create multiple issues.A

**Comment by aditiverma-21** [comment]
@pankaj-bind sorry for my mistake can you assign me this one only now?
