### ISSUE TITLE
[NEW ALGORITHM] Intersection of Two Linked Lists

### ISSUE THREAD

**Issue by aditiverma-21** [AlgoGenesis/C#1680]
### Description: Detects if two linked lists intersect and finds the intersection point if they do. This can be achieved by using two pointers that traverse each list and reset to the beginning of the other list until they meet.
Potential Use Case: Used in scenarios where you need to check shared structures, like in social networks or networked data.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.A
