### ISSUE TITLE
[NEW ALGORITHM] 

### ISSUE THREAD

**Issue by aditiverma-21** [AlgoGenesis/C#1682]
### Description: Implement quicksort specifically for linked lists, with partitioning done through linked node rearrangements.
Potential Use Case: Quick and efficient sorting for linked lists where mergesort isn’t ideal.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.A
