### ISSUE TITLE
[NEW ALGORITHM] Conversion of Linked List to Balanced Binary Search Tree

### ISSUE THREAD

**Issue by aditiverma-21** [AlgoGenesis/C#1683]
### Description: Given a sorted linked list, convert it into a balanced binary search tree.
Potential Use Case: Useful for converting sequentially sorted data into a tree format for faster access in search-related applications.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.A
