### ISSUE TITLE
[NEW ALGORITHM] Union of two 1-d arrays

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [AlgoGenesis/C#1684]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Union of Two Sorted Arrays]```  

### About:  
It will take two one dimensional arrays in sorted format and give their union as the output.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by divyaaa16** [comment]
@Arghya-Chakraborty0812 I would love to work on this issue , please can you assign this issue to me?

**Comment by nandinisharma166** [comment]
I would love to work on this issue , please allow me to work on this.

**Comment by divyaaa16** [comment]
@pankaj-bind Please assign me this issue !

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
Raise your PR before 11:30PM otherwise, it will not considered in GSSOC-ext.

**Comment by pankaj-bind** [comment]
Raise your PR 45 minutes left.
