### ISSUE TITLE
[NEW ALGORITHM] Dijkstra's Algorithm

### ISSUE THREAD

**Issue by Mahima-2404** [AlgoGenesis/C#169]
## Description:
A weighted graph is given and a source vertex is provided in the graph. Through this algorithm we can find the shortest paths from the source to all other vertices of the graph. 

## Checklist:
- [ ✔️] Contributor in GSSoC-ext
- [✔️ ] Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by Sancharisingh** [comment]
@Mahima-2404 @pankaj-bind  Please assign this issue to me I want to work on this.

**Comment by Supraja-Gao** [comment]
@Mahima-2404 please assign this issue to me. I would like to work on this issue

**Comment by Supraja-Gao** [comment]
please assign this issue to me also. I would like to work on this issue.

**Comment by shuvojitss** [comment]
Please assign this Issue to me I will fix this

**Comment by UtsavKashyap1710** [comment]
// A weighted graph is given and a source vertex is provided in the graph. Through this algorithm we can find the shortest paths from the source to all other vertices of the graph.
// answer of this

#include <iostream>
#include <vector>
#include <queue>
#include <utility>
#include <limits.h>

using namespace std;

typedef pair<int, int> pii;  // pair of (distance, vertex)

void dijkstra(int source, vector<vector<pii>>& graph, int V) {
    // Initialize distance array with infinity
    vector<int> dist(V, INT_MAX);
    dist[source] = 0;

    // Min-heap priority queue to select vertex with the smallest distance
    priority_queue<pii, vector<pii>, greater<pii>> pq;
    pq.push({0, source});

    while (!pq.empty()) {
        int u = pq.top().second;  // Current vertex
        int uDist = pq.top().first;  // Distance to the current vertex
        pq.pop();

        // Explore neighbors of u
        for (const auto& neighbor : graph[u]) {
            int v = neighbor.second;  // Neighbor vertex
            int weight = neighbor.first;  // Edge weight

            // Relaxation step
            if (dist[u] + weight < dist[v]) {
                dist[v] = dist[u] + weight;
                pq.push({dist[v], v});
            }
        }
    }

    // Print shortest distances from source
    for (int i = 0; i < V; ++i) {
        if (dist[i] == INT_MAX)
            cout << "Vertex " << i << " is unreachable from source.\n";
        else
            cout << "Distance from source to vertex " << i << " is " << dist[i] << ".\n";
    }
}

int main() {
    int V = 5;  // Number of vertices
    vector<vector<pii>> graph(V);

    // Graph represented as adjacency list (weight, vertex)
    graph[0].push_back({10, 1});
    graph[0].push_back({5, 3});
    graph[1].push_back({1, 2});
    graph[1].push_back({2, 3});
    graph[2].push_back({4, 4});
    graph[3].push_back({3, 2});
    graph[3].push_back({2, 4});
    graph[4].push_back({6, 0});

    int source = 0;
    dijkstra(source, graph, V);

    return 0;
}
``
