### ISSUE TITLE
[UPDATE ALGORITHM] Indian denomination problem

### ISSUE THREAD

**Issue by AE-Hertz** [AlgoGenesis/C#1695]
## Description:
Please describe the changes you want to make to the existing algorithm and why they are necessary.

[Indian denomination problem]

optimize this code using dynamic problem;
current space and time complexity is - O(n log n + n * n) and O(n + amount) respectively.

## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

## Affected Algorithm:
[Indian denomination proble

@pankaj-bind can i work on this/

**Comment by pankaj-bind** [comment]
assigned
