### ISSUE TITLE
[NEW ALGORITHM] N-Queen Problem In Dynamic Programming

### ISSUE THREAD

**Issue by PasamTharun** [AlgoGenesis/C#1696]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  N-Queen Problem 

### About:  
The N-Queen Problem involves placing N queens on an N×N chessboard so that no two queens attack each other. This means no two queens are in the same row, column, or diagonal. The solution uses backtracking to explore all possible placements for the queens. The N-Queen problem is a well-known combinatorial problem that can be solved using backtracking or optimization techniques.

Input: N (the number of queens and the size of the board)
Output: All possible placements of the queens, where each configuration represents a solution

Approach:
The most common approach to solving the N-Queen problem is through backtracking:

Place a queen on a row, then move to the next row.
Check if the queen placement is safe by ensuring no queens are in the same row, column, or diagonal.
If safe, proceed; if not, backtrack and try the next position.
Continue until all queens are placed or all possibilities are exhausted.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create multiple issues.

**Comment by PasamTharun** [comment]
If I raises multiple issues u can close either of one right ???
