### ISSUE TITLE
[UPDATE ALGORITHM] Deadlock avoidance algorithm

### ISSUE THREAD

**Issue by PasamTharun** [AlgoGenesis/C#1698]
## Description:
The Deadlock Avoidance Algorithm currently uses hardcoded values for resources and processes. I want to update the algorithm to allow dynamic input from the user, which will make the algorithm more interactive and practical for varied use cases. This change will involve modifying the code to:

Take the number of processes and resources from the user.
Accept maximum resource demand and allocation matrices as input.
Use the user inputs to perform deadlock avoidance (Banker’s algorithm).

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Affected Algorithm:
Algorithm: Deadlock Avoidance (Banker's Algorithm)
Directory: Specify the directory path(https://github.com/AlgoGenesis/C/blob/main/Deadlock%20avoidance%20algorithm/Banker's%20Algorithm.c)

## Additional Information:
Implementing this change will require prompts for user inputs and validation checks to ensure correct data entry. This update will enhance the algorithm's usability, making it more flexible and adaptable for testing with various process/resource configurations.

**Comment by pankaj-bind** [comment]
Do not create multiple issues.

**Comment by PasamTharun** [comment]
Why u have closed both issues????
