### ISSUE TITLE
[NEW ALGORITHM] Moore's Voting Algorithm

### ISSUE THREAD

**Issue by meghanakn473** [AlgoGenesis/C#170]
The algorithm aim is to:
Return the number which appears more than N/2 times .

- Im Contributor in GSSoC-ext
- I Want to work on it

**Comment by meghanakn473** [comment]
@mehul-m-prajapati please assign me this issue, i want to work on it

**Comment by mehul-m-prajapati** [comment]
@meghanakn473 : I am not owner of this repo.. @pankaj-bind will assign it.

**Comment by meghanakn473** [comment]
@pankaj-bind can u please assign me this issue
