### ISSUE TITLE
Implement Merge Sort for Linked List

### ISSUE THREAD

**Issue by Kamini8707** [AlgoGenesis/C#1701]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Implement Merge Sort for Linked List

### About:  
Description:
This feature involves implementing the Merge Sort algorithm to sort a singly linked list. Merge Sort is particularly well-suited for linked lists due to its O(n log n) time complexity and efficiency with non-contiguous memory structures. This contribution will add a mergeSort function for linked lists, enabling sorting without converting to an array or using extra memory.

Problem Statement:
Currently, the LinkedList folder does not include a method to sort a linked list in an efficient way. Sorting with Merge Sort directly on a linked list structure avoids the additional space and time costs associated with array-based sorting techniques, making it an optimal choice.

Proposed Solution:
1. Recursive Merge Sort: The linked list will be split into two halves until each sublist has only one element.
2. Merge Operation: Two sorted sublists will be merged into a single sorted list, ensuring the overall list remains sorted.
3. Algorithm Implementation:
  - Identify the middle node using the fast-and-slow pointer technique.
  - Recursively apply the mergeSort function on each half.
  - Merge the sorted halves to form the final sorted linked list.
  
Expected Complexity:
Time Complexity: O(n log n)
Space Complexity: O(log n) due to recursive stack space.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by divyaaa16** [comment]
@pankaj-bind  please can you assign me this issue ?
