### ISSUE TITLE
[NEW ALGORITHM] PANCAKE SORT

### ISSUE THREAD

**Issue by surbhisharma004** [AlgoGenesis/C#1702]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  PANCAKE SORT ALGORITHM

### About:  
Propose a new algorithm to be added to the repository
Pancake Sort is a sorting algorithm that sorts an array by repeatedly "flipping" subarrays. In each step, it finds the largest unsorted element, flips it to the front, and then flips it again to its correct position. This process is repeated until the entire array is sorted. The algorithm is inspired by the idea of flipping a stack of pancakes to order them by size, with the largest pancake at the bottom.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by surbhisharma004** [comment]
@pankaj-bind please assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
