### ISSUE TITLE
[NEW ALGORITHM] MULTILEVEL QUEUE CPU SCHEDULING 

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1706]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  MULTILEVEL QUEUE CPU SCHEDULING 

### About:  
Multilevel Queue Scheduling is a CPU scheduling method where processes are classified into different queues based on certain criteria, such as process type (foreground, background), priority, or resource requirements. Each queue operates independently with its own scheduling algorithm, like FCFS for background tasks or Round Robin for interactive tasks. Processes remain in their assigned queue and do not move between them. This approach allows for distinct scheduling policies suited to the specific needs of each process group, enhancing overall system efficiency. However, it can lead to issues like lower-priority processes facing starvation if higher-priority queues dominate CPU time.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by khwaishchawla** [comment]
@pankaj-bind kindly assign me this isssue

**Comment by pankaj-bind** [comment]
assigned
