### ISSUE TITLE
[NEW ALGORITHM] Multilevel Feedback Queue Scheduling:

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1709]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Multilevel Feedback Queue Scheduling:

### About:  

Multilevel Feedback Queue Scheduling
Multilevel Feedback Queue (MLFQ) Scheduling is an advanced CPU scheduling algorithm designed to dynamically adjust the priority of processes based on their behavior and requirements. Unlike Multilevel Queue Scheduling, where processes are assigned to fixed queues, MLFQ allows processes to move between different queues based on their execution history, which makes it more flexible and adaptive to varying workloads.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
