### ISSUE TITLE
[NEW ALGORITHM] : Climbing Stairs

### ISSUE THREAD

**Issue by ananydev** [AlgoGenesis/C#1710]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name: Climbing Stairs
  ```[NEW ALGORITHM]```  

### About:  
Propose a new algorithm to be added to the repository
You are climbing a staircase. It takes n steps to reach the top.

Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?

 

Example 1:

Input: n = 2
Output: 2
Explanation: There are two ways to climb to the top.
1. 1 step + 1 step
2. 2 steps
Example 2:

Input: n = 3
Output: 3
Explanation: There are three ways to climb to the top.
1. 1 step + 1 step + 1 step
2. 1 step + 2 steps
3. 2 steps + 1 step
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by ananydev** [comment]
@pankaj-bind kindly update

**Comment by ananydev** [comment]
@pankaj-bind pls assign it to me

**Comment by ananydev** [comment]
@pankaj-bind kindly update

**Comment by pankaj-bind** [comment]
assigned
