### ISSUE TITLE
[NEW ALGORITHM] Longest Bitonic String

### ISSUE THREAD

**Issue by NK-Works** [AlgoGenesis/C#1712]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Longest Bitonic String```  

### About:  
Longest Bitonic Subsequence (LBS) problem is a variation of the longest increasing subsequence problem. A bitonic subsequence is a sequence that first increases, then decreases. The goal is to find the length of the longest subsequence that follows this pattern within a given sequence of numbers.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
