### ISSUE TITLE
[NEW ALGORITHM] Vortex Cache Replacement Algorithm (VCRA)

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1715]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Vortex Cache Replacement Algorithm (VCRA)

### About:  
The VCRA is a conceptual algorithm that focuses on dynamically managing cache by prioritizing frequently accessed pages and strategically replacing pages that are less likely to be needed in the near future, based on historical access patterns.This algorithm combines aspects of Least Recently Used (LRU) and Frequency-Based caching strategies to balance both recency and frequency, making it adaptable in environments with mixed workloads.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly assign this issue to me.

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly assign this issue to me.

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
