### ISSUE TITLE
[NEW ALGORITHM] Kth largest element in an array 

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1716]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Kth largest element in an array```  

### About: 
Given an integer array nums and an integer k, return the kth largest element in the array.

Note that it is the kth largest element in the sorted order, not the kth distinct element.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
-  [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

Please assign me this issue 
@pankaj-bind

**Comment by Dipanita45** [comment]
Please assign me this issue 
@pankaj-bind

**Comment by pankaj-bind** [comment]
assigned
