### ISSUE TITLE
[NEW ALGORITHM] Merging Two Sorted Arrays Using Circular Queue 

### ISSUE THREAD

**Issue by DinkyRajpoot56** [AlgoGenesis/C#1719]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Merging Two Sorted Arrays Using Priority Queue]```  

### About:  
Explanation:
Circular Queue Implementation: A circular queue structure is used to store the intermediate merged results.
Enqueue and Dequeue Operations: Functions enqueue and dequeue manage the insertion and removal of elements.
Merging Logic: Two pointers are used to iterate through the sorted arrays, and elements are enqueued in ascending order.
Output: The merged array is dequeued and printed in sorted order.
Complexity:
Time Complexity: 
𝑂
(
𝑛
+
𝑚
)
O(n+m), where 
𝑛
n and 
𝑚
m are the sizes of the two arrays.
Space Complexity: 
𝑂
(
𝑛
+
𝑚
)
O(n+m) for storing elements in the queue.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by theonlybigmiao** [comment]
I've already solve it.If ths problem is considered valuable,please reserve the issue and I will submit it soon.Hopefully I can take responsibility of it.

**Comment by pankaj-bind** [comment]
assigned
