### ISSUE TITLE
XOR Singly Linked List

### ISSUE THREAD

**Issue by prishsha** [AlgoGenesis/C#172]
Description:
An XOR Linked List is a variation in regular singly linked list where the XOR value of the address of the current node and the next node is stored as the link. This has wide applications in security.

Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

Additional Information:
I will provide the algorithm, along with an overview of the problem and my approach to it. Kindly assign it to me under gssoc-ext, hacktober-accepted labels and specify the level of the problem. 
 
@pankaj-bind   
@saiam123 
@shekharyv

**Comment by jyothimanoj12** [comment]
plz  assign me this

**Comment by jyothimanoj12** [comment]
also can you plz add the level

**Comment by pankaj-bind** [comment]
@prishsha you can sratr
