### ISSUE TITLE
Detect Palindrome in a Linked List

### ISSUE THREAD

**Issue by Kamini8707** [AlgoGenesis/C#1720]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Detect Palindrome in a Linked List

### About:  

Description:
This feature request is to implement an algorithm that checks if a singly linked list is a palindrome. A linked list is considered a palindrome if its elements read the same forward and backward. This algorithm will add a isPalindrome function to the LinkedList folder to check for this condition efficiently.

Problem Statement:
Currently, there is no function in the LinkedList folder to check if a linked list is a palindrome. This is a common problem encountered in coding interviews, where the solution should be optimized for both time and space complexity.

Proposed Solution:
Two-Pointer Approach:
Use a fast and slow pointer to reach the midpoint of the linked list.
Reverse the second half of the linked list.
Compare the first half and the reversed second half node-by-node to check for palindrome properties.

Edge Cases:
Handle lists with a single node (which is always a palindrome).
Check empty lists (considered a palindrome by convention).

Expected Complexity:
Time Complexity: O(n)
Space Complexity: O(1) (in-place checking with no additional data structures).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by SWITCHin2** [comment]
@Kamini8707 Can you assign this to me? [gssoc contributor]

**Comment by Kamini8707** [comment]
please assign me this task.
