### ISSUE TITLE
[NEW ALGORITHM] Magic Square under 2D array

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [AlgoGenesis/C#1724]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Magic Square]```  

### About:  
Check if a given matrix(2D array) is a magic square (where the sum of rows, columns, and diagonals are the same).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by rajdeepchakraborty-rc** [comment]
@pankaj-bind I have resolved my previous issue and opened a PR. So I have opened this issue since I have completed my previous issue.
Please assign it to me.

**Comment by pankaj-bind** [comment]
assigned

**Comment by rajdeepchakraborty-rc** [comment]
Thanks for assigning the issue.

**Comment by rajdeepchakraborty-rc** [comment]
@pankaj-bind While forking and cloning the repo, this issue is showing:
![image](https://github.com/user-attachments/assets/f2c2673c-19ef-485f-9d62-90e494bdb960)

The repository cannot be cloned. This is after the recent PR that you merged, Can you please check it?
