### ISSUE TITLE
[UPDATE ALGORITHM] AVL Trees Algorithms code redundancy 

### ISSUE THREAD

**Issue by AE-Hertz** [AlgoGenesis/C#1726]
## Description:
Please describe the changes you want to make to the existing algorithm and why they are necessary.
AVL Trees Algorithms code redundancy , in the current code there is lot of calculation redundancy and caching issues.
i work on this and provide a optimized solution

## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

## Affected Algorithm:
Mention which algorithm you want to update and the specific directory where you want to change.

## Additional Information:
Any extra details or suggestions related to the update.

@pankaj-bind can you please assign me this./

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
Can you provide me the link of Program that you want to update

**Comment by AE-Hertz** [comment]
And can you please reopen and merge my request #1765  i need points. If that ok can you please help me with it my not closing it.
