### ISSUE TITLE
[NEW ALGORITHM] Rank-Balanced AVL Tree

### ISSUE THREAD

**Issue by T-Fathima** [AlgoGenesis/C#1727]
### Name:  
Rank-Balanced AVL Tree

### About:  
I would like to propose to add an implementation for a Rank-Balanced AVL Tree. This hybrid data structure combines aspects of rank-balanced trees and AVL trees, using rank differences to maintain efficient balance without excessive rotations. Rank-balanced AVL trees adjust ranks after insertions and deletions to maintain balanced heights

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
