### ISSUE TITLE
[NEW ALGORITHM] Dice Throw Problem

### ISSUE THREAD

**Issue by surbhisharma004** [AlgoGenesis/C#1732]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Dice Throw Problem Algorithm

### About:  
Propose a new algorithm to be added to the repository
The **Dice Throw Problem** is a dynamic programming problem where the goal is to find the number of ways to reach a target sum using a fixed number of dice, each with a certain number of faces. The algorithm computes the number of possible ways to achieve the sum by iteratively adding dice values and considering all previous possible outcomes. It typically uses a 2D table to store intermediate results, with one dimension representing the dice count and the other representing the sum.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by surbhisharma004** [comment]
@pankaj-bind please assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
