### ISSUE TITLE
[NEW ALGORITHM] Sliding Window Technique

### ISSUE THREAD

**Issue by shriyadindi** [AlgoGenesis/C#1734]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Sliding Window Algorithm

### About:  
Propose a new algorithm to be added to the repository

- Efficiently solves problems involving arrays or strings by maintaining a dynamic window of elements.
- Optimizes finding subarrays or substrings that meet specific criteria (e.g., maximum sum, length, patterns).
- Reduces time complexity from O(n^2) or higher to O(n), enhancing performance for large inputs.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
