### ISSUE TITLE
[NEW ALGORITHM] The Nearest Common Ancestor of a BST

### ISSUE THREAD

**Issue by theonlybigmiao** [AlgoGenesis/C#1736]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[The nearest commen ancestor of a BST]```  

### About:  
Given a binary search tree, find the nearest common ancestors of the two specified nodes in that tree.
For the two nodes p and q of the root tree T, the nearest common ancestor is represented as one node x, satisfying x is the ancestor of p and q and the depth of x is as large as possible.A node can also be its own ancestor.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [√ ] Contributor in GSSoC-ext
- [ √] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
