### ISSUE TITLE
[NEW ALGORITHM] Lottery Scheduling

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1737]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   Lottery Scheduling

### About:  

Concept: Uses randomness to allocate CPU time by assigning "lottery tickets" to processes.
Implementation: Each process is assigned tickets based on priority. A ticket is drawn at each scheduling decision to select a process.
Usage: Can simulate various scheduling strategies and provides fairness without rigid priority queues.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
