### ISSUE TITLE
[NEW ALGORITHM] SCAN (Elevator) Disk Scheduling Algorithm

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1740]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  SCAN (Elevator) Disk Scheduling Algorithm

### About:  
The SCAN (Elevator) algorithm for disk scheduling moves the disk arm in one direction to serve all requests sequentially until it reaches the end or the last request in that direction. After reaching the end, it reverses direction and serves requests on the way back. This approach reduces seek time compared to other algorithms like FCFS by minimizing the back-and-forth movement. It’s effective in preventing starvation and balancing seek times across all requests.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly assign this issue to me

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly assign this issue to me

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly assign this issue to me

**Comment by pankaj-bind** [comment]
assigned
