### ISSUE TITLE
[NEW ALGORITHM] Gang scheduling

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1742]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]``` gang scheduling 

### About:  
Concept: Schedules related processes (e.g., threads in a parallel application) to execute simultaneously on separate CPUs.
Implementation: Schedules threads as a "gang" to prevent idle time due to dependencies.
Usage: Common in high-performance computing clusters where processes need synchronized CPU access.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
Raise your PR before 11:30PM otherwise, it will not considered in GSSOC-ext.
