### ISSUE TITLE
[URGENT] Invalid Directory causing Cloning issue

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [AlgoGenesis/C#1744]
After the recent PR, you merged : PR #1711,
The Contributor has broken the codebase cloning due to improper directory path naming:
![image](https://github.com/user-attachments/assets/a0d1d7fb-d522-40c6-82a2-aefa8e3b1cef)

The colon ( : ) in the Folder name is failing the cloning process:

![Screenshot 2024-11-08 125808](https://github.com/user-attachments/assets/649573c0-8e05-46f3-b40a-53736af3a2e9)

**Comment by rajdeepchakraborty-rc** [comment]
@pankaj-bind Please resolve the issue by renaming and removing the colon ( : ) from the folder name. Or let me know if I should do it.

**Comment by pankaj-bind** [comment]
issue fixed

**Comment by rajdeepchakraborty-rc** [comment]
> issue fixed

Thanks
