### ISSUE TITLE
Add Code of Conduct file

### ISSUE THREAD

**Issue by subin-shk** [AlgoGenesis/C#175]
## Description:
Your project repo misses an important point Code of Conduct file which invites unnecessary elements to the project and spoil the environment here. I can make one for you

## Checklist:
- [ Yes] Contributor in GSSoC-ext
- [Yes ] Want to work on it

**Comment by pankaj-bind** [comment]
https://github.com/AlgoGenesis/C/blob/main/CONTRIBUTING.md
