### ISSUE TITLE
[NEW ALGORITHM] Cycle Detection in a Directed Graph (Using DFS)

### ISSUE THREAD

**Issue by Ananya-vastare** [AlgoGenesis/C#1752]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.
### Name:  
Cycle Detection in a Directed Graph (Using DFS)

### About:  
Propose a new algorithm to be added to the repository
Cycle detection in a directed graph using Depth-First Search (DFS) works by tracking visited nodes and using a recursive call stack to check for back edges, which indicate cycles. In this algorithm, each node is marked as "visited" when first traversed and added to a "recursion stack." If the DFS reaches a node that’s already in this recursion stack, a cycle exists because we've encountered a back edge, meaning we can reach the same node via a different path. Once a DFS path completes, the node is removed from the recursion stack, ensuring that only the current recursive path is checked for cycles. This method is efficient, with a time complexity of O(V+E), making it suitable for applications like dependency resolution and detecting infinite loops in graphs.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```
gssoc-extd

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
