### ISSUE TITLE
[NEW ALGORITHM] Addition of 4 Important Algorithms in Backtracking Algorithms 

### ISSUE THREAD

**Issue by Shariq2003** [AlgoGenesis/C#176]
## Description:

Additon of :- 
1. Subset Sum Problem
2. Permutations and Combinations
3. Rat in a Maze
4. Hamiltonian Path Problem

## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on ita

@pankaj-bind assign this to me.

**Comment by pankaj-bind** [comment]
@Shariq2003 you can start

**Comment by Shariq2003** [comment]
Thanks
