### ISSUE TITLE
[NEW ALGORITHM]: Want to add SHA-256 (Secure Hash Algorithm 256-bit) algorithm in hash algorithm folder

### ISSUE THREAD

**Issue by Jivanjamadar** [AlgoGenesis/C#1762]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  SHA-256 (Secure Hash Algorithm 256-bit) 
```[NEW ALGORITHM]```  

### About:  

SHA-256 (Secure Hash Algorithm 256-bit) is a cryptographic hash function in the SHA-2 family. It produces a 256-bit (32-byte) hash value, which is commonly represented as a 64-character hexadecimal number.
**Common Use Cases:**

- Digital signatures and certificates
- Data integrity verification
- Blockchain hashing (e.g., Bitcoin)
- Password hashing (when combined with additional techniques like salting and key stretching)

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by Jivanjamadar** [comment]
@pankaj-bind assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
