### ISSUE TITLE
[NEW ALGORITHM] Word Ladder II (Shortest Transformation Sequence)

### ISSUE THREAD

**Issue by NK-Works** [AlgoGenesis/C#1775]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Word Ladder II (Shortest Transformation Sequence)```  

### About:  
The Word Ladder II problem involves finding the shortest transformation sequence(s) from a begin word to an end word by changing only one letter at a time. Each transformed word must exist in a given word list. The goal is to find all the shortest possible sequences that meet these criteria.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
