### ISSUE TITLE
[NEW ALGORITHM] SmartSlice algorithm

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1787]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  SmartSlice algorithm

### About:  
The SmartSlice algorithm is a dynamic CPU scheduling technique that adjusts time slices based on process burst times, enhancing efficiency over standard Round Robin. Short burst processes receive smaller time slices, allowing quick execution, while longer burst processes receive larger slices, reducing context switching. This tailored approach optimizes both waiting and turnaround times. It’s ideal for systems with a mix of short and long tasks.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly Assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned

**Comment by pankaj-bind** [comment]
Raise your PR before 11:30PM otherwise, it will not considered in GSSOC-ext.

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind PR already raised and merged.
