### ISSUE TITLE
[NEW ALGORITHM] Using Two Stacks to Implement a Queue

### ISSUE THREAD

**Issue by shriyadindi** [AlgoGenesis/C#1788]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Using Two Stacks to Implement a Queue

### About:  

- Implements a queue using two stacks to manage enqueue and dequeue operations efficiently.
- Ensures elements are enqueued onto the first stack and dequeued from the second, leveraging stack transfer for correct order.
- Provides an amortized O(1) time complexity for both operations, making it a practical and efficient solution.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
