### ISSUE TITLE
[NEW ALGORITHM] Proportional Share Scheduling (Fair-Share)

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1789]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
Proportional Share Scheduling (Fair-Share)
### About:  
Propose a new algorithm to be added to the repository

Proportional Share Scheduling, also known as Fair-Share Scheduling, is an advanced CPU scheduling method that distributes CPU resources among multiple processes, users, or applications in a way that respects predefined "shares" or "weights." Each process (or user) is assigned a portion of CPU resources based on these shares, which ensures fair allocation in environments where multiple entities compete for CPU time.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by khwaishchawla** [comment]
@pankaj-bind kindly assign

**Comment by pankaj-bind** [comment]
assigned
