### ISSUE TITLE
[NEW ALGORITHM] Josephus Problem 

### ISSUE THREAD

**Issue by surbhisharma004** [AlgoGenesis/C#1790]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Josephus Problem Algorithm

### About:  
Propose a new algorithm to be added to the repository
A recursive approach to solving the elimination-based problem.The Josephus Problem recursively eliminates every 
k-th person in a circle of N people until one remains. The recursive formula is: J(N,k)=(J(N−1,k)+k) modN where J(1,k)=0.  
The Josephus Problem algorithm in recursion is a way to find the "safe position" in a group of N people standing in a circle, where every k-th person is eliminated in a loop until only one person remains. The recursive approach uses a mathematical formula to determine the position of the last person left.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by surbhisharma004** [comment]
@pankaj-bind please assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
