### ISSUE TITLE
[NEW ALGORITHM] Circular Queue Using Two Stacks

### ISSUE THREAD

**Issue by DinkyRajpoot56** [AlgoGenesis/C#1793]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Circular Queue Using Two Stacks]```  

### About:  
xplanation of the Code:
Stack Operations:

push: Adds an element to the stack by incrementing the top pointer.
pop: Removes the element from the stack by decrementing the top pointer.
Queue Operations:

Enqueue: Adds an element to the circular queue by pushing it onto Stack 1.
Dequeue: Removes an element from the queue:
If Stack 2 is empty, all elements are moved from Stack 1 to Stack 2, reversing their order.
After that, we pop the top element from Stack 2 to return the dequeued element.
Display: Displays the elements of the queue, printing elements from Stack 2 (in reverse order) and Stack 1 (top to bottom).

Circular Queue Behavior: Although we are using two stacks, the behavior of enqueue and dequeue in a circular queue is simulated by managing the size and ensuring that the queue behaves like a circular structure. Once it’s full, it will start overwriting old elements.
Two Stack Simulation: The two-stack approach is a simple way to implement a queue by reversing the order of elements between two stacks. It allows us to perform both enqueue and dequeue operations efficiently, though each operation has a time complexity of O(n) when transferring elements between stacks.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
