### ISSUE TITLE
[NEW ALGORITHM]  Queue Reconstruction by Height

### ISSUE THREAD

**Issue by SimranShaikh20** [AlgoGenesis/C#1798]
## Issue will be closed if:

To reconstruct the queue of people based on their attributes, we first sort the input array by height in descending order, and by the number of people in front (ki) in ascending order for those with the same height. This ensures that taller individuals are considered first when placing them in the queue. We then initialize an empty queue and iterate through the sorted list, inserting each person at the index corresponding to their ki value. This guarantees that each person has the correct number of taller or equal-height individuals in front of them. Finally, we return the constructed queue as the output.

### Name:  
Queue Reconstruction by Height 

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

@pankaj-bind  assign me this issue !

**Comment by SimranShaikh20** [comment]
@pankaj-bind !

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
