### ISSUE TITLE
[NEW ALGORITHM]  Predict the Winner

### ISSUE THREAD

**Issue by SimranShaikh20** [AlgoGenesis/C#1799]
## Issue will be closed if:

Problem Statement

You are given an integer array nums. Two players, Player 1 and Player 2, take turns picking numbers from either end of the array. Player 1 starts first, and both players aim to maximize their scores. The player who has the highest score at the end of the game wins. If the scores are tied, Player 1 is considered the winner.

Return true if Player 1 can guarantee a win, assuming both players play optimally.

### Name:  
Predict the Winner

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

@pankaj-bind assign me this issue !

**Comment by SimranShaikh20** [comment]
@pankaj-bind !

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
