### ISSUE TITLE
Searching Algorithms/Best-First Search /Program.c

### ISSUE THREAD

**Issue by Deeptig9138** [AlgoGenesis/C#18]
Memory Leak: The Node created in enqueue is never freed. After you finish using the node (when the search is complete), ensure to free it to avoid memory leaks.
Out-of-Bounds Access: Ensure that the enqueue function does not exceed the MAX_NODES limit when adding nodes. You may want to add a check to prevent this.
Inefficient Enqueue Operation: The current implementation of enqueue has a time complexity of O(n) due to shifting elements, which can be improved by using a linked list for the priority queue.
Heuristic Initialization: In the main function, ensure that the heuristic values are meaningful for your graph structure.
Proper Cleanup: In the bestFirstSearch, free the memory allocated for nodes after processing them to prevent memory leaks.

Can you please assign this to me @pankaj-bind

**Comment by Charul00** [comment]
can i work on this please assign to me

**Comment by Deeptig9138** [comment]
> @Deeptig9138 You can start now

can you also add hacktoberfest label here

**Comment by pankaj-bind** [comment]
> > @Deeptig9138 You can start now
> 
> can you also add hacktoberfest label here

I can do but I don't think it will be counted, we have guidelines to add this lable in out project repo only.

**Comment by Deeptig9138** [comment]
okay. thank you
