### ISSUE TITLE
[NEW ALGORITHM] Addition of New Linked List Algorithms

### ISSUE THREAD

**Issue by Shariq2003** [AlgoGenesis/C#180]
## Description:
1. Reversing a Linked List
2. Detecting a Cycle in a Linked List (Floyd's Cycle Detection)
3. Merging Two Sorted Lists
4. Finding the Middle of a Linked List
5. Removing N-th Node from End of List
6. Flattening a Multilevel Doubly Linked List

## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by AnshDwivedi03** [comment]
Done all the necessary changes whatever mentioned. Kindly merge my pr @Shariq2003

**Comment by Shariq2003** [comment]
@AnshDwivedi03, why you have raised a PR without even being assigned for the issue, please follow the guidelines int the contributing.md file to do the contributions.

**Comment by AnshDwivedi03** [comment]
@Shariq2003 No issue assign it to me simply

**Comment by Shariq2003** [comment]
@AnshDwivedi03 I am not the author, that's why I can't assign. Also I have created this issue for myself to resolve.

**Comment by AnshDwivedi03** [comment]
@Shariq2003  work on ability instead of saying .
