### ISSUE TITLE
[NEW ALGORITHM]  Verbal Arithmetic Puzzle

### ISSUE THREAD

**Issue by SimranShaikh20** [AlgoGenesis/C#1800]
## Issue will be closed if:

Problem Description
The Verbal Arithmetic Puzzle involves determining if an equation represented by words can be solved by assigning unique digits (0-9) to each character. Each word on the left side of the equation must sum up to the number represented by the word on the right side. The mapping must satisfy the following rules:

Each character is mapped to a unique digit.
No two characters can map to the same digit.
Words cannot have leading zeros.
The sum of the numbers formed by the words on the left must equal the number formed by the result on the right.

### Name:  
Verbal Arithmetic Puzzle

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

@pankaj-bind assign me this issue !

**Comment by SimranShaikh20** [comment]
@pankaj-bind !

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
