### ISSUE TITLE
[NEW ALGORITHM] Tiling Problem DP

### ISSUE THREAD

**Issue by NK-Works** [AlgoGenesis/C#1802]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Tiling Problem```  

### About:  
The Tiling Problem is a classic problem in dynamic programming, where the task is to determine the number of ways to completely cover a 2xN board using 2×1 tiles.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
assigned
