### ISSUE TITLE
[NEW ALGORITHM] Longest Common Prefix Under Strings

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [AlgoGenesis/C#1804]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Longest Common Prefix]```  

### About:  
This program finds the Longest Common Prefix (LCP) among an array of strings. It starts by assuming the first string as the prefix and iteratively compares it with each subsequent string, updating the prefix to the common portion. If no common prefix exists, it stops early. The program is useful for applications like string analysis, autocomplete systems, and pattern matching.

**Input**:
```
Enter the number of strings: 3
Enter the strings:
String 1: flower
String 2: flow
String 3: flight
```

**Output**:
```
The longest common prefix is: fl
```

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by tharikashree** [comment]
Hey can i work on this

**Comment by pankaj-bind** [comment]
assigned
