### ISSUE TITLE
[NEW ALGORITHM] Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree

### ISSUE THREAD

**Issue by SimranShaikh20** [AlgoGenesis/C#1805]
## Issue will be closed if:

In graph theory, a Minimum Spanning Tree (MST) is a subset of the edges of a connected, weighted, undirected graph that connects all vertices with the minimum possible total edge weight, without any cycles. In the context of MSTs, edges can be classified into two categories:

Critical Edges: These are edges that, when removed, increase the total weight of the MST. Their presence is essential for maintaining the minimum weight.

Pseudo-Critical Edges: These edges can be included in some MSTs but are not required in all. Their inclusion does not guarantee that the MST weight will remain the same across different MSTs.

Identifying critical and pseudo-critical edges helps in understanding the structure and flexibility of the MST in a given graph.

### Name:  
 Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree

### About:  
Find Critical and Pseudo-Critical Edges in Minimum Spanning Tree

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

@pankaj-bind pls assign me this issue

**Comment by SimranShaikh20** [comment]
@pankaj-bind !

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
