### ISSUE TITLE
[NEW ALGORITHM] Repeated DNA Sequences Sliding Window

### ISSUE THREAD

**Issue by SimranShaikh20** [AlgoGenesis/C#1806]
## Issue will be closed if:

Problem Explanation
The task is to identify all 10-letter-long substrings (sequences) in a given DNA sequence that occur more than once. The DNA sequence is represented as a string consisting of characters 'A', 'C', 'G', and 'T', which are the four nucleotides found in DNA.

### Name:  
Repeated DNA Sequences Sliding Window

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
@pankaj-bind pls assign me this issue !

**Comment by SimranShaikh20** [comment]
@pankaj-bind !

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
