### ISSUE TITLE
[NEW ALGORITHM] Cheapest Flights Within K Stops Graph Probelm

### ISSUE THREAD

**Issue by SimranShaikh20** [AlgoGenesis/C#1807]
## Issue will be closed if:

 the problem is about finding the cheapest way to travel between two cities given a set of flights, while also considering a limit on the number of stops. It tests your ability to work with graphs and optimize paths based on costs and constraints.

### Name:  
Cheapest Flights Within K Stops

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

@pankaj-bind pls assign me this issue!

**Comment by SimranShaikh20** [comment]
@pankaj-bind !

**Comment by pankaj-bind** [comment]
Do not create multiple issues.
