### ISSUE TITLE
[UPDATE ALGORITHM] Traversal of a Binary Tree without Recursion

### ISSUE THREAD

**Issue by theonlybigmiao** [AlgoGenesis/C#1810]
## Description:
We have implemented recursive preorder, inorder, and postorder traversals of a binary tree, and now I would like to supplement them with their non-recursive counterparts.

## Checklist:
- [√] Contributor in GSSoC-ext
- [√] Want to work on it

## Affected Algorithm:
Mention which algorithm you want to update and the specific directory where you want to change.

## Additional Information:
Any extra details or suggestions related to the update.

**Comment by pankaj-bind** [comment]
assigned
