### ISSUE TITLE
[NEW ALGORITHM] Weighted Fair Queueing (WFQ)

### ISSUE THREAD

**Issue by surbhisharma004** [AlgoGenesis/C#1814]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Weighted Fair Queueing (WFQ)

### About:  
Propose a new algorithm to be added to the repository
Weighted Fair Queueing (WFQ) is an advanced scheduling algorithm that provides fair and prioritized resource allocation among multiple tasks or flows. It is widely used in networking and operating systems to ensure Quality of Service (QoS) by allocating bandwidth or CPU time to each task according to its assigned weight. This approach is particularly effective in environments where differentiated service levels are needed, as it can prioritize certain flows while maintaining fairness across all tasks.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by surbhisharma004** [comment]
@pankaj-bind please assign this issue to me.

**Comment by pankaj-bind** [comment]
assigned
