### ISSUE TITLE
[NEW ALGORITHM] Two-Level Scheduling Algorithm (TLS)

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1824]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Two-Level Scheduling Algorithm (TLS)

### About:  
Propose a new algorithm to be added to the repository
The TLS algorithm combines a primary and secondary scheduling mechanism. In the first level, processes are allocated to specific CPUs, and the second level uses local scheduling on each CPU. It’s often used in systems that require distributed or clustered scheduling.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Raise your PR before 11:30PM otherwise, it will not considered in GSSOC-ext.
