### ISSUE TITLE
Simhash Algorithm 

### ISSUE THREAD

**Issue by ananyashinde2434** [AlgoGenesis/C#1849]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

SIMHASH ALGORITHM

SimHash is a hashing algorithm designed to create a compact "fingerprint" of a document or text, enabling quick similarity comparisons between texts. It’s often used for tasks like detecting duplicate content, plagiarism detection, and clustering similar documents. 

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
Raise your PR before 11:30PM otherwise, it will not considered in GSSOC-ext.

**Comment by pankaj-bind** [comment]
Raise your PR 45 minutes left.
