### ISSUE TITLE
[NEW ALGORITHM] Adaptive Disk Reordering (ADR) Algorithm

### ISSUE THREAD

**Issue by AshmitaBarthwal** [AlgoGenesis/C#1853]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Adaptive Disk Reordering (ADR) Algorithm

### About:  
The Adaptive Disk Reordering (ADR) algorithm is designed to optimize disk scheduling by dynamically adjusting the order of pending I/O requests based on current disk head position, data locality, and request frequency. This can lead to significant improvements in disk access times, especially in environments with changing access patterns.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Kindly assign this issue to me.

**Comment by pankaj-bind** [comment]
Raise your PR before 11:30PM otherwise, it will not be considered in GSSOC-ext.

**Comment by AshmitaBarthwal** [comment]
@pankaj-bind Raised the PR.
