### ISSUE TITLE
[NEW ALGORITHM] Merge n ascending Linked Lists

### ISSUE THREAD

**Issue by theonlybigmiao** [AlgoGenesis/C#1856]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Merge n ascending Linked Lists]```  

### About:  
Given an array of linked lists, each of which is already in ascending.

Please merge all linked lists into an sorted linked list and return the merged linked list.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [√] Contributor in GSSoC-ext
- [√] Want to work on it

**Comment by pankaj-bind** [comment]
Raise your PR before 11:30PM otherwise, it will not be considered in GSSOC-ext.

**Comment by pankaj-bind** [comment]
Raise your PR 45 minutes left.
