### ISSUE TITLE
[NEW ALGORITHM] Merge k sorted lists 

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1857]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Merge k sorted lists```  

### About:  
You are given an array of k linked-lists lists, each linked-list is sorted in ascending order.

Merge all the linked-lists into one sorted linked-list and return it.

 
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

Please assign me this issue 
@pankaj-bind

**Comment by Aachallll** [comment]
@Dipanita45 please assign me this issue.

**Comment by Aachallll** [comment]
please assign me this 
@pankaj-bind

**Comment by Dipanita45** [comment]
Please assign me this issue
@pankaj-bind

**Comment by pankaj-bind** [comment]
Raise your PR before 11:30PM otherwise, it will not be considered in GSSOC-ext.
