### ISSUE TITLE
[NEW ALGORITHM] Rotated Lists

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#1863]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Rotated Lists```  

### About:  
Given the head of a linked list, rotate the list to the right by k places.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

Please assign me the issue 
@pankaj-bind

**Comment by gurramtejaswini** [comment]
Hello @Dipanita45, 
I would like to work on this issue, could you please assign this to me. It will be very helpful for my academics.
