### ISSUE TITLE
[NEW ALGORITHM] Energy-Aware Scheduling:

### ISSUE THREAD

**Issue by khwaishchawla** [AlgoGenesis/C#1868]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Energy-Aware Scheduling:

### About:  
Propose a new algorithm to be added to the repository
 Focuses on optimizing CPU scheduling to minimize power consumption without significantly sacrificing performance. Often used in mobile devices and data centers to reduce energy costs.

**Comment by nikhilritgithub** [comment]
Is this solved.? if not then please assign it to me
