### ISSUE TITLE
[NEW ALGORITHM] Prim’s Algorithm for Minimum Spanning Tree (MST)

### ISSUE THREAD

**Issue by ParasY1724** [AlgoGenesis/C#188]
## Description:

Addition of Graph Algo : **Prim’s Algorithm for Minimum Spanning Tree (MST)**

Prim's Algorithm is a greedy algorithm that is used to find the minimum spanning tree from a graph. Prim's algorithm finds the subset of edges that includes every vertex of the graph such that the sum of the weights of the edges can be minimized.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by ParasY1724** [comment]
Please assign this task to me under gssoc-ext

**Comment by Supraja-Gao** [comment]
Please assign this issue to me. I would like to work on this issue.

**Comment by shuvojitss** [comment]
I am a Contributor in GSSoC-ext. Please assign it to me
