### ISSUE TITLE
Addition of Stack And Queues Data Structures

### ISSUE THREAD

**Issue by DBasu2610** [AlgoGenesis/C#19]
I would like to contribute to this project by implementing Stack and Queue data structures. These are fundamental data structures that are often used in various algorithms and real-world applications, and I'd love to enhance the project with them.

Please let me know if this is something you'd be interested in adding, and I can get started right away!

Looking forward to your feedback!

**Comment by pankaj-bind** [comment]
mention name of algorithm you want to contribute in Stack and Queue

**Comment by DBasu2610** [comment]
I would like to add Stack, Linear Queue, Circular Queue and DEqueue  in a menu driven manner, to show the proper ways how stack works in a LIFO manner and queue in FIFO

**Comment by pankaj-bind** [comment]
@DBasu2610 Go for it.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by pankaj-bind** [comment]
@AnujSaha0111 you can start working

**Comment by AnujSaha0111** [comment]
Done it in #298
