### ISSUE TITLE
Addition of Common Linked List Algorithms

### ISSUE THREAD

**Issue by Upendra48** [AlgoGenesis/C#20]
I would like to contribute by implementing the following algorithms for singly/doubly linked lists:
1. Insertion: At the start, at the end, and at a specific position.
2. Deletion: Remove nodes by value or by position.
3. Reversal of the linked list.
4. Finding the middle node in a linked list.
5. Detecting cycles in the linked list using Floyd’s cycle-finding algorithm.

**Comment by Upendra48** [comment]
Looking forward for your approval and assignment so I could start working on it.
(Please add gssoc-ext 24 and hacktoberfest label)

**Comment by simmi-verma** [comment]
I’m excited to submit my first pull request as a new contributor in GSSoC-extd 24 . I’d love your feedback and guidance as I get started.

**Comment by pankaj-bind** [comment]
@simmi-verma you can start

**Comment by Upendra48** [comment]
@pankaj-bind I am currently working on it but you unassigned me

**Comment by simmi-verma** [comment]
Hii, I would like to be reassigned to this issue . Please let me know if that's

**Comment by Upendra48** [comment]
@simmi-verma I am working on this issue and already created a pull request for it. 

@simmi-verma  I would like to be reassigned to this issue.
