### ISSUE TITLE
[NEW ALGORITHM] Add new Linked list algorithms 

### ISSUE THREAD

**Issue by SurajSG23** [AlgoGenesis/C#202]
Hey, I noticed in the linked list file only singly linked list is there, i would like to add few more like Doubly linked list , Circular linked list and others...

![Screenshot 2024-10-05 211021](https://github.com/user-attachments/assets/a1217896-4791-4168-afdf-30164a5c0443)

I'll make sure there is a corresponding readme file for each of the new linked list.

please label me under gssoc and hacktober fest. THANK YOU

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
