### ISSUE TITLE
[NEW ALGORITHM] Sparse matrix Algorithms 

### ISSUE THREAD

**Issue by Salini-sat** [AlgoGenesis/C#207]
## Description:
I want to add sparse matrix operations like creation of sparse matrix , it's representation and it's operations such as, addition and multiplication of two sparse matrixes .

## Checklist:
- I'm a Contributor in GSSoC-ext
- I Want to work on it

## Additional Information:

A matrix is a two-dimensional data object made of m rows and n columns, therefore having total m x n values. If most of the elements of the matrix have 0 value, then it is called a sparse matrix.

Why to use Sparse Matrix instead of simple matrix ?

Storage: There are lesser non-zero elements than zeros and thus lesser memory can be used to store only those elements.
Computing time: Computing time can be saved by logically designing a data structure traversing only non-zero elements..

**Comment by Salini-sat** [comment]
@pankaj-bind kindly please assign me this

**Comment by Salini-sat** [comment]
@pankaj-bind please assign me this

**Comment by pankaj-bind** [comment]
@Salini-sat you can start
