### ISSUE TITLE
Add Caesar Cipher Algorithm

### ISSUE THREAD

**Issue by mehul-m-prajapati** [AlgoGenesis/C#208]
## Description:
The Caesar cipher is one of the simplest and most well-known encryption techniques. It is a type of substitution cipher where each letter in the plaintext is shifted by a fixed number of places down or up the alphabet. Named after Julius Caesar, who reportedly used it to communicate with his generals, this cipher is easy to understand and implement, making it popular for educational purposes.

**Comment by Koushik-Biswas** [comment]
Hi, I'd like to work on this issue. Please assign it to me.

**Comment by mehul-m-prajapati** [comment]
> Hi, I'd like to work on this issue. Please assign it to me.

You need to open you own issue and work on it. I have opened this one, So, I will open PR
