### ISSUE TITLE
Adding Divide and Conquer

### ISSUE THREAD

**Issue by tanya-soni-git** [AlgoGenesis/C#21]
I would like to contribute to this project by adding Divide and conquer approach in Merge Sort, Quick Sort.

I am interested in contributing to your project, and I can start right away!

Looking forward to your feedback!

**Comment by ARYAN-ANSUMAN-SAHOO** [comment]
@pankaj-bind I would like to contribute to this issue

**Comment by pankaj-bind** [comment]
@tanya-soni-git create a folder Divide and conquer and add this Merge Sort, Quick Sort files
