### ISSUE TITLE
Some more common recursion problems

### ISSUE THREAD

**Issue by Adarsh-Chaubey03** [AlgoGenesis/C#219]
I would like to add some more common recursion problems like:
1. Permutations of a String  
2. N-Queens Problem  
3. Merge Sort  
4. Reverse a Linked List  
5. Generate All Balanced Parentheses
 @pankaj-bind please assign me this task.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by Adarsh-Chaubey03** [comment]
Please assign me the task @pankaj-bind
