### ISSUE TITLE
Adding more Dynamic Programming problems

### ISSUE THREAD

**Issue by ramana2074** [AlgoGenesis/C#22]
I would like to contribute some Dynamic programming problems .To understand dynamic programming we can use these problems:
Longest Common Subsequence (LCS)
Matrix Chain Multiplication
Cutting a Rod

**Comment by pankaj-bind** [comment]
@ramana2074 go for it

**Comment by poojapoojanr** [comment]
@pankaj-bind  hello Pankaj, I would like to contribute some more dynamic programming problems like computing binomial coefficient and MFKnapsack. 
So can you please assign me to this.

**Comment by simmi-verma** [comment]
I would like to work on this .Please assign to me.

**Comment by ramana2074** [comment]
could you please add the label hacktober fest label.

**Comment by pankaj-bind** [comment]
@poojapoojanr you can start
