### ISSUE TITLE
[NEW ALGORITHM] Reverse-Delete Algorithm

### ISSUE THREAD

**Issue by samyak-aditya** [AlgoGenesis/C#221]
## Description:
Please provide a detailed description of the algorithm you are proposing.

- **Approach:** Modified version of Kruskal’s algorithm.
- **Process:**
  1. Start with the original graph and remove edges in decreasing order of their weight.
  2. For each edge removed, check if its removal disconnects the graph. If it does, add it back to the MST.
  3. Continue until all edges have been processed.
- **Complexity:** \( O(E \log E) \) due to the union-find structure for connectivity checks.

These algorithms provide a foundation for solving various problems in graph theory and network design. Each has its own advantages and is suitable for different types of graphs and applications.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@samyak-aditya you can start development

**Comment by pankaj-bind** [comment]
no response

**Comment by samyak-aditya** [comment]
Hey @pankaj-bind I am working on it
