### ISSUE TITLE
[NEW ALGORITHM] Randomized Spanning Tree Algorithm (RST)

### ISSUE THREAD

**Issue by shubhagarwal1** [AlgoGenesis/C#222]
This algorithm generates a random spanning tree of a graph by using random choices during the construction of the tree. It can be implemented using random walks or via Wilson's algorithm, which utilizes loop-erased random walks. Randomized spanning trees are useful in applications where uniformity or randomness is a requirement, such as in network design for robustness against failures.

@govindumeesala Please assign this to me with level tag

**Comment by pankaj-bind** [comment]
@shubhagarwal1 you can start working on it.
