### ISSUE TITLE
[NEW ALGORITHM] Rotated Sorted Array

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#225]
## Description:
Search the item after rotating in the array

-  Contributor in GSSoC-ext
-  Want to work on it

**Comment by Dipanita45** [comment]
Please assign me

**Comment by pankaj-bind** [comment]
@Dipanita45 you're assigned.

**Comment by Dipanita45** [comment]
Thank for the chance. I will start work as early as possible 😃

**Comment by Dipanita45** [comment]
I have completed the algorithm program and please review my pull request
