### ISSUE TITLE
[NEW ALGORITHM] Selection sort

### ISSUE THREAD

**Issue by Rohinipilla** [AlgoGenesis/C#229]
## Description:
Selection Sort is a comparison-based sorting algorithm. It sorts an array by repeatedly selecting the smallest (or largest) element from the unsorted portion and swapping it with the first unsorted element. This process continues until the entire array is sorted.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
- [x] hactoberfest

## Additional Information:
Time Complexity: O(n2) 
Auxiliary Space: O(1)
Number of Swaps: Involves fewer swaps compared to bubble sort, as each element is swapped at most once.

**Comment by developer-krish** [comment]
Hello maintainers,
I would like to work on the issue related to implementing the Selection Sort algorithm. I have prior experience in sorting algorithms and will ensure that the code is optimized, follows the project's guidelines, and includes proper documentation. Please assign this issue to me under GSSoC. I will also make sure to write test cases to verify the implementation. Looking forward to contributing to the project.

Thank you!
