### ISSUE TITLE
Addition of Trees Algos.

### ISSUE THREAD

**Issue by Shariq2003** [AlgoGenesis/C#23]
There is no such folder for trees related algos.
Please assign this to me.

@pankaj-bind

**Comment by Salini-sat** [comment]
I would like to contribute by adding tree algorithms (ie used for making programmes more faster).

Kindly assign me this issue
@pankaj-bind

**Comment by pankaj-bind** [comment]
@Shariq2003, complete previous issues first.

**Comment by Salini-sat** [comment]
@pankaj-bind I requested a PR for this but you declined it . Kindly say is there any mistake from my end or any miscommunication .
