### ISSUE TITLE
[NEW ALGORITHM] : Want to add N-Queen problem under recursion.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [AlgoGenesis/C#240]
## Description:
The N-Queen problem is a classic example of backtracking. The objective is to place N queens on an N×N chessboard in such a way that no two queens threaten each other. This means that no two queens can be in the same row, column, or diagonal.

The algorithm uses recursion and backtracking to explore all possible ways to place the queens on the board. If a placement leads to a conflict, the algorithm backtracks and tries a different configuration until a solution is found.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:

- Input: A single integer N, representing the size of the board and the number of queens.
- Output: All possible configurations to place N queens safely on the board.
- Approach: Recursive backtracking.

**Comment by shuvojitss** [comment]
I am a Contributor in GSSoC-ext. PLease assign me this issue.
