### ISSUE TITLE
[NEW ALGORITHM] Adding Basic And Standard Bit manipulation Algorithms

### ISSUE THREAD

**Issue by sumankr15** [AlgoGenesis/C#241]
##Description
I propose to add a new section on bit manipulation to the repository. This section will cover the basics of bit manipulation, include standard algorithms, and provide comprehensive documentation to aid understanding and usage.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
- [x] I want to add a new section
   
  ## Additional Information
  Plan for Bit Manipulation Section:- 

  1. **Introduction to Bit Manipulation**
  Explanation of bits and binary representation
  Common bitwise operators (AND, OR, XOR, NOT, shifts)

  2. **Standard Algorithms**
   Counting the number of set bits (Hamming weight)
   Finding the only non-repeating element in an array where every other element repeats twice
  Detecting if a number is a power of two
  Swapping two numbers without using a temporary variable

  I am eager to take on this task and am confident in my ability to meet and exceed expectations.

**Comment by sumankr15** [comment]
Is this task assigned to me?
@pankaj-bind

**Comment by pankaj-bind** [comment]
@sumankr15 you can start working on it

**Comment by pankaj-bind** [comment]
no response
