### ISSUE TITLE
[NEW ALGORITHM]  Problems on Patterns

### ISSUE THREAD

**Issue by HeartTick** [AlgoGenesis/C#242]
## Description:
 I would like to add a section of Printing of patterns Which are the basics to understand the loops concept.

## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
I will try to explain atleast add 4 to 5 patterns form basic to addvance.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by HeartTick** [comment]
can you assign the level tag as well to this issue.
