### ISSUE TITLE
[NEW ALGORITHM] would like to add mathematical algorithm

### ISSUE THREAD

**Issue by icemberg** [AlgoGenesis/C#247]
## Description:
I would add an algorithm for catalan numbers

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Contributor in Hacktoberfest
- [ ] Want to work on it

**Comment by ShudarsanRegmi** [comment]
Shall I add optimziation algorithms in mathematics such as:
Simplex Methods, Gradient Descent, Power Method, etc.?

And, where is the discussion section for this repo? I want to clarify some doubts. 
Group?discord?
