### ISSUE TITLE
Floyd's Cycle Detection

### ISSUE THREAD

**Issue by Rajata-Hegde** [AlgoGenesis/C#251]
## Description:
Floyd’s Cycle Detection Algorithm, also known as the Tortoise and Hare Algorithm, is a two-pointer technique used to detect whether a linked list contains a cycle (loop). 

## Checklist:

 1.Contributor in GSSoC-ext

 2.Want to work on it

## Additional Information:
1. Cycle Detection in a Linked List
Problem: Given a singly linked list, determine if it contains a cycle (loop).
Example: In a linked list with elements like 1 -> 2 -> 3 -> 4 -> 5 -> 3, detect that node 3 is where the cycle starts.

**Comment by pankaj-bind** [comment]
@Rajata-Hegde you are assigned.
