### ISSUE TITLE
Topological-Sorting 

### ISSUE THREAD

**Issue by sammy0318** [AlgoGenesis/C#255]
Topological Sorting is an algorithm for ordering the vertices of a directed acyclic graph (DAG) such that for every directed edge u → v, vertex u comes before vertex v in the ordering. Topological sorting is only possible for Directed Acyclic Graphs (DAGs), as cyclic graphs do not have a linear ordering.

It is used in scenarios like task scheduling, course prerequisites, and other dependency resolution problems where certain tasks need to be completed before others.

![1_uMg_ojFXts2WZSjcZe4oRQ](https://github.com/user-attachments/assets/236ffdf7-8d8c-4e0c-b177-63212acf8ff3)
 

@sanjay-kv ,@pankaj-bind , please accept my pull request .

**Comment by Lokesh11868** [comment]
Could you assign me this issue?
