### ISSUE TITLE
Add Tug of War Problem to Backtracking Folder

### ISSUE THREAD

**Issue by 770navyasharma** [AlgoGenesis/C#258]
## Description:
Hi, I would like to contribute the Tug of War Problem algorithm to the Backtracking folder. The Tug of War problem involves partitioning a set into two subsets such that the difference between their sums is minimized.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Labels Requested:
GSSoC (GirlScript Summer of Code)
Hacktoberfest
Enhancement
Backtracking (if available)
This algorithm would be a valuable addition to the collection of backtracking problems. Looking forward to contributing!

**Comment by pankaj-bind** [comment]
@770navyasharma you can start working on it.
