### ISSUE TITLE
Adding right labels. GSSoC.

### ISSUE THREAD

**Issue by smog-root** [AlgoGenesis/C#261]
You need to add level labels for GSSoC-ext.

- There are 3 levels and with no space. every letter is in small case.
- Add hacktoberfest-accepted.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
and add the gssoc-ext label

**Comment by smog-root** [comment]
@AnujSaha0111 there nothing you could do about it. The admin needs to change it!
