### ISSUE TITLE
[NEW ALGORITHM] Selection sort

### ISSUE THREAD

**Issue by tanya-soni-git** [AlgoGenesis/C#266]
## Description:
Basic type of sorting Selection sort is missiing in Sorting folder

## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by SaswatikaDas** [comment]
I am a Contributor in GSSoC-ext and I want to work on it.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
