### ISSUE TITLE
 Kadan's Algorithm

### ISSUE THREAD

**Issue by Bhumika-00** [AlgoGenesis/C#270]
## Description:
I am proposing Kadan's Algorithm that is used to calculate the sub  arrays in an array.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Kadane's Algorithm is a well-known method for finding the maximum sum of a contiguous subarray within a one-dimensional array of numbers. It efficiently computes the result in linear time, making it very effective for large datasets.

How It Works:
Initialization:

Start with two variables:
max_so_far to keep track of the maximum sum encountered so far (initialize it to a very small number, or the first element of the array).
max_ending_here to store the maximum sum of the subarray that ends at the current position (initialize it to 0).
Iterate through the array:

For each element in the array:
Update max_ending_here by adding the current element.
If max_ending_here exceeds max_so_far, update max_so_far.
If max_ending_here drops below 0, reset it to 0 (since starting a new subarray could yield a higher sum).
Final Result:

After processing all elements, max_so_far contains the maximum sum of any contiguous subarray..

**Comment by Bhumika-00** [comment]
Can you please tell me when will be the issue assigned to me

**Comment by pankaj-bind** [comment]
@Bhumika-00 you can start working on it.

**Comment by pankaj-bind** [comment]
@Bhumika-00 create new issue when you complete this one, after that when you raise PR for this create another issue and mention it’s no. in your PR.
There is to much spam issue that’s why I’m remove those who are creating more issues.

**Comment by Bhumika-00** [comment]
Okay thank you for the clarification

**Comment by Bhumika-00** [comment]
I have created the pull request for the same can you please review it ASAP
and assign the other problems to me.

**Comment by Bhumika-00** [comment]
Now can you assign me 271 as it was created by me only
