### ISSUE TITLE
Time and Space Algorithm

### ISSUE THREAD

**Issue by Bhumika-00** [AlgoGenesis/C#272]
## Description:
I  want to add Space and Time Complexity as it contribute an essential role in DSA.
## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
Time Complexity
Time complexity measures the amount of time an algorithm takes to complete as a function of the input size. It’s expressed using Big O notation, which describes the worst-case scenario. Common complexities include:

O(1): Constant time
O(n): Linear time
O(n²): Quadratic time
O(log n): Logarithmic time
Space Complexity
Space complexity measures the amount of memory an algorithm uses relative to the input size. It includes:

Auxiliary Space: Extra space needed beyond the input data.
Common complexities include:
O(1): Constant space
O(n): Linear space

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
