### ISSUE TITLE
Circular and doubly linked list

### ISSUE THREAD

**Issue by Bhumika-00** [AlgoGenesis/C#273]
## Description:
Circular Linked List
Structure: The last node points back to the first node, forming a loop.

Doubly Linked List
Structure: Each node has pointers to both the next and previous nodes.

## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
Types:
Singly Circular: Each node points to the next.
Doubly Circular: Each node points to both the next and previous nodes.
Use Cases: Suitable for applications requiring circular traversal, like round-robin scheduling.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by manya346** [comment]
Hey! I want to work on this can you please assign it to me?
