### ISSUE TITLE
Linked List

### ISSUE THREAD

**Issue by Bhumika-00** [AlgoGenesis/C#274]
## Description:
Reverse of a linked list.
calculation of mid node.
## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

## Affected Algorithm:
Mention which algorithm you want to update and the specific directory where you want to change.

## Additional Information:

Reversing a linked list involves changing the direction of the pointers in the list so that the first node becomes the last, and the last node becomes the first.
To find the middle node of a linked list, you can use a two-pointer technique, commonly referred to as the "Tortoise and Hare" approach.

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by manya346** [comment]
Hey! I want to work on this, please assign it to me
