### ISSUE TITLE
[NEW ALGORITHM] Adding Strassen Algorithm for Matrix Multiplication(Divide and Conquer)

### ISSUE THREAD

**Issue by ahinagangopadhyay** [AlgoGenesis/C#275]
## Description:
Strassen Algorithm is a divide and conquer algorithm which performs matrix multiplication using only 7 recursive multiplications and reduces the time complexity.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
- [x]Hacktoberfest Contributor

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by ahinagangopadhyay** [comment]
I wanted to work on this issue.Please assign me this issue for GSSOC Extended and Hacktoberfest
