### ISSUE TITLE
[NEW ALGORITHM] Want to add Painting-fence algorithm in dp dolder

### ISSUE THREAD

**Issue by Manish5043** [AlgoGenesis/C#279]
## Description:

The Painting Fence algorithm solves the problem of finding the number of ways to paint a fence with `n` posts using `k` colors, such that no more than two adjacent posts have the same color. It uses dynamic programming to calculate combinations based on two cases: when the current post has the same color as the previous one, and when it has a different color. The time complexity is O(n).
## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it
- [ ] add hactoberfest label also

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by SaswatikaDas** [comment]
I am a Contributor in GSSoC-ext and I believe I would be able to solve this.
Please assign this to me, I would like to work on it.

**Comment by Manish5043** [comment]
@pankaj-bind kindly assign me

**Comment by pankaj-bind** [comment]
@Manish5043 assigned

**Comment by pankaj-bind** [comment]
no response

**Comment by Manish5043** [comment]
hey i am facing  an issue will resolve it and quickly create a new pull request
