### ISSUE TITLE
Adding Jump Search algorithm

### ISSUE THREAD

**Issue by mehul-m-prajapati** [AlgoGenesis/C#28]
## Description:
Like [Binary Search](https://www.geeksforgeeks.org/binary-search/), Jump Search is a searching algorithm for sorted arrays. The basic idea is to check fewer elements (than [linear search](https://www.geeksforgeeks.org/analysis-of-algorithms-set-2-asymptotic-analysis/)) by jumping ahead by fixed steps or skipping some elements in place of searching all elements.

@pankaj-bind : Please assign it to me.

**Comment by pankaj-bind** [comment]
you can start
