### ISSUE TITLE
[NEW ALGORITHM] Want to add Longest Arithmetic progression problem in dp folder

### ISSUE THREAD

**Issue by Manish5043** [AlgoGenesis/C#281]
## Description:
The Longest Arithmetic Progression (LAP) problem involves finding the length of the longest subsequence in an array that forms an arithmetic progression. An arithmetic progression has a constant difference between consecutive terms. Efficient solutions typically use dynamic programming or hashing to achieve optimal results.

## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by harish08102004** [comment]
Hey @Manish5043 I can work on it.

**Comment by Manish5043** [comment]
@pankaj-bind kindly assign me
