### ISSUE TITLE
[NEW ALGORITHM] Implementation of 10 DP Problems

### ISSUE THREAD

**Issue by rudrapratap63** [AlgoGenesis/C#287]
## Description:
I would like to implement following 10 DP Problems :- 
1. Longest Increasing Subsequence (LIS)
2. Edit Distance (Levenshtein Distance)
3. Partition Equal Subset Sum
4. Subset Sum Problem
5. Rod Cutting Problem
6. House Robber Problem
7. Egg Dropping Problem
8. Palindromic Substrings
9. Maximum Subarray Problem (Kadane’s Algorithm)
10. Word Break 

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Please add the `hacktoberfest-accepted `and `level3 `labels to it. If you want to suggest any other algorithms related to DP or any other category, feel free to let me know. However, please label this as `level3`.

**Comment by rudrapratap63** [comment]
@pankaj-bind , can you please assign this issue to me under the Level 3 or Level 2 label?

**Comment by rudrapratap63** [comment]
@sanjay-kv and @pankaj-bind Please add level label on this issue

**Comment by pankaj-bind** [comment]
@rudrapratap63 assigned
