### ISSUE TITLE
[NEW ALGORITHM] Bloom Filter

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [AlgoGenesis/C#295]
## Description:
 A simple, space-efficient probabilistic data structure for checking if an element is in a set.
## Checklist:
- [X] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
hashing related algorithm

**Comment by Lokesh11868** [comment]
could you please assign me this issue?

**Comment by pankaj-bind** [comment]
@Lokesh11868 try this

**Comment by Mansi-Tanwar** [comment]
Hey @Lokesh11868 how to add the pull request with the issue like you did?

**Comment by Lokesh11868** [comment]
> Hello @Lokesh11868 how to add the pull request with the issue like you did?

You just need to mention #(issue number) in the description box when you create a pull request.
