### ISSUE TITLE
[NEW ALGORITHM] Euclidean Algorithm(GCD)

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [AlgoGenesis/C#296]
## Description:
A simple algorithm for finding the greatest common divisor (GCD) of two numbers using repeated division

## Checklist:
- [X] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
Maths, recursion used

**Comment by meghanakn473** [comment]
@SanikaBhalerao1345 please assign me this i want to work on it
