### ISSUE TITLE
[NEW ALGORITHM] Pascals Triangle

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [AlgoGenesis/C#297]
## Description:
An algorithm that generates Pascal’s Triangle, where each element is the sum of the two elements directly above it

## Checklist:
- [X] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
Used math, dp

**Comment by meghanakn473** [comment]
@SanikaBhalerao1345 can u assign me this issue i want to work on it

**Comment by pankaj-bind** [comment]
@meghanakn473 Do you want to try?

**Comment by meghanakn473** [comment]
Sure

**Comment by meghanakn473** [comment]
@pankaj-bind , done !! Please check it out
