### ISSUE TITLE
Additing Hashing Techniques

### ISSUE THREAD

**Issue by Salini-sat** [AlgoGenesis/C#30]
I would like to add hashing techniches to resolve collisions , quadratic probing and double hashing techniques also. It would make it more effective as they are important part in programming.

- I am a Contributor in GSSoC-ext
- I Want to work on it

**Comment by Salini-sat** [comment]
Please @pankaj-bind kindly assign me this issue

**Comment by simmi-verma** [comment]
I am participating in gssoc-ext for the first time. I would like to work on this .Please assign to me.

**Comment by pankaj-bind** [comment]
@Salini-sat you can start

**Comment by Salini-sat** [comment]
I have added PR for this . Please check @pankaj-bind
