### ISSUE TITLE
[NEW ALGORITHM] Fermats little algoritm for modulo multiplicative inverse

### ISSUE THREAD

**Issue by kRajoria121** [AlgoGenesis/C#303]
## Description:
Please provide a detailed description of the algorithm you are proposing.

## Checklist:
-  Contributor in GSSoC-ext
- Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by Lokesh11868** [comment]
I would like to work on this, could you please assign me this issue?

**Comment by kRajoria121** [comment]
check my PR request
