### ISSUE TITLE
Knapsack algorithm

### ISSUE THREAD

**Issue by sammy0318** [AlgoGenesis/C#305]
The Knapsack Problem is a classic optimization problem where the goal is to select items with given weights and values to maximize the total value without exceeding a given capacity.

Problem Description
You have a knapsack with a fixed weight capacity, and you are given a set of items, each with a weight and value. Your task is to determine the number of each item to include in the knapsack so that the total weight does not exceed the capacity and the total value is maximized.

Time Complexity
The time complexity of the 0/1 knapsack problem using dynamic programming is O(n * W), where:
n is the number of items.
W is the capacity of the knapsack.

@pankaj-bind Please accept my PR #304 and provide suggestions.
Thank You.

**Comment by Lokesh11868** [comment]
Can you please assign this issue to me? I want to work on it.
