### ISSUE TITLE
[NEW ALGORITHM]  I would like to enhance String Algorithms by adding the following new Algorithms i.e. Floyd's Tortoise and Hare Algorithm (Cycle Detection), Suffix Array Construction, Burnside's Lemma (Counting Symmetries)

### ISSUE THREAD

**Issue by amanver45** [AlgoGenesis/C#306]
## Description:
1.Floyd's Tortoise and Hare Algorithm (Cycle Detection) :This algorithm is used to detect cycles in a linked list or find repeated elements in sequences. It's also known as the "Tortoise and Hare" algorithm and operates in O(n) time with O(1) space.
2.Suffix Array Construction
A Suffix Array is an array of all suffixes of a string, sorted in lexicographical order. It can be used for pattern matching, longest common prefix, etc.
3.Burnside's Lemma (Counting Symmetries)
Burnside's Lemma is used in group theory to count the number of distinct objects under symmetry operations. This is particularly useful in combinatorics for counting colorings, patterns, etc.
## Checklist:

- [ ☑️] Contributor in GSSoC-ext
- [ ☑️] Want to work on it

**Comment by pankaj-bind** [comment]
mention only one
