### ISSUE TITLE
Adding  some new algorithm in sorting repo

### ISSUE THREAD

**Issue by Ashish001sing** [AlgoGenesis/C#31]
Bucket sort, selection sort, merge sort so you can please assign me this task and add it gsoc ext and level 2 issue

**Comment by pankaj-bind** [comment]
Duplicate, #13

**Comment by Ashish001sing** [comment]
But sir there is no such algo in your sorting folder

**Comment by pankaj-bind** [comment]
@Ashish001sing I have already assigned someone on such algorithm, and he/she might be working on it, you can find other unique algorithms and create an issue
