### ISSUE TITLE
Addition of more algorithms to String Algorithms

### ISSUE THREAD

**Issue by pratheekv39** [AlgoGenesis/C#32]
## Description:
I want to add more useful algorithms in String Algorithms . They are:
1)Rabin-Karp Algorithm
2)Aho-Corasick Algorithm
3)Z Algorithm
4)Levenshtein Distance Algorithm
5)Suffix Array Algorithm

## Checklist:
- [ ✓] Contributor in GSSoC-ext
- [ ✓] Want to work on it

## Additional Information:
1)Rabin-Karp Algorithm: Uses hashing to find patterns in a text, efficient for multiple pattern searches.
2)Aho-Corasick Algorithm: Builds a trie and uses a failure function for multi-pattern string search.
3)Z Algorithm: Constructs a Z-array to efficiently find pattern matches in a string.
4)Levenshtein Distance Algorithm: Computes the minimum number of edits (insertions, deletions, substitutions) to transform one string into another.
5)Suffix Array Algorithm: Constructs an array of suffixes to efficiently solve various string problems like pattern matching.

I will also add suitable comments for the code and add README.md for all of them. Kindly , assign this issue to me . Thanks

**Comment by ARYAN-ANSUMAN-SAHOO** [comment]
@pratheekv39 please assign me this issue.I want to contribute

**Comment by pratheekv39** [comment]
@ARYAN-ANSUMAN-SAHOO Thanks for your reply! However, I believe there’s been some confusion. I have already implemented and merged the Boyer-Moore Algorithm in the Strings Algorithms section. I’m looking to continue contributing in this area, so it would be great if you could add your own issue for any unrelated algorithms or tasks. I’m eager to stay involved in this project as I’m getting a good grasp of it!

Thanks again for your understanding!

**Comment by pankaj-bind** [comment]
@pratheekv39  you can start
