### ISSUE TITLE
Application on stack

### ISSUE THREAD

**Issue by Salini-sat** [AlgoGenesis/C#339]
## Description:
I want to add various applications on stack like
 -reversal of string
-implement two stacks in an array
(using method 1 divide the space in two halves
method 2 A space efficient implementation)

## Checklist:
- [ ]I'm a Contributor in GSSoC-ext
- [ ] I Want to work on it

## Additional Information:
Function calls: Stacks are used to keep track of the return addresses of function calls, allowing the program to return to the correct location after a function has finished executing.
Recursion: Stacks are used to store the local variables and return addresses of recursive function calls, allowing the program to keep track of the current state of the recursion.

**Comment by pankaj-bind** [comment]
not planned
