### ISSUE TITLE
[NEW ALGORITHM] Check whether a number is odd or even using bit manipulation

### ISSUE THREAD

**Issue by saiprasanna56** [AlgoGenesis/C#343]
## Description:
Please provide a detailed description of the algorithm you are proposing.
Using bit manipulation we can check whether a number is odd or even

## Checklist:
- [ X] Contributor in GSSoC-ext
- [ X] Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by Tanisha-Verma-16** [comment]
Please assign this issue to me.
