### ISSUE TITLE
[ARRAY DATA STRUCTURE] 

### ISSUE THREAD

**Issue by Ashish001sing** [AlgoGenesis/C#36]
## Description:
I want to add some array  algorithm  two pointer array and so on 

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Ashish001sing** [comment]
Sir can you assign me this task

**Comment by sheetalchaurasia21** [comment]
@pankaj-bind Sir please assign this task to me
