### ISSUE TITLE
[NEW ALGORITHM] Sorting algorithms

### ISSUE THREAD

**Issue by ananyakaligal** [AlgoGenesis/C#37]
I would like to add the following standard sorting algorithms to enhance the project:

Quick Sort
Merge Sort
Insertion Sort
Selection Sort'

(Please add gssoc-ext 24 and hacktoberfest label) -(if assigned)

**Comment by ash-k121** [comment]
Please assign this issue to me
Name-Ashmeet Kaur (under GSSOC -EXT 24)

**Comment by chmp0940** [comment]
i would like to work on it pls assign it to me  .

**Comment by pankaj-bind** [comment]
@ananyakaligal,
Do not raise a PR until I assign you, in you PR readme files are not written properly.

**Comment by pankaj-bind** [comment]
Now you can start

**Comment by pankaj-bind** [comment]
completed
