### ISSUE TITLE
[NEW ALGORITHM] Trapping Rainwater

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#383]
## Description:
Return how much water it can trap after raining.

## Checklist:
- [yes ] Contributor in GSSoC-ext
- [ yes] Want to work on it

Please assign me  and assigned the labels

**Comment by Dipanita45** [comment]
Please assign to me so that i can start working

**Comment by pankaj-bind** [comment]
@Dipanita45 you can start

**Comment by Dipanita45** [comment]
Okay thank you

**Comment by Dipanita45** [comment]
Please also assign me #676 sir
