### ISSUE TITLE
[NEW ALGORITHM] Set matrix zeroes

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#384]
## Description:
1. Given m*n integer matrix
2. if an element is 0, set the entire rows and columns to 0

## Checklist:
- [yes  ] Contributor in GSSoC-ext
- [ yes] Want to work on it

**Comment by SravikaPadakanti** [comment]
@Dipanita45 maam , I know CPP and iam now learning DSA , I can fix this.
