### ISSUE TITLE
Inserting the node to the left of the node whose key value is given using doubly linked list 

### ISSUE THREAD

**Issue by Yashaswini2205** [AlgoGenesis/C#387]
## Description:
Doubly linked list is a data structure, in which each node consists of three fields 
- to store the data
- to store of the address of the previous node
- to store the address of the next node
## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Please assign me this with suitable labels

**Comment by Bhumika-00** [comment]
Hey can you please assign me this issue.

**Comment by Yashaswini2205** [comment]
May I know why had it been closed saying completed
