### ISSUE TITLE
[NEW ALGORITHM] : Infix to prefix conversion

### ISSUE THREAD

**Issue by Mansi-Tanwar** [AlgoGenesis/C#398]
## Description:
The infix to postfix code is present in the github repo but the infix to prefix is not present. I would love to do that part if you assign the task to me.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
![image](https://github.com/user-attachments/assets/6dcb7609-3f11-4b49-be14-0d6d300aa29f)

I will add both the code and the evaluation part in readme file for Infix to Prefix Folder

**Comment by Kavish-Paraswar** [comment]
I would like to work on this under gsoc'24

**Comment by Mansi-Tanwar** [comment]
How is this a duplicate issue? I haven't seen this issue in the issues list or the pull requests list.
