### ISSUE TITLE
[NEW ALGORITHM] - Greedy algorithm

### ISSUE THREAD

**Issue by ramana2074** [AlgoGenesis/C#40]
To know more about problem solving through C programming greedy algorithm which involves making the locally optimal choice at each step, with the hope that these local choices will lead to a global optimum

Problems:
- Activity Selection Problem  
- Fractional Knapsack Problem

**Comment by pankaj-bind** [comment]
@ramana2074, do you want to work on it?

**Comment by ramana2074** [comment]
I want to work on this greedy algorithm's problems.
please assign me @pankaj-bind
