### ISSUE TITLE
[NEW ALGORITHM] Reverse a LinkedList

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#413]
## Description:
Given a linked list, the task is to reverse the linked list by changing the links between nodes.

**Input**
The program prompts the user to enter the number of nodes they wish to create in the linked list, followed by the values for each node.

**Output**
The original list and the reversed list.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
I want to work in this issue please assign me this program.

**Comment by Kavish-Paraswar** [comment]
I would like to work on this under gsoc'24

**Comment by Ambit-ion** [comment]
Hey are they not accepting PRs?
