### ISSUE TITLE
[NEW ALGORITHM] I want to Insert Interpolation Search Algorithm

### ISSUE THREAD

**Issue by PrAyAg9** [AlgoGenesis/C#421]
## Description:
The Interpolation Search is an improvement over Binary Search for instances, where the values in a sorted array are uniformly distributed. Interpolation constructs new data points within the range of a discrete set of known data points

## Checklist:
- [✔ ] Contributor in GSSoC-ext
- [ ✔] Want to work on it

## Additional Information:
Time Complexity: O(log2(log2 n)) for the average case, and O(n) for the worst case 
Auxiliary Space Complexity: O(1)

**Comment by Kiran-Jadhav200** [comment]
Hey I have already completed it Please do another
