### ISSUE TITLE
[NEW ALGORITHM] I want to add Complete Circular Linked List Implementation

### ISSUE THREAD

**Issue by PrAyAg9** [AlgoGenesis/C#426]
## Description:
A circular linked list is a data structure where the last node connects back to the first, forming a loop. This structure allows for continuous traversal without any interruptions. Circular linked lists are especially helpful for tasks like scheduling and managing playlists

## Checklist:
- [✅] Contributor in GSSoC-ext
- [ ✅] Want to work on it

## Additional Information:
 In a circular linked list, there is no null pointer at the end; instead, the last node points back to the first node, creating a loop structure

**Comment by divyalakshmi0** [comment]
I am ready to work on it. Can you please assign me

**Comment by PrAyAg9** [comment]
> I am ready to work on it. Can you please assign me

I have already done it in pull request #427
