### ISSUE TITLE
Implement Machine Learning Algorithms (KNN, Linear Regression, Decision Trees)

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#434]
### Feature Request: Implement Machine Learning Algorithms (KNN, Linear Regression, Decision Trees)

**Description:**  
This issue proposes the implementation of several fundamental machine learning algorithms, including K-Nearest Neighbors (KNN), Linear Regression, and Decision Trees, in C. These algorithms will serve as educational resources for students and educators, enhancing the repository's utility.

**Proposed Implementations:**

1. **K-Nearest Neighbors (KNN):**
   - A simple classification algorithm that predicts the label of a data point based on the labels of its nearest neighbors. The implementation will include Euclidean distance calculations and a voting mechanism for label prediction.

2. **Linear Regression:**
   - A basic statistical method used for predicting a dependent variable based on one or more independent variables. This implementation will utilize the least squares method to derive the best-fit line for a dataset.

3. **Decision Trees:**
   - A decision support tool that uses a tree-like model of decisions and their possible consequences. The implementation will include constructing the tree based on feature values and classifying input data accordingly.

**Motivation:**  
Implementing these algorithms will provide practical examples of machine learning concepts, aiding in the understanding of how these algorithms work and their applications in real-world scenarios.

**Additional Notes:**
- Each implementation will include detailed documentation explaining the algorithm's functioning, use cases, and potential limitations.
- Test cases and example datasets will be provided to demonstrate the algorithms in action.

**Comment by divyalakshmi0** [comment]
Can you please assign me and label level 3 because i will enhance the machine learning algorithms asap!!!!

**Comment by ExPl0iT-29** [comment]
Hey,
Can you assign this to me, i can work on this issue.
Thankyou!
