### ISSUE TITLE
[NEW ALGORITHM] Add mathematical algorithms

### ISSUE THREAD

**Issue by icemberg** [AlgoGenesis/C#44]
## Description:
Please provide a detailed description of the algorithm you are proposing.
sieve of eratosthenes
euclidean algorithm

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Contributor in Hacktoberfest
- [x] Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by icemberg** [comment]
please assign this issue to me as i am interested in adding these algorithms.

**Comment by pankaj-bind** [comment]
@icemberg you can start now
