### ISSUE TITLE
[NEW ALGORITHM]Add 5 Dynamic Programming Algorithms

### ISSUE THREAD

**Issue by T-Fathima** [AlgoGenesis/C#445]
## Description:
I propose adding the following dynamic programming algorithms to our repository. These algorithms are fundamental for understanding dynamic programming concepts and will benefit our users in solving complex problems effectively.

1. **Fibonacci Sequence**
   - **Description**: Compute the nth Fibonacci number using dynamic programming techniques such as memoization.
   - **Justification**: This is a classic example that introduces the concept of memoization and recursion.

2. **Longest Increasing Subsequence (LIS)**
   - **Description**: Find the length of the longest increasing subsequence in a given array using dynamic programming.
   - **Justification**: This algorithm helps in understanding subsequence problems and their applications in various fields.

3. **Edit Distance**
   - **Description**: Calculate the minimum number of operations (insertions, deletions, substitutions) required to convert one string into another.
   - **Justification**: This algorithm has practical applications in text processing and spell checking.

4. **Subset Sum Problem**
   - **Description**: Given a set of integers, determine if there exists a subset that adds up to a specified sum.
   - **Justification**: This problem is a fundamental example of combinatorial optimization.

5. **Rod Cutting Problem**
   - **Description**: Maximize the profit obtained by cutting a rod into pieces of different lengths and selling them, using dynamic programming techniques.
   - **Justification**: This classic problem illustrates the optimal substructure property of dynamic programming.

## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
- Each of these algorithms has a wide range of applications and serves as a building block for more complex problems.
- I am open to discussing the specific implementations and optimizations for each algorithm.
- Resources for each algorithm can include links to relevant tutorials, papers, or existing implementations.

**Comment by pankaj-bind** [comment]
someone else already assigned
