### ISSUE TITLE
[NEW ALGORITHM] addition of more DP related problems

### ISSUE THREAD

**Issue by apoorvasj** [AlgoGenesis/C#45]
## Description:
I would like to add the following problems to the dynamic programming folder-
- House Robber
- Maximum sum of non-adjacent elements

## Checklist:
- [✔️] Contributor in GSSoC-ext
- [✔️] Want to work on it

## Additional Information:
I would like to add illustrations of how the problem can be solved as well, for easier, visual understanding. Would that be permitted?

Thankyou!

**Comment by simmi-verma** [comment]
I am participating in gssoc-ext for the first time. Could you please assign me to this task?

**Comment by pankaj-bind** [comment]
@simmi-verma you can start

**Comment by apoorvasj** [comment]
Hey, I think the second person has wrongly commented under this issue

Thanks for the assignment

**Comment by simmi-verma** [comment]
Thanks for the assignment

**Comment by apoorvasj** [comment]
Hi @pankaj-bind 
I have raised the issue and mentioned that I wish to work on this.. and this person's PR mentioned algorithms I wanted to work on. Kindly look into this as, as per GirlScript rules the assignee is supposed to work on the issue raised, not someone who comments afterwards. 
Thankyou for your consideration
