### ISSUE TITLE
CubeSort

### ISSUE THREAD

**Issue by chetanpatil0304** [AlgoGenesis/C#450]
## Description: it is an sorting algorithm
Please provide a detailed description of the algorithm you are proposing.

## Checklist:
- [yes ] Contributor in GSSoC-ext
- [yes ] Want to work on it

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.

**Comment by Ambit-ion** [comment]
**CubeSort: Overview**

CubeSort is a parallelized, cache-efficient sorting algorithm designed for large datasets and modern multi-core processors. By dividing the input into smaller segments (cubes), sorting them independently, and merging them, CubeSort reduces cache misses and improves performance in multi-threaded environments.
Key Steps:

    Partitioning: The input array is split into smaller cubes (sub-arrays).
    Sorting: Each cube is sorted individually using a simple algorithm like Insertion Sort or MergeSort.
    Merging: The sorted cubes are merged in multiple passes until the entire array is sorted.
    Parallelism: Sorting and merging phases are parallelized to utilize multiple CPU cores efficiently.

Advantages:

    Parallelism: Efficient on multi-core systems.
    Cache Efficiency: Reduces cache misses by working with small data chunks.
    Scalability: Performs well on large datasets.

CubeSort stands out for its adaptability and performance optimization, making it ideal for modern computing environments.

- [ Yes ] I am a contributor in GSSoC 24
- [  Yes ] I want to work on this
