### ISSUE TITLE
Heap Sort

### ISSUE THREAD

**Issue by Vd7905** [AlgoGenesis/C#46]
![heap](https://github.com/user-attachments/assets/0b5aabe8-0b28-4b32-b6bc-40f33e1e3973)

Algorithm Description: Heap Sort
Heap Sort is a comparison-based sorting algorithm that uses the properties of a binary heap (a specialized tree-based data structure) to sort an array. The algorithm works by building a Max-Heap (for ascending order sorting) or a Min-Heap (for descending order sorting) from the input array. Once the heap is constructed, the root element, which is the largest or smallest element in the heap, is swapped with the last element of the heap, and the heap is reduced in size by one. This process is repeated until the heap is empty, resulting in a sorted array.

Detailed Steps:
Build Max-Heap:

Treat the input array as a binary tree, where the parent at index i has children at indices 2i + 1 (left) and 2i + 2 (right).
Begin from the middle of the array (non-leaf nodes) and perform a heapify operation to ensure the parent node is larger than both its children.
Continue heapifying all parent nodes down to the root, ensuring the entire array satisfies the Max-Heap property.
Heap Sort:

After building the Max-Heap, the largest element (root) is at the beginning of the array.
Swap the root with the last element of the heap.
Reduce the size of the heap by one and heapify the root element to restore the Max-Heap property.
Repeat the process until the heap is fully sorted.
Time Complexity:
Best-case, Average-case, and Worst-case time complexity: O(n log n)
The heapify operation takes O(log n), and we perform it n times for n elements in the array.
Space Complexity:
Space complexity: O(1) (in-place sorting, no extra space needed except for the input array and a few variables)

Checklist:
[✔️] Contributor in GSSoC-ext
[✔️] Want to work on it

Additional Information:
Binary Heap: A binary heap is a complete binary tree where each node is greater than (Max-Heap) or smaller than (Min-Heap) its children.
In-place sorting: Heap sort operates in-place, meaning it uses constant extra memory beyond the input array.
Not stable: Heap sort is not a stable sorting algorithm, meaning the relative order of equal elements is not necessarily preserved.

@pankaj-bind could you assign this to me i will add this algorithm

**Comment by simmi-verma** [comment]
I’m excited to submit my first pull request as a new contributor to GSSoC. I kindly request your feedback and guidance as I start this journey.

**Comment by pankaj-bind** [comment]
Duplicate, Heap sort already there
