### ISSUE TITLE
[NEW ALGORITHM]  Operating System Scheduling Algorithm

### ISSUE THREAD

**Issue by sindhuja184** [AlgoGenesis/C#467]
## Description:
I want to add the Operating System's Scheduling Algorithms like
1. First Come First Serve
2. Shortest Job First(Preemptive and non-preemptive)
3. Priority Algorithm (Preemptive and Non-Preemptive)

Please assign this to me.

Thanks @pankaj-bind

**Comment by pankaj-bind** [comment]
not needed
