### ISSUE TITLE
Bit Manipulation

### ISSUE THREAD

**Issue by Vd7905** [AlgoGenesis/C#47]
Description:
Bit manipulation is a technique that leverages binary representations of numbers to perform operations directly on bits.
I can add the following questions/tricks of bit manipulation..

1. Check if the i-th bit is set or not
2. Check if a number is power of 2 or not(using bit manipulation)
3. Swap two numbers(using bit manipulation)

Checklist:
[✔️] Contributor in GSSoC-ext
[✔️] Want to work on it

Additional Information:

All the above algorithms have constant time and space complexity

**Comment by simmi-verma** [comment]
I’m excited to submit my first pull request as a new contributor in GSSoC ext 24. I’d love your feedback and guidance as I get started. Could you please add the gssoc-extd24 labels?

**Comment by lkksharma** [comment]
@Vd7905 I am at a contributor at GSSoC- ext '24 and would like to work on it. Kindly assign it to me.

**Comment by pankaj-bind** [comment]
@Vd7905 you can start

**Comment by pankaj-bind** [comment]
@simmi-verma try this

**Comment by simmi-verma** [comment]
Thank you

**Comment by simmi-verma** [comment]
Sir please add hacktoberfest lebel
