### ISSUE TITLE
[NEW ALGORITHM] Additoion of Rabin-Karp Algorithm in String Matching Algos.

### ISSUE THREAD

**Issue by Shariq2003** [AlgoGenesis/C#48]
## Description:
I want to add a new algorithm in string matching algorithms, which is Rabin Karp Algo.
I have also checked the code base and the present issues for this existence, but it's not.
So please assign this to me.  

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@Shariq2003 You can start now
