### ISSUE TITLE
[NEW ALGORITHM] Backtracking Algorithms Addition

### ISSUE THREAD

**Issue by Shariq2003** [AlgoGenesis/C#49]
## Description:
I have checked the codebase and found the most important and the difficult topic of DSA as absent in this repo, which is Backtracking.
So I want to add that, pleased assign this to me

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

![image](https://github.com/user-attachments/assets/fa49c3fc-9224-4103-aa1f-698380973610)

**Comment by lkksharma** [comment]
I am a contributor at GSSoC- ext '24 and would like to work on it. Kindly assign it to me.

**Comment by pankaj-bind** [comment]
@Shariq2003 you can start

**Comment by Shariq2003** [comment]
@pankaj-bind sir, mark this issue as complete
