### ISSUE TITLE
[NEW ALGORITHM] cube sort

### ISSUE THREAD

**Issue by ABHI-SHEK-001** [AlgoGenesis/C#492]
Cube sort is an algorithm that organizes data into a three-dimensional cube structure, allowing for efficient sorting and retrieval. The data is divided into smaller sub-cubes, which are sorted individually using a traditional sorting algorithm. Once sorted, these sub-cubes are merged back together into a larger cube. This method is particularly useful for multidimensional datasets, as it leverages spatial locality to improve performance. While cube sort can be complex to implement, it can provide significant advantages in specific applications, especially those involving large volumes of data with multiple dimensions, such as in data analysis and visualization.

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

**Comment by pankaj-bind** [comment]
#450
