### ISSUE TITLE
Kosaraju's Algorithm

### ISSUE THREAD

**Issue by AmanKumar1115** [AlgoGenesis/C#50]
### Kosaraju's Algorithm for Strongly Connected Components (SCCs)

Kosaraju's Algorithm is an efficient method for finding all **strongly connected components (SCCs)** in a **directed graph**. An SCC is a maximal subgraph where every pair of vertices is mutually reachable (i.e., there is a path between any two vertices in both directions).

@pankaj-bind I will add code in C with with proper explanation.

Please assign it to me under the label of gssoc-ext, hacktoberfest and required
 level .

**Comment by pankaj-bind** [comment]
@AmanKumar1115 You can start
