### ISSUE TITLE
Reversing the doubly linked list.

### ISSUE THREAD

**Issue by Rajata-Hegde** [AlgoGenesis/C#502]
### Name:  
Reverse the doubly linked list using Recursion.  

### About:  
A doubly linked list has two pointers next and previous .By using recursion I will reverse the original doubly linked list.
Thankyou 

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ 1] Contributor in GSSoC-ext
- [ 2] Want to work on it

**Comment by Kushagra614** [comment]
Want to work on it
