### ISSUE TITLE
[NEW ALGORITHM] : Infix to Prefix Conversion

### ISSUE THREAD

**Issue by Mansi-Tanwar** [AlgoGenesis/C#506]
### Name:  
```[NEW ALGORITHM] :Infix to Prefix```  

### About:  
![image](https://github.com/user-attachments/assets/eefeecab-260d-48f3-b7d3-064f50564c05)

I explored the github repo, there was code for infix to postfix. But there was neither the code present for infix to prefix nor any pull requests for this algorithm. If you assign this task to me, I would love to complete the task. Thank You.  

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Kushagra614** [comment]
Can you assign it to me?
I would like to work on it.

**Comment by Mansi-Tanwar** [comment]
@pankaj-bind please assign the task to me.

**Comment by Mansi-Tanwar** [comment]
#692
