### ISSUE TITLE
Prim's Algorithm for Minimum Spanning Tree (MST)

### ISSUE THREAD

**Issue by AmanKumar1115** [AlgoGenesis/C#52]
## Description:
Prim's Algorithm is a greedy algorithm used to find the minimum spanning tree (MST) of a connected, undirected graph. The minimum spanning tree is a subset of edges that connects all vertices in the graph with the minimum possible total edge weight, without forming any cycles.

@pankaj-bind I will add code in C with with proper explanation.

Please assign it to me under the label of gssoc-ext, hacktoberfest and required
level .

**Comment by Charul00** [comment]
can i work on this

**Comment by pankaj-bind** [comment]
@AmanKumar1115 first complete previous issue

**Comment by AmanKumar1115** [comment]
@pankaj-bind  I have completed the previous task. 
Please assign it to me under the label of gssoc-ext, hacktoberfest and required
level .

**Comment by pankaj-bind** [comment]
We have this
