### ISSUE TITLE
Adding tranpose of a matrix.

### ISSUE THREAD

**Issue by ankitasure23** [AlgoGenesis/C#524]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Transpose of a 2D array

### About:  
I want to add the transpose of a 2D array. 
The transpose of a matrix is such that the diagonal remains the same but the matrix is flipped along its diagonal.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by BURNOUTAlGO** [comment]
Assighn this task to me 

✅Want to work on it

**Comment by BURNOUTAlGO** [comment]
kindly assighn this task to me

**Comment by BURNOUTAlGO** [comment]
want to work on it
