### ISSUE TITLE
[NEW ALGORITHM] Reverse a string using stack

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#530]
### Name:  
```[NEW ALGORITHM]```  Write a program to reverse a string using stack data structure.

### About:  
Implementation of stack data structure.
### Input:
A single string of up to 100 characters, which may contain spaces and other characters.
### Output:
The reversed string.
### Time Complexity: 
O(n), where n is the length of the string. This is because each character is pushed and popped from the stack exactly once.
### Space complexity: 
O(n), where n is the length of the string, since the stack needs to store the characters temporarily.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

Additional :
Please assign me this problem. I want to work on this.

**Comment by DhayananthB** [comment]
hi please assign to me
