### ISSUE TITLE
[NEW ALGORITHM]  Adding Sorting Algorithms

### ISSUE THREAD

**Issue by aditiverma-21** [AlgoGenesis/C#54]
## Description:
Selection Sort
Selection Sort divides the array into a sorted and an unsorted region and repeatedly selects the smallest (or largest) element from the unsorted region to add to the sorted region.

Insertion Sort
Insertion Sort builds a sorted array one element at a time by repeatedly picking the next element and inserting it into the correct position.

Merge Sort
Merge Sort is a divide-and-conquer algorithm that splits the array into halves, sorts them, and then merges the sorted halves.

Quick Sort
Quick Sort is another divide-and-conquer algorithm that selects a 'pivot' element and partitions the array around the pivot, sorting the elements recursively.

**Comment by lkksharma** [comment]
I am a contributor at GSSoC- ext '24 and would like to work on it. Kindly assign it to me.
