### ISSUE TITLE
Maximum Falling Path Sum

### ISSUE THREAD

**Issue by Rahul-Morabiya** [AlgoGenesis/C#551]
### Name:  
```Maximum Falling Path Sum Algorithm```  

### About:  
We are given an N x M matrix. The task is to find the maximum falling path sum starting from any cell in the first row and ending at any cell in the last row. At every cell, we can move in the following directions:
To the bottom cell (↓) To the bottom-right cell (↘) To the bottom-left cell (↙) Your goal is to determine the maximum path sum you can obtain by following the allowed movements.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [✅] Contributor in GSSoC-ext
- [✅] Want to work on it

**Comment by susrithasabbini** [comment]
@Rahul-Morabiya I will work on it. Please assign it to me.
