### ISSUE TITLE
[NEW ALGORITHM] Add Hamming Distance Algorithm to bit manipulation

### ISSUE THREAD

**Issue by sindhuja184** [AlgoGenesis/C#556]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  

### About:  
Propose a new algorithm to be added to the repository
The [Hamming distance](https://en.wikipedia.org/wiki/Hamming_distance) between two integers is the number of positions at which the corresponding bits are different.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by palak-k5** [comment]
would like to work on it ,can you please assign it to me
