### ISSUE TITLE
[NEW ALGORITHM] Hare and Tortoise Algorithm

### ISSUE THREAD

**Issue by Bhumika-00** [AlgoGenesis/C#557]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Hare and Tortoise Algorithm``  

### About:  
The "Hare and Tortoise" algorithm, also known as Floyd's Cycle-Finding Algorithm, is a method for detecting cycles in a sequence of values, particularly in linked lists. The main idea is to use two pointers that move at different speeds: one moves slowly (the tortoise) and the other moves quickly (the hare). 

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by itznayan** [comment]
@Bhumika-00 Please assign this issue to me.

**Comment by pankaj-bind** [comment]
@Bhumika-00 You are assigned

**Comment by Bhumika-00** [comment]
Thanku so much

**Comment by Bhumika-00** [comment]
I have completed this please review

**Comment by Bhumika-00** [comment]
When will it get merged??
