### ISSUE TITLE
[NEW ALGORITHM] 

### ISSUE THREAD

**Issue by anushkaa-dubey** [AlgoGenesis/C#564]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  Heap Cascade Sort
```[NEW ALGORITHM]```  

### About:  
Propose a new algorithm to be added to the repository
A variation of Heap Sort that builds the heap in a cascading manner. Instead of building a complete heap initially, it progressively inserts elements into a binary heap, maintaining the heap property after each insertion.---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x ] Contributor in GSSoC-ext
- [ x] Want to work on it

**Comment by anushkaa-dubey** [comment]
Please assign this issue to me

**Comment by pankaj-bind** [comment]
@anushkaa-dubey you are assigned

**Comment by 2004san** [comment]
i want to work on this issue @anushkaa-dubey

**Comment by pankaj-bind** [comment]
@2004san assigned

**Comment by anushkaa-dubey** [comment]
But I already did it?

**Comment by pankaj-bind** [comment]
@anushkaa-dubey you are reassigned.
