### ISSUE TITLE
[UPDATE ALGORITHM] Delete Algorithm for binary tree.

### ISSUE THREAD

**Issue by psa21git** [AlgoGenesis/C#569]
## Description:
The Binary tree algorithm which is currently available has no delete node algorithm in it. I want to add a deleteNode algorithm in it which is a very important operation on a binary tree. 

## Checklist:
- [ [psa21git](https://github.com/psa21git) ] Yes I'm a Contributor in GSSoC-ext.
- [ [psa21git ](https://github.com/psa21git)] Yes I want to work on it.

## Affected Algorithm:
I want to update the binary tree algorithm with Delete Node algorithm. 
**This will help to complete the whole binary tree algorithm.**

## Additional Information:
![image](https://github.com/user-attachments/assets/0b5dc553-b2e2-4f8f-8397-3d0af585adea)

**Comment by SaanyaGarg5** [comment]
you can assign this issue to me..
