### ISSUE TITLE
DSA Roadmap in C Language

### ISSUE THREAD

**Issue by ananyakaligal** [AlgoGenesis/C#57]
I would like to contribute by creating a roadmap for Data Structures and Algorithms (DSA) in C language. This resource will aid in studying C while simultaneously mastering DSA concepts, providing a structured approach to learning essential techniques.

(Please add gssoc-ext 24 and hacktoberfest label) -(if assigned)

**Comment by pankaj-bind** [comment]
Currently not needed.
