### ISSUE TITLE
[NEW ALGORITHM] Prefix to postfix

### ISSUE THREAD

**Issue by Mansi07sharma** [AlgoGenesis/C#576]
### Name:  
Prefix to postfix

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by ExPl0iT-29** [comment]
Hey,
Can you assign me to this please?
Thankyou!

**Comment by SaanyaGarg5** [comment]
you can assign this issue to me..

**Comment by crackedmob** [comment]
can you assign me to this please ?
thank you
