### ISSUE TITLE
[NEW ALGORITHM] Greedy Algorithm

### ISSUE THREAD

**Issue by lkksharma** [AlgoGenesis/C#58]
## Description:
Addition of an important algorithm: Greedy Algorithm

I am a Contributor in GSSoC-ext '24 and want to work on it. Kindly assign this issue to me.

**Comment by ganashree1612** [comment]
hey I am a gssoc contribuyor
I would like to add greedy important algorithms like:
knapsack by greedy
dijkstra's shortest path algorithm
kruskals minimum spanning tree
can u please assign me this issue

**Comment by pankaj-bind** [comment]
@lkksharma You can start

**Comment by prisha-sh** [comment]
Hey I'm interested please assign me, and I'll share my proposed solution as soon as u ping me !!
