### ISSUE TITLE
[NEW ALGORITHM] prefix to infix

### ISSUE THREAD

**Issue by Mansi07sharma** [AlgoGenesis/C#582]
### Name:  
prefix to infix

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by shaswat-satyam** [comment]
Can  you assign this issue to me?

**Comment by KrishnaMohanty08** [comment]
i can work on this can you assign this to me
