### ISSUE TITLE
[NEW ALGORITHM] Hopcroft-Karp Algorithm (Maximum Bipartite Matching)

### ISSUE THREAD

**Issue by amanver45** [AlgoGenesis/C#588]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[Hopcroft-Karp Algorithm (Maximum Bipartite Matching)]```  

### About:  
Propose a new algorithm to be added to the repository
The Hopcroft-Karp algorithm finds the maximum matching in a bipartite graph. It is widely used in network flow algorithms and scheduling.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@amanver45 assined
