### ISSUE TITLE
[NEW ALGORITHM] Push-Relabel

### ISSUE THREAD

**Issue by sandeepmaddheshiya** [AlgoGenesis/C#590]
---

### Name:  
```Push-Relabel Algorithm```  

### About:  
The Push-Relabel Algorithm is an efficient method for computing the maximum flow in flow networks. It operates by maintaining a preflow and repeatedly pushing excess flow from vertices to their neighbors while adjusting vertex heights to facilitate further pushes. This algorithm excels in handling dense graphs and provides improved performance over traditional methods, making it suitable for a wide range of network optimization problems.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Contributor in hacktoberfest
- [x] Want to work on it

**Comment by sandeepmaddheshiya** [comment]
@pankaj-bind please assign to me, i'll do it asap!

**Comment by pankaj-bind** [comment]
@sandeepmaddheshiya you are assigned
