### ISSUE TITLE
[NEW ALGORITHM] Expression Tree

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#596]
### Name:  

```[NEW ALGORITHM]```  Write a program to create an expresion tree which accepts the postfix expression as input and store it as expression tree. On inorder traversal along the tree the expression gets exaluated.

---

### About:  
Implementation of Expression tree data structure.

### Input
The postfix expression.

### Output
The infix expression along with the evaluated value.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---

### Additional Information:
Please assign me this issue I want to work on this program

**Comment by pankaj-bind** [comment]
@shuvojitss you are assigned
