### ISSUE TITLE
[NEW ALGORITHM] Finding Median Using Divide and Conquer Approach

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#598]
---

### Name:  
```[NEW ALGORITHM]```  Write a C program that takes an array of integers as input and finds the median using the Divide and Conquer approach.

### About:  
Adiing new programs of Divide and conquer.

### Input:
Array of Integers

### Output:
The value of the median of the array.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---

### Additional Information:
I want to work on this issue. Please assign me this issue.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.

**Comment by shuvojitss** [comment]
> Do not create unnecessary PR until you complete the previous one.

@pankaj-bind I don't have any previous pull request left
