### ISSUE TITLE
Add OOP Concepts 

### ISSUE THREAD

**Issue by Sandigupta** [AlgoGenesis/C#602]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Add Concepts of OOP. 

### About:  
On the basis of everything else, OOP concepts are typically applied to solve complex coding problems. This will give the user a basic understanding of oops so they can solve related problems.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by SaanyaGarg5** [comment]
you can assign this issue to me..

**Comment by Sandigupta** [comment]
@SaanyaGarg5 The mentor appears to be inactive.

**Comment by Sandigupta** [comment]
okay
