### ISSUE TITLE
[NEW ALGORITHM] Multistage Graph in Dynamic Programming

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#603]
### Name:  
```[NEW ALGORITHM]```  MULTISTAGE GRAPH
You are given a directed multistage graph with n nodes. The graph is divided into multiple stages, and you need to find the shortest path from the source node (node 0) to the destination node (node n-1) while passing through intermediate stages. Each node belongs to a particular stage, and edges between nodes have associated costs. Use Dynamic Programming to solve this.

### About:  
One of the most important program in dynamic programming. 
The graph is represented as an adjacency matrix, where graph[i][j] denotes the cost of moving from node i to node j:
graph[i][j] = -1 indicates there is no edge from node i to node j.
graph[i][j] ≥ 0 represents the cost of traveling from node i to node j.

### Input:
The adjacency Cost Matrix.

### Output:
MInimum cost path and Minimum Cost.

![image (2)](https://github.com/user-attachments/assets/874b35a0-7da3-4072-aa42-aeed7f9335b8)

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

### Additionl Information:

Sir Please assign me this issue I want to work on it.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.

**Comment by shuvojitss** [comment]
@pankaj-bind Sir I don't have any pending assigned pull request not I have made any.
