### ISSUE TITLE
[NEW ALGORITHM] Min Stack

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#605]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Design a Data Structure SpecialStack that supports all the stack operations like push(), pop(), isEmpty(), isFull() and an additional operation getMin() which should return minimum element from the SpecialStack. All these operations of SpecialStack must have a time and space complexity of O(1). 

### About:  
A famous stack data structure problem that perfroms all operations with least time complexity.

### Input:
push() , pop() , getmin(), operation to choose.

### Output:
The corresponding opertaion.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

### Adiitional Information:
Please assign me this issue I want to work on it.

**Comment by jashwanthbavandlapalli** [comment]
@shuvojitss kindly assign me the issue.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.

**Comment by shuvojitss** [comment]
@pankaj-bind I don't have any incomplete 
previous pull request.

**Comment by shuvojitss** [comment]
> Do not create unnecessary Issues until you complete the previous one.

@pankaj-bind It's ok. But until I get assigned how can I start. I have made the issue almost 4 days ago. But didn't get assigned
