### ISSUE TITLE
[NEW ALGORITHM] 

### ISSUE THREAD

**Issue by DipanwitSen** [AlgoGenesis/C#63]
## Description:
For sorting add different algorithm like quick sort ,merge sort ,radix sort etc 
## Checklist:
- [ ] Contributor in GSSoC
- [ ] Want to work on it
- [ ] hacktoberfest fest 

## Additional Information:
Want to provide best optimized code please assign me this take

**Comment by simmi-verma** [comment]
I would like to work on this. please assign to me. first time I am contributing in gssoc-ext 24.
