### ISSUE TITLE
[NEW ALGORITHM] ADD DESCRIPTION ABOUT ROTATING THE MATRIX BY 180 DEGREES.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [AlgoGenesis/C#631]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  

### About:  
Rotating a matrix by 90 degree is already explained. I want to explain the 180 degree rotation.
PLEASE ASSIGN THE ISSUE TO ME....AND ADD PROPER LABELS.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest-accepted, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@ABHISIKTAcommits assigned

**Comment by ABHISIKTAcommits** [comment]
@pankaj-bind please add the label of hacktoberfest-accepted.
