### ISSUE TITLE
[NEW ALGORITHM] Dynamic Array

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#641]
### Name:  
```[NEW ALGORITHM]```  Write a program in C to implement dynamic array using pointers. You can use malloc(), or calloc()
 to dynamaically allacate memory.

### About:  
Implementation of pointer and dynamic memory alloacation[malloc(),calloc(),realloc(),free()]

### Input:
The size of the array and the corresponding elements.

### Output:
The elements of the  array.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

### Additional Information:
Please assign me this issue I want to work on it.

**Comment by jashwanthbavandlapalli** [comment]
@shuvojitss kindly assign me this issue

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.

**Comment by shuvojitss** [comment]
@ I don't have any previous pull request left
