### ISSUE TITLE
[NEW ALGORITHM] Clone a graph

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#642]
### Name:  
```[NEW ALGORITHM]```  You are given the reference of a node in a connected undirected graph.
Return a deep copy (clone) of the graph.
Each node in the graph contains a value and a list of its neighbors.
There are n nodes in the graph each with a unique value from 0 to n-1.

### About:  
Implementation of Graph data structure.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
---
### Additional Information:
Please assign this issue to me. I want to work on this.

**Comment by susrithasabbini** [comment]
@shuvojitss I will work on it. Please assign it to me.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
