### ISSUE TITLE
[NEW ALGORITHM] Longest path in DAG

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#643]
---

### Name:  
```[NEW ALGORITHM]```  Given a weighted directed acyclic graph (DAG) and a source vertex, find the cost of the longest path from the source vertex to all other vertices present in the graph. If the vertex can’t be reached from the given source vertex, print its distance as infinity.

### Input:
Source vertex and the cost matrix or the dajacency list as per your wish.

### Output:
Longest path from source vertex to all other vertices. 

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---
### Additional Information:
Please assign me this issue I want to work on it.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
