### ISSUE TITLE
[NEW ALGORITHM] Line Sweep Algorithm

### ISSUE THREAD

**Issue by ishakatiyar06** [AlgoGenesis/C#646]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Line Sweep Algorithm

### About:  
The Line Sweep Algorithm is a computational geometry algorithm often used to solve interval problems, detect overlaps, and process geometric data. It works by sweeping a vertical or horizontal line across a plane and processing events in a sorted order (by key coordinates like time, position, etc.).
---

### Labels:  gssoc-ext
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@ishakatiyar06  assigned
