### ISSUE TITLE
[NEW ALGORITHM]  Want to add Euler's Algorithm  for finding Eulerian paths and circuits

### ISSUE THREAD

**Issue by Gurpreet0022** [AlgoGenesis/C#653]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  

### About:  
Euler's Algorithm  for finding Eulerian paths and circuits

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by jashwanthbavandlapalli** [comment]
@Gurpreet0022 assign me this issue.

**Comment by Gurpreet0022** [comment]
@jashwanthbavandlapalli  I don't know how to assign it to you ? Could you help me with it ?
