### ISSUE TITLE
[NEW ALGORITHM] Dutch National Flag Algorithm

### ISSUE THREAD

**Issue by meghanakn473** [AlgoGenesis/C#661]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Dutch National Flag Algorithm

### About:  
The Dutch National Flag Algorithm, by Edsger Dijkstra, sorts an array of three distinct elements into three parts: values less than, equal to, and greater than a pivot. It uses three pointers—low for elements less than the pivot, mid for current element processing, and high for elements greater than the pivot—sorting the array in a single pass.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [X ] Contributor in GSSoC-ext
- [X ] Want to work on it

**Comment by JSLSasiRekha** [comment]
I will work on it, can you please assign it to me.

**Comment by meghanakn473** [comment]
@pankaj-bind please assign this issue to me as i raised the issue
