### ISSUE TITLE
[NEW ALGORITHM]  In Sorting Section

### ISSUE THREAD

**Issue by TheRaj71** [AlgoGenesis/C#67]
## Description:
I am proposing the addition of the following sorting algorithms to the repository, along with their detailed explanations, time complexities, and implementations:

### 1. Heap Sort
- **Description**: Heap Sort is a comparison-based sorting technique based on a Binary Heap data structure. It first converts the list into a max heap and then extracts the largest element one by one to build the sorted list.
- **Time Complexity**:
  - Best Case: O(n log n)
  - Average Case: O(n log n)
  - Worst Case: O(n log n)

### 2. Insertion Sort
- **Description**: Insertion Sort is a simple, comparison-based algorithm that builds the final sorted array one item at a time. It is efficient for small datasets or nearly sorted data.
- **Time Complexity**:
  - Best Case: O(n)
  - Average Case: O(n^2)
  - Worst Case: O(n^2)

### 3. Merge Sort
- **Description**: Merge Sort is a divide-and-conquer algorithm that recursively splits the array into halves, sorts each half, and merges the sorted halves back together.
- **Time Complexity**:
  - Best Case: O(n log n)
  - Average Case: O(n log n)
  - Worst Case: O(n log n)

### 4. Quick Sort
- **Description**: Quick Sort is a divide-and-conquer algorithm that selects a pivot and partitions the array into elements less than or greater than the pivot. It then recursively sorts the partitions.
- **Time Complexity**:
  - Best Case: O(n log n)
  - Average Case: O(n log n)
  - Worst Case: O(n^2) (when the pivot is poorly chosen)

### 5. Radix Sort
- **Description**: Radix Sort is a non-comparative sorting algorithm that sorts numbers by processing individual digits. It processes the digits from least significant to most significant using a stable counting sort as a subroutine.
- **Time Complexity**:
  - Best Case: O(nk)
  - Average Case: O(nk)
  - Worst Case: O(nk)
  - *(where k is the number of digits in the largest number)*

### 6. Selection Sort
- **Description**: Selection Sort is a simple, in-place comparison-based algorithm that divides the input list into two parts: the sorted and unsorted part. It repeatedly selects the smallest element from the unsorted part and swaps it with the first unsorted element.
- **Time Complexity**:
  - Best Case: O(n^2)
  - Average Case: O(n^2)
  - Worst Case: O(n^2)

### 7. Counting Sort
- **Description**: Counting Sort is a non-comparative sorting algorithm that sorts elements by counting occurrences of each distinct element. It is efficient for sorting integers or objects with integer keys.
- **Time Complexity**:
  - Best Case: O(n + k)
  - Average Case: O(n + k)
  - Worst Case: O(n + k)
  - *(where k is the range of the input)*

---

### 8. Shell Sort
- **Description**: Shell Sort is a comparison-based algorithm that starts by sorting elements far apart from each other and progressively reduces the interval between elements to be compared. It’s a generalization of Insertion Sort.
- **Time Complexity**:
  - Best Case: O(n log n)
  - Average Case: O(n^3/2)
  - Worst Case: O(n^2)

### 9. Cocktail Shaker Sort
- **Description**: Cocktail Shaker Sort is a variation of Bubble Sort. It passes through the list in both directions, which helps move larger and smaller elements towards their correct ends more efficiently.
- **Time Complexity**:
  - Best Case: O(n)
  - Average Case: O(n^2)
  - Worst Case: O(n^2)

### 10. Comb Sort
- **Description**: Comb Sort is an improvement over Bubble Sort that uses a larger gap between elements to compare, which reduces the number of swaps needed. The gap shrinks as the algorithm progresses, eventually becoming 1, at which point it becomes similar to Bubble Sort.
- **Time Complexity**:
  - Best Case: O(n log n)
  - Average Case: O(n^2)
  - Worst Case: O(n^2)

### 11. Gnome Sort
- **Description**: Gnome Sort is a simple comparison-based sorting algorithm similar to Insertion Sort. The algorithm moves through the list, swapping adjacent elements if they are in the wrong order.
- **Time Complexity**:
  - Best Case: O(n)
  - Average Case: O(n^2)
  - Worst Case: O(n^2)

### 12. Odd-Even Sort
- **Description**: Odd-Even Sort is a parallel version of Bubble Sort that compares adjacent pairs of elements, first comparing odd-indexed elements and then even-indexed elements, repeating the process until the list is sorted.
- **Time Complexity**:
  - Best Case: O(n)
  - Average Case: O(n^2)
  - Worst Case: O(n^2)

### 13. Cycle Sort
- **Description**: Cycle Sort is an in-place, comparison-based sorting algorithm that is theoretically optimal in terms of the number of writes. It minimizes memory writes and is particularly useful when memory write operations are expensive.
- **Time Complexity**:
  - Best Case: O(n^2)
  - Average Case: O(n^2)
  - Worst Case: O(n^2)

### 14. Pancake Sort
- **Description**: Pancake Sort is a fun sorting algorithm that involves "flipping" subarrays, much like how you would flip pancakes. It sorts the array by flipping the largest unsorted element to the front and then flipping it into its correct position.
- **Time Complexity**:
  - Best Case: O(n)
  - Average Case: O(n^2)
  - Worst Case: O(n^2)

---

## Checklist:
- [✅ ] Contributor in GSSoC-ext
- [✅ ] Want to work on it

## Additional Information:
These algorithms represent a variety of sorting techniques, each with its own advantages depending on the dataset and application. I will ensure the implementations are well-documented, with clear explanations of their time complexities and use cases.

kindly assign me this issue

**Comment by pankaj-bind** [comment]
Check which are already there then tell me on what you want to work

**Comment by pankaj-bind** [comment]
@TheRaj71 you are good to go
