### ISSUE TITLE
[NEW ALGORITHM] 8 Puzzle problem 

### ISSUE THREAD

**Issue by Mahateaa** [AlgoGenesis/C#671]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
8puzzle problem `  

### About:  
Propose a new algorithm to be added to the repository
Given a 3×3 board with 8 tiles (each numbered from 1 to 8) and one empty space, the objective is to place the numbers to match the final configuration using the empty space. We can slide four adjacent tiles (left, right, above, and below) into the empty space.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [.] Contributor in GSSoC-ext
- [.] Want to work on it

**Comment by pankaj-bind** [comment]
@Mahateaa assigned
