### ISSUE TITLE
[NEW ALGORITHM] Meet in the Middle (used in problems with large search spaces)

### ISSUE THREAD

**Issue by sandeepmaddheshiya** [AlgoGenesis/C#673]
---

### Name:  
```Meet in the Middle```  

### About:  
The Meet in the Middle algorithm is a divide-and-conquer technique used to solve problems with large search spaces, typically when brute force would be too slow. The approach splits the problem into two smaller subproblems, solves each one independently, and then combines the results. This technique is particularly useful when the problem space grows exponentially, allowing for more efficient exploration of possible solutions.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Contributor in Hacktoberfest
- [x] Want to work on it

@pankaj-bind Please assign to me, I'll do it asap!.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
