### ISSUE TITLE
[NEW ALGORITHM] (Find Lower Bound in Sorted Array using Binary Search)

### ISSUE THREAD

**Issue by VahantSharma** [AlgoGenesis/C#681]
### Description:

- I would like to add a new algorithm that implements binary search to find the lower bound in a sorted array.
- The lower bound problem  is about efficiently locating the first position of an element in the array that is greater than or equal to the given target value.
- This functionality is about finding the first place in a sorted array where you can insert a number without messing up the order. 
---

### Proposed Changes:
- Algorithm Implementation: Add code for **Lower Bound Implementation** .
- Add README.md : Include a comprehensive README.md file that outlines:

         (1)  An explanation of the lower bound concept.
         (2)  A step-by-step guide on how to use the algorithm.
---

### CheckList:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

--- 

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

**Comment by jashwanthbavandlapalli** [comment]
@VahantSharma assign me this issue
