### ISSUE TITLE
[NEW ALGORITHM] Uniform-Cost Search (UCS)

### ISSUE THREAD

**Issue by Sandigupta** [AlgoGenesis/C#682]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Uniform-Cost Search (UCS)

### About:  
A graph search algorithm is used for weighted graphs. It expands the least-cost node first, similar to BFS but considers edge costs.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by jashwanthbavandlapalli** [comment]
@Sandigupta assign me this issue

**Comment by Sandigupta** [comment]
@pankaj-bind  Please assign this issue.

**Comment by Sandigupta** [comment]
@pankaj-bind, please assign this issue.

**Comment by pankaj-bind** [comment]
@Sandigupta assigned

**Comment by Sandigupta** [comment]
[NEW ALGORITHM] Uniform-Cost Search (UCS) #682
this is the issue number.

**Comment by Sandigupta** [comment]
@pankaj-bind Please merge this PR.
Thanks.
🙏

**Comment by Sandigupta** [comment]
@pankaj-bind 
What is this, bro? After assigning, you closed the issue without merging my PR.
