### ISSUE TITLE
[NEW ALGORITHM] SJF CPU Scheduling Program

### ISSUE THREAD

**Issue by meghanakn473** [AlgoGenesis/C#683]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   SJF CPU Scheduling 

### About:  
The Shortest Job First (SJF) scheduling algorithm selects the process with the shortest burst time for execution, aiming to minimize average waiting and turnaround time. It can be implemented as preemptive (Shortest Remaining Time First) or non-preemptive. While efficient, SJF may cause longer processes to be delayed, leading to "starvation."

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X ] Contributor in GSSoC-ext
- [X ] Want to work on it
@pankaj-bind please assign me this issue

**Comment by jashwanthbavandlapalli** [comment]
@meghanakn473 assign me this issue

**Comment by meghanakn473** [comment]
@pankaj-bind please assign me this issue, as i have created the issue
