### ISSUE TITLE
[NEW ALGORITHM] LRU Page Replacement Algorithm

### ISSUE THREAD

**Issue by meghanakn473** [AlgoGenesis/C#684]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Least Recently Used Page Replacement Algorithm

### About:  
The Least Recently Used (LRU) page replacement algorithm replaces the page that hasn't been accessed for the longest time when a page fault occurs. It aims to optimize memory usage by retaining frequently accessed pages but can be complex to implement due to tracking page access history.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [X ] Contributor in GSSoC-ext
- [X ] Want to work on it
@pankaj-bind please assign me this issue

**Comment by jashwanthbavandlapalli** [comment]
@meghanakn473 assign me this issue

**Comment by meghanakn473** [comment]
@pankaj-bind please assign me this issue, as i have created the issue
