### ISSUE TITLE
[NEW ALGORITHM] Island Counting Algorithm (DFS/BFS)

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#688]
## Description:
This issue proposes the implementation of the Island Counting Algorithm using DFS/BFS. Given a 2D grid of 0s (water) and 1s (land), the algorithm will count the number of distinct islands. Each island is a group of connected 1s (horizontally or vertically).

## Key Features:

- Input: A grid of 0s and 1s.
- Output: Number of distinct islands.
- Algorithms: DFS and BFS implementations.
## Importance:
The problem is essential for understanding connectivity in grid-based problems, which appear in areas like geographical mapping and image processing.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by susrithasabbini** [comment]
I will work on it. Please assign this to me.
