### ISSUE TITLE
[NEW ALGORITHM] : Tag Sort Algorithm

### ISSUE THREAD

**Issue by bhaviya18** [AlgoGenesis/C#694]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
TAG SORT ALGORITHM

### About:  
Tag sort is a sorting algorithm that keeps track of the original indices of elements while sorting. This allows the sorted array to be mapped back to the original array

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@bhaviya18 assigned
