### ISSUE TITLE
[NEW ALGORITHM] : 3- way Merge Sort

### ISSUE THREAD

**Issue by bhaviya18** [AlgoGenesis/C#695]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
3-way Merge Sort

### About:  
A variant of merge sort is called 3-way merge sort where instead of splitting the array into 2 parts we split it into 3 parts.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
