### ISSUE TITLE
[NEW ALGORITHM] :Pancake Sort Algorithm

### ISSUE THREAD

**Issue by bhaviya18** [AlgoGenesis/C#696]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Pancake Sort Algorithm

### About:  
Pancake sorting is the mathematical problem of sorting a disordered stack of pancakes in order of size when a spatula can be inserted at any point in the stack

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
