### ISSUE TITLE
[NEW ALGORITHM] :The Ubiquitous Binary Search

### ISSUE THREAD

**Issue by bhaviya18** [AlgoGenesis/C#697]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
The Ubiquitous Binary Search 

### About:  
a straightforward search method where you start searching from the beginning of a dataset, compare each element with the target you’re looking for, and continue until you find a match or reach the end of the dataset.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
