### ISSUE TITLE
[NEW FOLDER FOR PATTERNS] 

### ISSUE THREAD

**Issue by pand-coder** [AlgoGenesis/C#70]
## Description:
I would like to add a new folder that contains the patterns such as two pointer,sliding window, prefix sum and also many more 

## Checklist:
- [ X] Contributor in GSSoC-ext
- [ X] Want to work on it

**Comment by simmi-verma** [comment]
I would like to work on this. please assign to me. first time I am contributing in gssoc-ext 24.
