### ISSUE TITLE
[NEW ALGORITHM] Cocktail Sort

### ISSUE THREAD

**Issue by Lighting-pixel** [AlgoGenesis/C#701]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM] Cocktail Sort```  

### About:  
Cocktail Sort, also known as Bidirectional Bubble Sort or Shaker Sort, is a variation of the traditional Bubble Sort algorithm. The key difference is that Cocktail Sort traverses the list in both directions (hence the "cocktail" analogy), improving performance by reducing the number of passes needed to sort the array.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by susrithasabbini** [comment]
@Lighting-pixel I will work on it. Please assign it to me.
