### ISSUE TITLE
[UPDATE ALGORITHM] updating heaps by introducing priority queue

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [AlgoGenesis/C#704]
## Description:
the heaps dont have priority queue, i would like to add  it.

## Checklist:
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

## Affected Algorithm:
heap folders

**Comment by YadavAdarsh01** [comment]
i would like to add it

**Comment by pankaj-bind** [comment]
@YadavAdarsh01 assigned

**Comment by YadavAdarsh01** [comment]
yes
