### ISSUE TITLE
[NEW ALGORITHM] Moore Voting Algorithm

### ISSUE THREAD

**Issue by eshaalal** [AlgoGenesis/C#705]
### Name:  
Moore Voting Algorithm

### About:  
The Moore Voting Algorithm is a linear time algorithm used to find the majority element in an array,

**Comment by tanishqkolhatkar93** [comment]
Greetings!
I would like to take up this particular issue. Please guide me with the steps that need to be taken for contributing to this project in an efficient and correct manner.
Thank you.

**Comment by pankaj-bind** [comment]
@eshaalal assigned
