### ISSUE TITLE
[NEW ALGORITHM]  Dijkstra's Algorithm for Shortest Paths

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#708]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Dijkstra's Algorithm for Shortest Paths

### About:  
Dijkstra's Algorithm is a famous algorithm used to find the shortest paths between nodes in a graph. It can be applied to weighted graphs where the weights are non-negative. The algorithm uses a priority queue to explore the shortest path from a starting node to all other nodes in the graph efficiently.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [YES ] Want to work on it

**Comment by prachi-0319** [comment]
Greetings!
I would like to take up this particular issue. Please guide me with the steps that need to be taken for contributing to this project in an efficient and correct manner.
Thank you.
