### ISSUE TITLE
[NEW ALGORITHM] Binary Search

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#709]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```    Binary Search

### About:  
Binary Search is a classic algorithm used to find the position of a target value within a sorted array. It works by repeatedly dividing the search interval in half. If the target value is less than the middle element, the search continues on the left half; otherwise, it continues on the right half. This algorithm has a time complexity of O(log n), making it very efficient for large datasets.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [YES] Want to work on it

**Comment by KrinsKumar** [comment]
I would like to work on this issue!. So make a new folder in the root of the repo with the docs right?
