### ISSUE TITLE
[NEW ALGORITHM]  Addition of new algos in String Section.

### ISSUE THREAD

**Issue by TheRaj71** [AlgoGenesis/C#71]
## Description:
I am proposing the addition of the following string matching and pattern searching algorithms to the repository, along with their detailed explanations, time complexities, and implementations:

### 1. Knuth-Morris-Pratt (KMP) Algorithm
- **Description**: The KMP algorithm is a string matching algorithm that improves upon the naive string matching approach by avoiding unnecessary comparisons. It preprocesses the pattern to create a partial match table (or "lps" array), which is used to skip characters in the text.
- **Time Complexity**:
  - Preprocessing: O(m) (where m is the length of the pattern)
  - Matching: O(n) (where n is the length of the text)
  - Overall: O(n + m)

### 2. Rabin-Karp Algorithm
- **Description**: Rabin-Karp is a hash-based string matching algorithm that uses a rolling hash to find multiple pattern matches in a text. It is particularly useful for detecting multiple patterns in a large text, such as plagiarism detection.
- **Time Complexity**:
  - Best Case: O(n + m)
  - Worst Case: O(n * m) (due to hash collisions)

### 3. Z Algorithm
- **Description**: The Z algorithm finds all occurrences of a pattern in a string in linear time by preprocessing the input into a Z-array. It is efficient for finding exact pattern matches and is useful in bioinformatics and string analysis.
- **Time Complexity**: O(n + m)

### 4. Boyer-Moore Algorithm
- **Description**: The Boyer-Moore algorithm is a highly efficient string matching algorithm that uses two heuristics (the bad character rule and the good suffix rule) to skip sections of the text, reducing the number of comparisons.
- **Time Complexity**:
  - Best Case: O(n / m)
  - Average Case: O(n)
  - Worst Case: O(n * m)

### 5. Aho-Corasick Algorithm
- **Description**: Aho-Corasick is an efficient multi-pattern string matching algorithm. It builds a finite state machine to search for multiple patterns simultaneously and outputs all matches in a single pass through the text.
- **Time Complexity**: O(n + m + z) (where z is the number of matches)

### 6. Manacher's Algorithm
- **Description**: Manacher's Algorithm is used to find the longest palindromic substring in linear time. It efficiently computes the lengths of all palindromic substrings centered at each position in the string.
- **Time Complexity**: O(n)

### 7. Suffix Array
- **Description**: A Suffix Array is a sorted array of all suffixes of a given string. It can be used to solve a variety of string matching and searching problems, such as finding the longest repeated substring or searching for a pattern.
- **Time Complexity**:
  - Construction: O(n log n)
  - Search: O(m log n)

---

## Checklist:
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

## Additional Information:
These string algorithms are highly efficient for solving a variety of pattern matching and substring searching problems. Each algorithm is implemented to minimize time complexity and optimize performance for specific use cases, such as searching for multiple patterns, detecting palindromes, or handling large texts.

**Comment by simmi-verma** [comment]
I would like to work on this. please assign to me. first time I am contributing in gssoc-ext 24.

**Comment by pratheekv39** [comment]
@TheRaj71 Unfortunately, these algorithms are already present in the String Algorithms except Manacher's algorithm. I would recommend you to raise another issue with Manacher algorithm...

**Comment by pankaj-bind** [comment]
@pratheekv39 Do you want to work I think @TheRaj71 is just spamming

**Comment by pratheekv39** [comment]
Sure , I will add Manacher's Algorithm and raise a PR for this issue 👍🏿

**Comment by pratheekv39** [comment]
@pankaj-bind The spammer closed this issue . Shall I raise a new issue regarding this ??
