### ISSUE TITLE
[NEW ALGORITHM] A* Search Algorithm

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#710]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   A* Search Algorithm
 
### About:  
The A* (A-star) Search Algorithm is a widely used pathfinding and graph traversal algorithm. It is an extension of Dijkstra's Algorithm and incorporates heuristics to optimize the search process. A* efficiently finds the shortest path from a start node to a goal node by evaluating the cost to reach a node and the estimated cost to reach the goal from that node. This algorithm is particularly useful in scenarios like navigation systems and game development.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ YES] Contributor in GSSoC-ext
- [ YES] Want to work on it

**Comment by career-yashaswee** [comment]
Would love to work on it. Please assign it to me!
