### ISSUE TITLE
[NEW ALGORITHM] M-Coloring Problem

### ISSUE THREAD

**Issue by tanishqkolhatkar93** [AlgoGenesis/C#713]
Issue will be closed if:
You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.
You propose an algorithm that is already present or has been mentioned in a previous issue.
You create a new issue without completing your previous issue.
Note: These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

Name:
[NEW ALGORITHM] M-Coloring Problem

About :
M-Coloring Problem is a backtracking problem widely used in various backtracking applications .The problem is as follows-
Given an undirected graph and a number m, the task is to color the given graph with at most m colors such that no two adjacent vertices of the graph are colored with the same color

Labels:
new algorithm, gssoc-ext, hacktoberfest, level1

Assignees:
[ YES] Contributor in GSSoC-ext
[ YES] Want to work on it

**Comment by susrithasabbini** [comment]
@tanishqkolhatkar93 I will work on it. Please assign it to me.
