### ISSUE TITLE
[NEW ALGORITHM] Sort A Linked List

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#720]
### Name:  
```[NEW ALGORITHM]```  Given a singly Linked List, the task is to sort this Linked List in non-decreasing order.

---
### About:  
Implementation of Linked list.

### Input:
The elements of the linkedlist.

### Output:
The elements of the linkedlist in non decreasing order.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---
### Additional Information:
Please assign me this issue I want to work on it.

**Comment by susrithasabbini** [comment]
I will work on it. Please assign it to me.
