### ISSUE TITLE
[NEW ALGORITHM] Stack Permutation

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#721]
---

### Name:  
```[NEW ALGORITHM]```  Given two arrays, both of unique elements. One represents the input queue and the other represents the output queue. Our task is to check if the given output is possible through stack permutation.

---
### Sample Input and Output:
**Input:** arr1[] = [ 1, 2, 3 ] , arr2[] = [ 2, 1, 3 ]
**Output:** YES
**Explanation:** 
push 1 from input to stack
push 2 from input to stack
pop 2 from stack to output
pop 1 from stack to output
push 3 from input to stack
pop 3 from stack to output

**Input:** arr1[] = [ 1, 2, 3 ] , arr2[] = [ 3, 1, 2 ]
**Output:** Not Possible

---
### About:  
Application of stack data structure.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

### Additional Information:
Please assign me this, I want to work on this.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
