### ISSUE TITLE
[NEW ALGORITHM] Bipartite Graph

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#722]
### Name:  
```[NEW ALGORITHM]```  Given an adjacency list / matrix representing a graph with V vertices indexed from 0, the task is to determine whether the graph is bipartite or not. You can use queue data structure to check the graph.

---
### About:  
Implementation of queue data structure.

### Input:
The adjacency matrix.

### Output:
True or false

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---
### Additional Information:
Please assign me this issue. I want to work on this.

**Comment by JSLSasiRekha** [comment]
I will solve it.
