### ISSUE TITLE
[NEW ALGORITHM] Add 1 to a linked list 

### ISSUE THREAD

**Issue by Arghya-Chakraborty0812** [AlgoGenesis/C#724]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
 Add 1 to a linked list 

### About:  
Propose a new algorithm to be added to the repository
It will add 1 to a number stored in format of a singly-linked list
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
Please assign this issue to me.Also can you assign me level 2.

**Comment by susrithasabbini** [comment]
@Arghya-Chakraborty0812 I am interested to solve this. Please assign it to me.
