### ISSUE TITLE
Algorithm for reversing a singly linked list without using extra space.

### ISSUE THREAD

**Issue by AnshDhingraAD** [AlgoGenesis/C#732]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Algorithm for reversing a singly linked list without using extra space.```  

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by susrithasabbini** [comment]
I will work on it.

**Comment by AnshDhingraAD** [comment]
> @AnshDhingraAD I will work on it. Please assign it to me.
 
@susrithasabbini May I know your designation in the project?

**Comment by susrithasabbini** [comment]
I am the contributor for gssoc-ext
