### ISSUE TITLE
[NEW ALGORITHM] Floyd-Warshall Algorithm

### ISSUE THREAD

**Issue by susrithasabbini** [AlgoGenesis/C#743]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]``  

### About:  
I propose to add a new algorithm to the repository for Floyd-Warshall Algorithm. This algorithm is used for finding the shortest paths in a weighted graph with positive or negative edge weights (but with no negative cycles).
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Sumanth077s** [comment]
Yes Im a Contributer in GSSoC -ext
I want to work on it
