### ISSUE TITLE
[NEW ALGORITHM] LRU Cache

### ISSUE THREAD

**Issue by susrithasabbini** [AlgoGenesis/C#744]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  

### About:  
I propose to add a new algorithm to the repository for the LRU (Least Recently Used) Cache. The LRU Cache is a data structure that efficiently stores a limited number of items while maintaining quick access to the most recently used entries. This cache eviction policy is particularly useful in scenarios where memory or storage is constrained, as it allows for the efficient management of resources by evicting the least recently accessed items first.

Key Features of the LRU Cache:
Fast Access: The cache provides average O(1) time complexity for both insertion and retrieval operations, making it highly efficient for frequent access patterns.
Automatic Eviction: When the cache reaches its maximum capacity, the least recently used item is automatically removed to make space for new entries, ensuring that the most relevant data remains accessible.
Use Cases: The LRU Cache is widely used in applications such as web browsers, operating systems, and databases, where managing memory effectively is crucial for performance. It is particularly beneficial in situations involving repetitive data access, such as retrieving images or files in a web application.
Implementation Details: The LRU Cache will be implemented using a combination of a hashmap (for O(1) access) and a doubly linked list (to maintain the order of usage). This approach allows us to quickly find, update, or remove entries while keeping track of their usage order.
By implementing the LRU Cache, we enhance the repository with a robust solution for caching, helping developers optimize memory usage and improve application performance.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Sumanth077s** [comment]
Yes I m a Contributor in GSSoC
I want to work on it
