### ISSUE TITLE
[NEW ALGORITHM]  Adding New Scheduling ALgorithms 

### ISSUE THREAD

**Issue by PrAyAg9** [AlgoGenesis/C#745]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
Adding Whole Directory of Scheduling Algorithms:- 
-First Come First Serve Scheduling Algorithm
-Round Robin Scheduling Algorithm
-Priority Scheduling Algorithm

### About:  
Propose a new algorithm to be added to the repository
1) Propose the First Come First Serve (FCFS) scheduling algorithm to be added to the repository. This non-preemptive algorithm serves processes in the order they arrive in the ready queue, ensuring fairness but potentially leading to long wait times for short processes.

2)Propose the Round Robin (RR) scheduling algorithm to be added to the repository. This preemptive algorithm assigns a fixed time slice to each process, allowing for fair time-sharing among processes in a cyclic manner. It is well-suited for time-sharing systems.

3)Propose the Priority Scheduling algorithm to be added to the repository. This scheduling method selects processes based on their priority, allowing for efficient handling of critical tasks. It can be preemptive or non-preemptive, depending on the implementation.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [  yes  ] Contributor in GSSoC-ext
- [ yes ] Want to work on it

**Comment by Sumanth077s** [comment]
yes

**Comment by PrAyAg9** [comment]
> Yes I am contributor in GSSoC ext I want to work on this issue

IT's already done guys work on new Issue-

**Comment by Sumanth077s** [comment]
> > Yes I am contributor in GSSoC ext I want to work on this issue
> 
> IT's already done guys work on new Issue-

In which folder I didn't find so raised a pull request sorry
