### ISSUE TITLE
[NEW ALGORITHM] Longest Common Substring in Dynamic Programming

### ISSUE THREAD

**Issue by Lokesh11868** [AlgoGenesis/C#757]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Longest Common Substring in Dynamic Programming```  

### About:  
The Longest Common Substring problem is a classic problem in dynamic programming. Given two strings, the goal is to find the longest substring that is common to both strings. A substring is a sequence of characters that occurs consecutively within a string.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by mothi-135** [comment]
can you please assign this issue to me?
