### ISSUE TITLE
[NEW ALGORITHM] Sliding Window Technique Explanation and 10 Problem Sets

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#766]
### Description:
This issue proposes to provide a detailed explanation of the Sliding Window technique, a crucial optimization strategy used in solving various algorithmic problems. The sliding window method helps to efficiently handle problems involving sequences, such as arrays or strings, by maintaining a subset of data and sliding it across the input.

### Problem Set:
1. **Maximum Sum Subarray of Size K**: Find the maximum sum of a contiguous subarray of size K within a given array.
2. **Longest Substring Without Repeating Characters**: Determine the length of the longest substring that contains all unique characters.
3. **Minimum Window Substring**: Given two strings, find the minimum window in the first string that contains all characters of the second string.
4. **Longest Substring with At Most K Distinct Characters**: Find the length of the longest substring that contains at most K distinct characters.
5. **Find All Anagrams in a String**: Given a string and a pattern, find all occurrences of the anagrams of the pattern in the string.
6. **Longest Repeating Character Replacement**: Given a string, find the length of the longest substring that can be obtained by replacing at most K characters.
7. **Subarray Product Less Than K**: Find the total number of contiguous subarrays where the product of all the elements is less than K.
8. **Count Distinct Elements in Every Window of Size K**: Given an array and a number K, find the count of distinct elements in every window of size K.
9. **Binary Subarrays with Sum**: Count the number of non-empty subarrays that sum up to a given value S.
10. **Sliding Window Maximum**: Given an array and a number K, find the maximum value in every contiguous subarray of size K.

### Motivation:
Implementing these problems using the Sliding Window technique will provide a comprehensive understanding of its applications and enhance problem-solving skills in algorithmic challenges.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by divyalakshmi0** [comment]
@pankaj-bind sir, can you assign me and label it as level 2 ?

**Comment by HemanthM8** [comment]
I would like to work on thus issue

**Comment by divyalakshmi0** [comment]
@pankaj-bind sliding window hasn't yet completed by anyone yet!!!
