### ISSUE TITLE
[NEW ALGORITHM] power of a number using recursion 

### ISSUE THREAD

**Issue by ahanadasgupta26** [AlgoGenesis/C#777]
### Name:
I want to add power of a number(recursive approach) algorithm in the recursion part of this repository.

### About:
This program helps to find the power of a number using recursive approach.When a function calls itself is known as recursion.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ✓] Contributor in GSSoC-ext
- [✓] Want to work on it

**Comment by Gokulan-SK** [comment]
i have submitted a pull request on this issue(#780), can you please review it.
