### ISSUE TITLE
[NEW ALGORITHM] Dutch National Flag Algorithm in C

### ISSUE THREAD

**Issue by Rahilsamani** [AlgoGenesis/C#781]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Dutch National Flag Algorithm```  

### About:  
The Dutch National Flag algorithm, developed by Edsger W. Dijkstra, sorts an array of elements into three distinct groups efficiently. It is typically used when the elements are limited to three distinct values. The algorithm works by maintaining three pointers:
- low for the first group (e.g., 0s).
- mid for the middle group (e.g., 1s).
- high for the last group (e.g., 2s).
The algorithm runs in O(n) time complexity with a space complexity of O(1).

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level2```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by Lokesh-Bijarniya** [comment]
@Rahilsamani Could you assign me ?

**Comment by Rahilsamani** [comment]
Why did you closed?
@pankaj-bind
