### ISSUE TITLE
[NEW ALGORITHM] Josephus Circle Problem

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#783]
### Name:  
```[NEW ALGORITHM]```  N people have decided to elect a leader by arranging themselves in a circle and eliminating every Mth person around the circle, closing ranks as each person drops out. Find which person will be the last one remaining( with rank 1).

---
### About:  
Implementation of circular linked list. Cicular queue can also be used.

---
### Sample input and output:

**Input:** N = 5 and k = 2
**Output:** 3
**Explanation:** Firstly, the person at position 2 is killed, then the person at position 4 is killed, then the person at position 1 is killed. Finally, the person at position 5 is killed. So the person at position 3 survives. 

**Input:** N = 7 and k = 3
**Output:** 4
**Explanations:** The persons at positions 3, 6, 2, 7, 5, and 1 are killed in order, 
and the person at position 4 survives.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---
### Additional Information:
Please assign me this issue I want to work on it.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
