### ISSUE TITLE
[NEW ALGORITHM] (Koko Eating Bananas Problem using Binary Search)

### ISSUE THREAD

**Issue by VahantSharma** [AlgoGenesis/C#786]
### Description:
- I would like to add a new algorithm that solves the Koko Eating Bananas problem using binary search on the answer space.
- The Koko Eating Bananas problem involves determining the minimum eating speed 
'k' at which Koko can finish all the banana piles within a given number of hours 'h'.
- The goal is to find the smallest integer speed such that Koko can complete eating all the bananas in the given time constraint.

---

### Proposed Changes:
- Algorithm Implementation: Add code for **KoKo Eating Bananas** problem.

- Add README.md :  Include a comprehensive README.md file that outlines:

       (1) An explanation of the binary search on answer search.
       (2) An explanation of the KoKo eating problem statement.
       (3) A step-by-step guide on how to solve the problem.

---

### Checklist:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

**Comment by avbhutani** [comment]
Can you assign it to me?
