### ISSUE TITLE
[NEW ALGORITHM] Josephus Problem 

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#791]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  Josephus Problem 

### About:  
The Josephus Problem is a theoretical problem related to a certain elimination game. People are arranged in a circle, and every k-th person is eliminated until only one person remains. The objective is to find the position of the last person standing. This problem has applications in computer science, particularly in data structures (circular linked lists) and game theory.

Implementation Details:
This algorithm will be implemented in C using both recursive and iterative approaches. The program will take the number of people n and the elimination step k as inputs and return the position of the last remaining person.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
