### ISSUE TITLE
Add an algorithm to merge intervals (line sweep)

### ISSUE THREAD

**Issue by lakshmirajvagu** [AlgoGenesis/C#794]
### Name:  
```Line sweep algorithm ```  

### About:  
This algorithm mainly used to solve questions based on intervals I will add algorithm and a sample of 2 to 3 questions 

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level 1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by AK261102** [comment]
@lakshmirajvagu  please assign me
