### ISSUE TITLE
transpose of a 2D matrix

### ISSUE THREAD

**Issue by PrasanBora** [AlgoGenesis/C#795]
### Name:  
Transpose of a 2D matrix

### About:  
The current repository lacks a simple and fundamental program to transpose a 2D matrix, which is a common operation in mathematical computing and matrix manipulation. Adding this will help users understand basic matrix operations and enhance their skills in handling multidimensional arrays.

The Transpose of a Matrix is an operation where the rows of a matrix are converted to columns and the columns are converted to rows.

Algorithm Explanation:
Given a matrix A with dimensions m x n (i.e., m rows and n columns), the transpose of A is a new matrix B with dimensions n x m, where the elements of B are defined as:
B[i][j]=A[j][i]
That means:
The element at row i and column j in matrix A will be placed at row j and column i in matrix B.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me?

**Comment by hari-dev-003** [comment]
☑️Contributor in GSSoc-ext
☑️Want to contribute 

Can you assign this issue

**Comment by crackedmob** [comment]
I would love to contribute to this , and i request you to please assign this to me .

**Comment by pankaj-bind** [comment]
@PrasanBora assigned

**Comment by mahi7665** [comment]
I would like to work on this project, kindly assign me this one.

**Comment by crackedmob** [comment]
> @PrasanBora assigned

Thank you for this , can you give me gssoc-extd label and hacktoberfest label please
