### ISSUE TITLE
Number of subarrays having product less than K

### ISSUE THREAD

**Issue by PrasanBora** [AlgoGenesis/C#796]
### Name:  
```[Number of subarrays having product less than K]```  

### About:  
Given an array of positive numbers, calculate the number of possible contiguous subarrays having product lesser than a given number K
The idea is to use two pointers (or a sliding window) to represent a dynamic range of elements. As we traverse the array, we calculate the product of elements in the current window. If the product exceeds K, we shrink the window from the left by moving the left pointer. For every valid window (i.e., product < K), all subarrays ending at the right pointer are valid and we can count them
_This was asked in my Accenture test_
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1,hacktoberfest-2024```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by mothi-135** [comment]
can you please assign this issue to me?

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
