### ISSUE TITLE
[NEW ALGORITHM] Largest Rectangular Area in a Histogram

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#798]
### Name:  
```[NEW ALGORITHM]```  Find the largest rectangular area possible in a given histogram where the largest rectangle can be made of a number of contiguous bars whose heights are given in an array. For simplicity, assume that all bars have the same width and the width is 1 unit.

---
### About:  
Implementation of Stack data structure.

---
### Sample Input and Output:

**Input:** hist = {60, 20, 50, 40, 10, 50, 60}
**Output:** 100
**Explanation :** We get the maximum are by picking bars highlighted above in green (50, and 60). The area is computed (smallest height) *  (no. of the picked bars) = 50* 2 = 100

**Input:** hist = {3, 5, 1, 7, 5, 9}
**Output:** 15
**Explanation :**  We get the maximum are by picking bars 7, 5 and 9 The area is computed (smallest height) *  (no. of the picked bars) = 5 * 3 = 15

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---
### Additional Information:
Please assign me this issue I want to work on this.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
