### ISSUE TITLE
Addition of Linear Search in Searching Algos.

### ISSUE THREAD

**Issue by Shariq2003** [AlgoGenesis/C#8]
@pankaj-bind 
I am going to add the Linear Search Algorithm in the Searching Algorithms.
With the proper Objective and Explaination, with proper code in C.

Please Assign this to me.

**Comment by pankaj-bind** [comment]
You can start

**Comment by Shariq2003** [comment]
@pankaj-bind please add lebels of gssoc

**Comment by Shariq2003** [comment]
@pankaj-bind i have already added the Linear Search Folder and you also have merged that along with DFS, but this issue is still opened.

**Comment by simmi-verma** [comment]
I would like to work on this .Please assign to me.
