### ISSUE TITLE
[NEW ALGORITHM] Largest rectangle in a histogram

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#806]
---

 Name:  
```[NEW ALGORITHM]  Largest rectangle in a histogram```  

### About:  
Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.

 

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

**Comment by mothi-135** [comment]
can you please assign this issue to me?

**Comment by Dipanita45** [comment]
Please assign me the issue so that i can start working on it @pankaj-bind

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.

**Comment by Dipanita45** [comment]
I have not created pr

**Comment by Dipanita45** [comment]
Please assign me #676 sir
