### ISSUE TITLE
[NEW ALGORITHM] Kruskal's Algorithm (Minimum Spanning Tree)

### ISSUE THREAD

**Issue by ananyag309** [AlgoGenesis/C#81]
## Description:
This algorithm finds the minimum spanning tree for a connected weighted graph.
Key Concept: Utilizes a union-find data structure to detect cycles.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@ananyag309  You can start
