### ISSUE TITLE
Rabin-Karp Algorithm

### ISSUE THREAD

**Issue by MihirSaiDudekula** [AlgoGenesis/C#83]
### Description:
The Rabin-Karp algorithm is a string searching technique that uses hashing to find any one of a set of pattern strings in a text. It's particularly useful when you need to search for multiple patterns simultaneously or when working with long texts.

#### Key Features:
- **Hashing**: The algorithm utilizes a rolling hash function, which allows for efficient computation of hash values for the substrings of the text.
- **Multiple Patterns**: It can search for multiple patterns in a single pass by using a hash set to store the hash values of the patterns.
- **Average Case Efficiency**: The average-case time complexity is \( O(n + m) \), where \( n \) is the length of the text and \( m \) is the length of the pattern. In the worst case, it can degrade to \( O(nm) \), but this is rare.

#### Algorithm Steps:
1. **Hash Calculation**: Compute the hash value for the pattern and the first window of the text.
2. **Sliding Window**: Slide the window one character at a time across the text.
3. **Hash Comparison**: For each window, compare the hash of the window with the hash of the pattern:
   - If the hash values match, verify the actual substring (to handle hash collisions).
4. **Rolling Hash**: Update the hash value as the window slides over the text using a rolling hash function.

### Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pratheekv39** [comment]
@MihirSaiDudekula  Rabin Karp Algorithm has already been added in the Strings Algorithms. Kindly raise another issue...
