### ISSUE TITLE
[NEW ALGORITHM] Postfix to Prefix

### ISSUE THREAD

**Issue by KashishJuneja101003** [AlgoGenesis/C#837]
### Name:  
```Postfix to Prefix```  

### About:  
I would like to add an algorithm for postfix to prefix conversion.

---

### Labels:  
```gssoc-ext, hacktoberfest```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Rajanjha12** [comment]
Please assign me this issue .i had done shiksha samagam issue

**Comment by crackedmob** [comment]
can you please assign me to this issue ?
thank you

**Comment by mahi7665** [comment]
I would like to work on this project, please assign this project to me.

**Comment by pankaj-bind** [comment]
@KashishJuneja101003 assigned
