### ISSUE TITLE
[NEW ALGORITHM] Sum Tree

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#844]
### Name:  
```[NEW ALGORITHM]```  Given a binary tree, the task is to check if it is a Sum Tree. A Sum Tree is a Binary Tree where the value of a node is equal to the sum of the nodes present in its left subtree and right subtree. An empty tree is Sum Tree and the sum of an empty tree can be considered as 0. A leaf node is also considered a Sum Tree.

---
### About:  
Implementation of binary tree

### Input:
The nodes of the tree.

### Output:
True or False ( Based on calculating the value of child nodes and parent node)
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

---
### Additional Information
Please assign me this issue I want to work on this,

**Comment by IshuSinghSE** [comment]
Hello! Could you assign this to me?

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
