### ISSUE TITLE
[NEW ALGORITHM] Symmetric Tree

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#847]
### Name:  
```[NEW ALGORITHM]```  Symmetric Tree
Given a Binary Tree, determine whether the given tree is symmetric or not. A Binary Tree would be Symmetric, when its mirror image is exactly the same as the original tree. If we were to draw a vertical line through the centre of the tree, the nodes on the left and right side would be mirror images of each other.

---
### About:  
Implementation of Tree data structure.

### Input:
The nodes of the tree.

### Output:
The tree is symmetrical / The tree is not symmetrical

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

### Additional Information:
Please assign me this issue I want to work on it.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
