### ISSUE TITLE
[NEW ALGORITHM] Addition of Linked List Folder

### ISSUE THREAD

**Issue by OneLimeStudio** [AlgoGenesis/C#86]
## Description:
Since there is Stacks and Queue Folder ,
I think it should also have linked list with various functions such as traversal, insertion and deletion

## Checklist:
- [no ] Contributor in GSSoC-ext
- [ yes] Want to work on it
- [ yes] -Contributor in Hacktober

## Additional Information:
None

**Comment by kashishchadha** [comment]
i have a better solution for this issue ,pls assign me this task
