### ISSUE TITLE
[NEW ALGORITHM] Add DFS and BFS Algorithm

### ISSUE THREAD

**Issue by AnushkaChouhan25** [AlgoGenesis/C#862]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```DFS and BFS```  

### About:  
I want to add Breadth First Search (BFS) and Depth First Search a graph traversal algorithm. This are fundamental algorithms used for traversing or searching graphs and trees.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Sai-ganesh-0004** [comment]
Hey i would like to work on this can you assign this to me
