### ISSUE TITLE
[UPDATE ALGORITHM]  Kadane's Algorithm

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#865]
## Description:
The current implementation of Kadane's Algorithm can be improved for better functionality and usability. The following updates are proposed:

1.Edge Case Handling: Ensure the algorithm can handle an empty array input, where no subarray exists.
2.Dynamic Memory Allocation: Utilize dynamic memory allocation (malloc) for handling large input sizes efficiently.
3.Input Validation: Add validation to handle incorrect input for both array size and elements.
4.Modular Code Structure: Separate input handling, result computation, and result display into individual functions for improved code organization and readability.

These changes are necessary to enhance the robustness of the algorithm and make it scalable for larger inputs, while improving the user experience by handling potential input errors.

## Checklist:
- [YES ] Contributor in GSSoC-ext
- [YES ] Want to work on it

## Affected Algorithm:
Algorithm: Kadane's Algorithm
Directory: /algorithms/dynamic_programming/kadane_algorithm.c

## Additional Information:
By implementing dynamic memory allocation, the algorithm will be capable of processing large datasets. Input validation ensures that invalid data will not cause unexpected behavior, thus improving the program's robustness. Additionally, the modular code structure will facilitate future updates or maintenance.

**Comment by Aakarshit07** [comment]
@13Sharad  Hey, I hope you doing well. I like to contribute to this issue. Can you assign this to me ? Thank you !

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
