### ISSUE TITLE
[UPDATE ALGORITHM] Two Pointer

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#866]
## Description:
We aim to improve the existing 3Sum algorithm implementation by optimizing it for performance and ensuring it correctly handles duplicate triplet cases. The new implementation will utilize sorting and the two-pointer technique, resulting in a time complexity of 
𝑂(n^2). This is necessary as the previous approach may have had inefficiencies and did not adequately manage duplicates, leading to potential incorrect outputs.

## Checklist:
- [YES ] Contributor in GSSoC-ext
- [ YES] Want to work on it

## Affected Algorithm:
The algorithm being updated is the 3Sum algorithm, located in the directory /algorithms/3sum.

## Additional Information:
The updated algorithm will:

1.Sort the input array to facilitate the two-pointer technique.
2.Implement a check to skip duplicate triplets.
3.Improve memory management by allocating and freeing memory for storing the triplets found.
4.Output all unique triplets that sum to zero.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
