### ISSUE TITLE
[UPDATE ALGORITHM] Two Pointer

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#867]
## Description:
I propose updating the 4Sum algorithm implementation to improve its efficiency and memory management. The current implementation uses a simple bubble sort for sorting, which is not optimal for larger datasets. Additionally, it lacks proper memory handling for storing quadruplets, which can lead to memory leaks.

## Checklist:
- [YES ] Contributor in GSSoC-ext
- [YES ] Want to work on it

## Affected Algorithm:
The algorithm to be updated is the 4Sum algorithm located in the ./C/two pointer/4sum.

## Additional Information:
The update will involve:

1.Using qsort for efficient sorting.
2.Implementing better handling of duplicate values to ensure unique quadruplets are counted.
3.Dynamically allocating memory for storing quadruplets and ensuring proper deallocation to avoid memory leaks.
4.Enhancing the logic to calculate the target sum using a two-pointer approach for optimal performance.

**Comment by Sai-ganesh-0004** [comment]
Hey i would like to work on this can you assign this to me

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
