### ISSUE TITLE
[UPDATE ALGORITHM] 2D Arrays

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#868]
## Description:
I want to enhance the existing Tic-Tac-Toe game by improving the user interface, optimizing game logic, and adding better move validation. These changes are necessary to provide a smoother gaming experience, improve code readability, and ensure that the game handles invalid moves more effectively.

## Checklist:
- [ YES] Contributor in GSSoC-ext
- [YES ] Want to work on it

## Affected Algorithm:
The algorithm I want to update is the Tic-Tac-Toe game logic, specifically located in the tic_tac_toe directory. This includes functions for player moves, board display, and win-checking logic.

## Additional Information:
I suggest implementing a function to initialize the game board and a separate function to print the board, which will help in maintaining code clarity. Additionally, the logic for checking win conditions could be refactored to reduce redundancy and improve performance.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
