### ISSUE TITLE
[UPDATE ALGORITHM]  Hash Algorithms

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#869]
## Description:
I want to enhance the existing Bloom filter algorithm by implementing dynamic memory allocation for the Bloom filter array, improving the hash functions for better distribution, and adding memory management functions to prevent memory leaks. These changes are necessary to improve the efficiency, clarity, and robustness of the implementation.

## Checklist:
- [YES ] Contributor in GSSoC-ext
- [YES ] Want to work on it

## Affected Algorithm:
The algorithm to be updated is the Bloom filter, located in the path/to/your/bloom filter directory.

## Additional Information:
1.The Bloom filter will now use dynamically allocated memory to allow for better management and potential resizing.
2.Improved hash functions using different prime numbers for better distribution of hash values.
3.Added functions to initialize and free memory for the Bloom filter to prevent memory leaks.
4.Enhanced comments throughout the code for better readability and understanding.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
