### ISSUE TITLE
[NEW ALGORITHM]: Merge Sort and Selection Sort

### ISSUE THREAD

**Issue by himanshu-sheetlani** [AlgoGenesis/C#87]
## Description:
I want to add two of the most important sorting algorithms Merge Sort and Selection Sort in the [Sorting Algorithms](https://github.com/AlgoGenesis/C/tree/main/Sorting%20Algorithms) section of this repository 

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
- As a software engineering student, I can explain this algo in a very easy way.
- Will explain about efficiency and time complexity of both.
- I will provide code for algo for better understanding.

**Comment by harish08102004** [comment]
Hey @himanshu-sheetlani I can work on this.

**Comment by Biswajeet124** [comment]
I would like to work on this project. Please assign it to me. @himanshu-sheetlani
