### ISSUE TITLE
[UPDATE ALGORITHM]  Hash Algothrims

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#870]
## Description:
This update enhances the DJB2 hash algorithm implementation by adding NULL input handling, improving code organization, and providing a user input feature for interactive hashing. These changes ensure that the algorithm can gracefully handle edge cases and provide users with a more robust experience.

## Checklist:
- [YES ] Contributor in GSSoC-ext
- [ YES] Want to work on it

## Affected Algorithm:
DJB2 Hash Algorithm, located in the hashing directory.

## Additional Information:
1.The update includes a test function to verify the correctness of the DJB2 implementation.
2.User input functionality allows users to hash their strings directly.
3.The code now handles NULL inputs gracefully by returning 0.

**Comment by pankaj-bind** [comment]
Do not create unnecessary PR until you complete the previous one.
