### ISSUE TITLE
Searching Algorithm-beam search algorithm -update.

### ISSUE THREAD

**Issue by PradeepFSTdhane123** [AlgoGenesis/C#871]
## Error in code implimentation.

***Node Structure***- Node structure that represents a node in a tree or graph with a value, the number of children, and pointers to child nodes.

***Node Creation***-The createNode function allocates memory for a new node and initializes its value and children.

***Beam Search Implementation-***
You initialize a beam with the root node and expand it iteratively.
For each node in the current beam, you add its children to the next beam.
You sort and limit the size of the next beam based on the beam width.
Memory Management: You allocate memory for nodes but do not free all allocated memory properly at the end of the program.

## Checklist:
- [ ] Contributor in GSSoC-ext and hacktoberfest.
- [ ] Want to work on it 

## Affected Algorithm: -Searching Algorithm-beam search algorithm 

***Key Changes-***
***Memory Management:*** Added a freeTree function to recursively free all nodes and their children to prevent memory leaks.
***NULL Check:*** Added a check for NULL before adding children to the next beam.
***Clearer Structure:*** The main function initializes the tree structure and calls freeTree at the end to clean up allocated memory.
This code should now work correctly and efficiently manage memory while performing the beam search.

"I am very interested in contributing to this project and would love the chance to work on this issue. Can you please assign it to me ? I am excited to start working on it and make a valuable contribution. Thank you!"

**Comment by pankaj-bind** [comment]
@PradeepFSTdhane123 assigned
