### ISSUE TITLE
[NEW ALGORITHM] Heavy-Light Decomposition

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [AlgoGenesis/C#874]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
Heavy-Light Decomposition

### About:  
A technique used to decompose trees for solving problems related to path queries and updates.

---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level2
,
---

### Assignees:  
- [X] Contributor in GSSoC-ext
- [X] Want to work on it

**Comment by Sai-ganesh-0004** [comment]
Hey 
I would like to work on it Can I give It a try

**Comment by pankaj-bind** [comment]
@SanikaBhalerao1345 assigned
