### ISSUE TITLE
[NEW ALGORITHM] Dijkstra's Algorithm for Shortest Path Finding

### ISSUE THREAD

**Issue by DivyaJyothi9** [AlgoGenesis/C#875]
### Name:  
 Dijkstra's Algorithm for Shortest Path Finding

### About:  
 I would like to propose adding Dijkstra's Algorithm to the repository. This algorithm is widely used for finding the shortest path from a source node to all other nodes in a weighted graph. It is particularly useful in applications like network routing, geographic mapping, and various optimization problems.

**Benefits of Adding Dijkstra's Algorithm:**

Educational Resource: Providing a clear implementation of Dijkstra's Algorithm will benefit both students and educators by demonstrating a fundamental graph traversal technique.
Wider Algorithm Coverage: Adding this algorithm enhances the diversity of algorithms present in the repository, showcasing a key concept in computer science.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by hunainejaz2** [comment]
assign to me

**Comment by DivyaJyothi9** [comment]
@pankaj-bind  I’m interested in the issue "Add Dijkstra's Algorithm for Shortest Path Finding" **that I created**. I believe this addition will enhance the repository and benefit learners.

Could you please assign this issue to me? I'm eager to contribute!
Thank you for considering my request @pankaj-bind . I look forward to your response
