### ISSUE TITLE
[NEW ALGORITHM] Add Tim Sort

### ISSUE THREAD

**Issue by Aditijainnn** [AlgoGenesis/C#878]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   Tim Sort

### About:  
Propose a new algorithm to be added to the repository

Tim Sort is highly efficient for real-world datasets, which often contain partially sorted data, making it widely used in modern software systems.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Aakarshit07** [comment]
@Aditijainnn Heyy, I hope you doing well. I like to contribute to this issue. Can you assign this to me ? Thank you !

**Comment by pankaj-bind** [comment]
@Aditijainnn assigned

**Comment by pankaj-bind** [comment]
@Aakarshit07 assigned

**Comment by Aakarshit07** [comment]
@pankaj-bind Hello, what would be the base branch to give pull request
