### ISSUE TITLE
[NEW ALGORITHM]: Add Generic Linear Sort Algorithm.

### ISSUE THREAD

**Issue by SAMluci666** [AlgoGenesis/C#88]
## Description:
Please provide a detailed description of the algorithm you are proposing.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
- The Algorithm will be generic as such it can work on any data type.
- The user of the algorithm will need to write the `comparator` function (proper guidance in documentation)

**Comment by pankaj-bind** [comment]
provide description
