### ISSUE TITLE
Two pointer

### ISSUE THREAD

**Issue by Sridevi0321** [AlgoGenesis/C#890]
## Description:
Given an array `arr[]` of size `N`, the objective is to find the longest subarray in which all elements are distinct and time and space complexity is O(n).

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Affected Algorithm:
 I want to update the Two pointer algorithm with the new question with efficient time and space complexity.

**Comment by Sridevi0321** [comment]
can you please assign this issue to me?

**Comment by pankaj-bind** [comment]
@Sridevi0321 assigned
