### ISSUE TITLE
Maximum Sum Square SubMatrix

### ISSUE THREAD

**Issue by khurshed07** [AlgoGenesis/C#899]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Maximum Sum Square SubMatrix```  

### About:  
Given an N x N matrix, find a k x k submatrix where k <= N and k >= 1, such that sum of all the elements in submatrix is maximum. The input matrix can contain zero, positive and negative numbers

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- ✔ Contributor in GSSoC-ext
- ✔ Want to work on it

**Comment by pankaj-bind** [comment]
@khurshed07 assigned
