### ISSUE TITLE
Add KMP pattern matching algorithm

### ISSUE THREAD

**Issue by icemberg** [AlgoGenesis/C#9]
Can you please assign this task to me . I would be very happy to add the documentation and code for this topic and would like to contribute to this project

**Comment by icemberg** [comment]
if possible i would like to add other string pattern matching algorithm

**Comment by pankaj-bind** [comment]
@icemberg You can start

**Comment by simmi-verma** [comment]
I am participating in gssoc-ext for the first time. I would like to work on this .Please assign to me.
