### ISSUE TITLE
[NEW ALGORITHM] Kahn's Algorithm in Graph Algorithms

### ISSUE THREAD

**Issue by iking07** [AlgoGenesis/C#90]
## Description:
I want to add Kahn's Algorithm under the graph section as it is one of most important algorithms while studying graph theory

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
- [x] Part of hacktober-fest

  

## Additional Information:
I will write the program file in c and it will have detailed explanation of every line of code and I want to start contributing through this so please assign this to me.

**Comment by pankaj-bind** [comment]
@iking07 you can start
