### ISSUE TITLE
[NEW ALGORITHM] Rotten Oranges Problem (Breadth-First Search)

### ISSUE THREAD

**Issue by divyalakshmi0** [AlgoGenesis/C#901]
### Description:
This issue proposes an algorithm to solve the **Rotten Oranges Problem**, where given a 2D grid of oranges, each cell can be empty, have a fresh orange, or contain a rotten orange. The goal is to determine the minimum time taken for all fresh oranges to become rotten, or return -1 if it's impossible.

### Key Features:
- **Input**: A 2D grid where:
  - 0 represents an empty cell,
  - 1 represents a fresh orange,
  - 2 represents a rotten orange.
- **Output**: The minimum time required for all fresh oranges to rot. If not all oranges can rot, return -1.
- **Algorithm**: Breadth-First Search (BFS) is used to simulate the spread of rot from rotten oranges to their neighboring fresh oranges.
  
### Importance:
The Rotten Oranges problem is important in simulating real-world processes such as infection spread, propagation of fire, or even viral marketing models. It teaches the use of BFS in grid-based problems where state changes propagate over time.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by AkshatSharma5** [comment]
Please assign me this issue
