### ISSUE TITLE
[NEW ALGORITHM]  Dutch - Flag Algorithm

### ISSUE THREAD

**Issue by Jazz-45** [AlgoGenesis/C#91]
## Description:
The Dutch flag algorithm is a classic computer science algorithm that efficiently sorts an array of elements into three groups: elements less than a pivot, elements equal to the pivot, and elements greater than the pivot. It's often used as a subroutine in more complex sorting algorithms like quicksort.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it
- [x] Part of Hacktober Fest

## Additional Information:
Provide any other relevant information or resources regarding the algorithm.
Dutch National Flag (DNF) - It is a programming problem proposed by Edsger Dijkstra. The flag of the Netherlands consists of three colors: white, red, and blue. The task is to randomly arrange balls of white, red, and blue in such a way that balls of the same color are placed together. For DNF (Dutch National Flag), we sort an array of 0, 1, and 2's in linear time that does not consume any extra space. We have to keep in mind that this algorithm can be implemented only on an array that has three unique elements.

**Comment by pankaj-bind** [comment]
@Jazz-45 you can start.

**Comment by Jazz-45** [comment]
Thank you @pankaj-bind sir for assigning me. I would love to work on this.
