### ISSUE TITLE
[NEW ALGORITHM] Postfix to infix

### ISSUE THREAD

**Issue by Mansi07sharma** [AlgoGenesis/C#911]
### Name:  
Postfix to infix

### About:  
to understand the use of stack
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

@pankaj-bind Kindly assign it to me

**Comment by pankaj-bind** [comment]
Do not create new issues until you complete previous one.
