### ISSUE TITLE
[NEW ALGORITHM] 3-way partitioning

### ISSUE THREAD

**Issue by KrishnaMohanty08** [AlgoGenesis/C#914]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```3-way partitioning```  

### About:  
 3-way partitioning is an algorithm for sorting an array containing three distinct values. The algorithm works by maintaining three pointers: low, mid, and high. The low pointer points to the beginning of the array, the high pointer points to the end of the array, and the mid pointer starts at the beginning of the array and moves through it.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [. ] Contributor in GSSoC-ext
- [. ] Want to work on it

**Comment by Avinashs7** [comment]
Can you assign this to me!

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
