### ISSUE TITLE
[NEW ALGORITHM] Happy Number and Sad Number Algorithms

### ISSUE THREAD

**Issue by Monojit-Pal** [AlgoGenesis/C#918]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  

### About:  
The Happy Number algorithm checks if a number is happy, which means that if you repeatedly replace the number with the sum of the squares of its digits, you eventually reach 1. A number that does not reach 1 is considered a Sad Number. Implementing both algorithms would provide a valuable addition to the collection of number-related algorithms in this repository.

This would help users learn about number classification through a simple yet effective approach.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Lokesh-Bijarniya** [comment]
@Monojit-Pal could you assign me?
