### ISSUE TITLE
[NEW ALGORITHM] Lee's algorithm for graphical grid-based environments

### ISSUE THREAD

**Issue by Anirudra16** [AlgoGenesis/C#930]
**Description**:
Lee's algorithm is a specialized application of breadth-first search (BFS) for graphical grid-based environments to find the shortest path in a 2D grid with obstacles. The algorithm guarantees the shortest path and is useful in scenarios like maze-solving, robotics navigation, and printed circuit board routing.

**Key Features**:
- Takes a 2D grid as input where 0 represents free space and 1 represents obstacles.
- Ensures optimal pathfinding in unweighted grids using BFS.
- The code includes user input for grid dimensions, obstacles, start point, and end point.
- Handles cases where no path exists by notifying the user.

**Why Lee's Algorithm**:
- Shortest Path Guarantee: Unlike depth-first search (DFS), Lee's algorithm ensures that the shortest path is found in an unweighted grid.
- Obstacle Handling: Efficiently manages blocked cells, avoiding paths that cannot be traversed.
- Simplicity: Provides a clear and simple approach to solving pathfinding problems in structured grid environments.

           Please assign me this as I want to work on it.

- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

**Comment by MD-IRFAN-RAJ** [comment]
Please assign me this as I want to work on it
