### ISSUE TITLE
Postorder Traversal Via Recursion 

### ISSUE THREAD

**Issue by MithanshuHedau** [AlgoGenesis/C#934]
### About:  
Postorder Traversal is one of the most fundamental tree traversal techniques, especially used in binary trees. In this traversal, the nodes of the tree are visited in a specific sequence: left subtree first, then the right subtree, and finally the root node. This order can be summarized as Left → Right → Root.

This approach is particularly useful in scenarios where child nodes need to be processed before their parent nodes, such as in the deletion of a tree, where it is essential to free the memory allocated to child nodes before dealing with the parent node. In evaluating expression trees, where leaf nodes represent operands and internal nodes represent operators, Postorder Traversal allows for the correct evaluation of expressions. The implementation is typically done recursively, where a function is called on the left child, then the right child, and then the node itself is processed, making the code concise and intuitive.

Time Complexity : 
The time complexity for this traversal is O(n), where n is the number of nodes, as each node is visited exactly once, while the space complexity is O(h), where h is the height of the tree, due to the call stack used in recursion. Overall, Postorder Traversal is a fundamental technique in computer science that is essential for various applications in data structures and algorithms.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [✅ ] Contributor in GSSoC-ext
- [✅ ] Want to work on it

**Comment by MD-IRFAN-RAJ** [comment]
Please assign this to me
