### ISSUE TITLE
[NEW ALGORITHM] Count Inversions

### ISSUE THREAD

**Issue by Dipanita45** [AlgoGenesis/C#935]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
``Count Inversion```  

### About:  
You are given an integer n and a 2D array requirements, where requirements[i] = [endi, cnti] represents the end index and the inversion count of each requirement.

A pair of indices (i, j) from an integer array nums is called an inversion if:

i < j and nums[i] > nums[j]

---

### Labels:  
```new algorithm, gssoc-ext,  level2```

---

### Assignees:  
- [yes] Contributor in GSSoC-ext
- [yes] Want to work on it

Please assign me the issue @pankaj-bind

**Comment by Avinashs7** [comment]
Can you assign it to me!
Would like to work on this

**Comment by pankaj-bind** [comment]
@Dipanita45 assigned

**Comment by Dipanita45** [comment]
Please assign me #676 also
