### ISSUE TITLE
[KMP Algorithm (Knuth-Morris-Pratt)] 

### ISSUE THREAD

**Issue by eshaalal** [AlgoGenesis/C#946]
String Matching: O(n + m) where n is text length and m is pattern length

Efficiently finds occurrences of a "word" within a main "text string" by employing the observation that when a mismatch occurs, the word itself embodies sufficient information to determine where the next match could begin.

**Comment by eshaalal** [comment]
@AlgoGenesis please assign me this task

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
