### ISSUE TITLE
[NEW ALGORITHM] Manacher's Algorithm (Longest Palindromic Substring Algorithm)

### ISSUE THREAD

**Issue by HimanshuM685** [AlgoGenesis/C#947]
### Name:  Manacher's Algorithm (Longest Palindromic Substring Algorithm)
```[NEW ALGORITHM]```  

### About:  
Manacher's Algorithm finds the longest palindromic substring in linear time by transforming the string to handle both even and odd-length palindromes uniformly.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by PrasanBora** [comment]
I will work on this assign it to me

**Comment by HimanshuM685** [comment]
> I will work on this assign it to me

My work is already done.
