### ISSUE TITLE
[NEW ALGORITHM] Subset Sum (Recursion)

### ISSUE THREAD

**Issue by govindumeesala** [AlgoGenesis/C#95]
## Description:
Problem Statement: Given an array print all the sum of the subset generated from it, in the increasing order.

## Checklist:
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

## Additional Information:
Example 1:

Input: N = 3, arr[] = {5,2,1}

Output: 0,1,2,3,5,6,7,8

Explanation: We have to find all the subset’s sum and print them.in this case the generated subsets are [ [], [1], [2], [2,1], [5], [5,1], [5,2]. [5,2,1],so the sums we get will be  0,1,2,3,5,6,7,8

Input: N=3,arr[]= {3,1,2}

Output: 0,1,2,3,3,4,5,6

Explanation: We have to find all the subset’s sum and print them.in this case the generated subsets are [ [], [1], [2], [2,1], [3], [3,1], [3,2]. [3,2,1],so the sums we get will be  0,1,2,3,3,4,5,6

**Comment by pankaj-bind** [comment]
@govindumeesala you can start
