### ISSUE TITLE
[NEW ALGORITHM] 

### ISSUE THREAD

**Issue by ananyashinde2434** [AlgoGenesis/C#952]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  
SIMHASH ALGORITHM 

### About:  
Propose a new algorithm to be added to the repository
Implement a C program that calculates the SimHash for a given string of text. The SimHash should be based on the words in the input string. The task involves breaking the input text into individual words, hashing each word using an 8-bit hash function, and combining these hashes to generate a SimHash binary pattern. The final output should be the SimHash represented as an 8-bit binary number.
---

### Labels:  
new algorithm, gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
@ananyashinde2434 assigned

**Comment by ananyashinde2434** [comment]
thank u
