### ISSUE TITLE
[NEW ALGORITHM] :Multi-threading in C (pthread)

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [AlgoGenesis/C#957]
Description:
Multi-threading allows a program to run multiple threads concurrently, significantly improving performance, especially on multi-core systems. This issue proposes the addition of a new algorithm to implement multi-threading using the POSIX thread library (pthread) in C. It will explain how to create and manage threads, enhancing the repository's coverage of concurrent programming techniques.
 
 ---

### Name:  
```[Multi-threading ]```  

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.
