### ISSUE TITLE
[NEW ALGORITHM] : Error Handling in C

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [AlgoGenesis/C#958]
### Description:
Error handling is a crucial aspect of programming that allows developers to manage and respond to unexpected conditions that may arise during the execution of a program. In C, error handling can be implemented using several techniques, including the use of the errno variable, return values from functions, and best practices for managing errors effectively.

---

### Name:  
```[Error Handling]```  

### About:  
Propose a new algorithm to be added to the repository

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by PrasanBora** [comment]
i want to work on this assign it to me

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
