### ISSUE TITLE
Add Automated Greeting Workflow

### ISSUE THREAD

**Issue by shubhagarwal1** [AlgoGenesis/C#96]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
Hey @pankaj-bind  please assign me this task with labels gssoc-ext, hacktoberfest, hacktoberfest-accepted, level

**Comment by pankaj-bind** [comment]
@shubhagarwal1 Do you want to work on it.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 Do you want to work on it.

yes i can want to work on this

**Comment by pankaj-bind** [comment]
@shubhagarwal1 go for it
