### ISSUE TITLE
JUMP SEARCH

### ISSUE THREAD

**Issue by Priyanshi0112** [AlgoGenesis/C#960]
### Name:  
JUMP SEARCH

### About:  
A search method that iterates over the list in constant-length steps until it finds the relevant element or determines that it is no longer present.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by crackedmob** [comment]
i want to work on this please assign this to me

**Comment by mahi7665** [comment]
i want to work on this please assign this to me

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
