### ISSUE TITLE
Sleeping Barber Problem Solution

### ISSUE THREAD

**Issue by Priyanshi0112** [AlgoGenesis/C#961]
### Name:  
Sleeping Barber Problem Solution

### About:  
The sleeping barber dilemma was first posed by Dijkstra in 1965. This issue is based on a fictitious situation in which there is a single barber at a barbershop. The waiting area and the workroom are separated in the barbershop. Customers can wait in the waiting area on n seats; however there is only one barber chair in the workroom.

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by Aditya-NV-06** [comment]
Can you assign this problem to me.

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
