### ISSUE TITLE
Quadratic Probing Program 

### ISSUE THREAD

**Issue by Priyanshi0112** [AlgoGenesis/C#962]
### Name:  
Quadratic Probing Program 

### About:  
Hash tables with quadratic probing are implemented in this C program. An associative array, a structure that can map keys to values, is implemented using a data structure called a hash table. A hash table uses a hash function to create an index into an array of slots or buckets. Linear probing and quadratic probing are comparable. The difference is that we would check 1^1=1 element, 2^2=4 elements, 3^2=9 elements, 4^2=16 elements, etc., if we attempted to insert into a slot that was already filled.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
