### ISSUE TITLE
Dino Game in C

### ISSUE THREAD

**Issue by Priyanshi0112** [AlgoGenesis/C#963]
### Name:  
Dino Game in C

### About:  
The dinosaur game is sometimes called the "T-Rex Run" or the "Chrome Dino Game". It is a simple online game that users can play in Google Chrome when they try to browse a website without an internet connection. In the game, players take control of a dinosaur running through a space with some obstacles. The challenge is to jump over obstacles, mostly cactus species, to avoid them. Over time, the game becomes increasingly difficult as its speed grows steadily. The spacebar key allows users to control how far the dinosaur can jump. Its simplicity and retro-inspired visuals have made it popular for people looking for a playful yet interactive diversion.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
