### ISSUE TITLE
Optimal Page Replacement Algorithm i

### ISSUE THREAD

**Issue by Priyanshi0112** [AlgoGenesis/C#964]
### Name:  
Optimal Page Replacement Algorithm 

### About:  
The Optimal Page Replacement Algorithm, often known as Belady's Algorithm, is a page replacement algorithm. It is used in operating systems to determine which page to evict from memory when a page fault occurs. It is different from some other algorithms like FIFO or LRU, the Optimal Algorithm is not practical for implementation in a real operating system because it requires knowledge of future page references, which is impossible in practice. However, it serves as an ideal benchmark to measure the performance of other page replacement algorithms.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by IngaleChinmay04** [comment]
I'm interested in doing it! Can you assign this issue to me?

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
