### ISSUE TITLE
Monoalphabetic cipher program

### ISSUE THREAD

**Issue by Priyanshi0112** [AlgoGenesis/C#965]
### Name:  
Monoalphabetic cipher program

### About:  
A monoalphabetic cipher program is about turning a secret message into something unreadable to anyone who doesn't know the secret. It replaces each letter in the message with a different letter from a special secret list. The secret list, called the "substitution key", never changes and is like a secret code. For example, if "A" becomes "D" in the secret code, every "A" in the message turns into a "D".

When you use this program, you must provide the secret code (26 unique letters in a specific order) and the message you want to hide. After that, the program goes through your message, one letter at a time, and changes each letter based on the secret code. It leaves spaces and punctuation alone.

The result of this process is the "ciphertext", which is the secret version of your message. It's ready to be sent the data securely or kept hidden. It's important to note that monoalphabetic ciphers could be more secure for modern purposes. They are mainly used for learning about cryptography or for historical interest because attackers can easily decipher them.
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
