### ISSUE TITLE
Runge-kutta method

### ISSUE THREAD

**Issue by Priyanshi0112** [AlgoGenesis/C#967]
### Name:  
Runge-kutta method  

### About:  
The Runge-Kutta method can be used to solve common differential equations numerically. The fourth-order Runge-Kutta method (RK4) is one of the most used variations. Ordinary differential equations are common in engineering, although not all of them can be resolved analytically. The Runge-Kutta method is one of the most often used methods for solving or obtaining a numerical solution to such ordinary differential equations.

In contrast to Taylor's series, which requires a lot of work to obtain higher-order derivatives, the RK4 technique does not call for the computation of such higher-order derivatives.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by mahi7665** [comment]
I would like to work on this project , please assign me this project.

**Comment by pankaj-bind** [comment]
Do not create unnecessary issues until you complete the previous one.
