### ISSUE TITLE
[NEW ALGORITHM] GRADIENT DESCENT IN C

### ISSUE THREAD

**Issue by anishka25** [AlgoGenesis/C#976]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```GRADIENT DESCENT```  

### About:  
Gradient descent is the most important algorithms in deep learning and I would like to add the implementations of the naive version as well as more advanced versions once this pr is closed in C language. 
---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level3```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by anishka25** [comment]
@karandevhub please stop spamming as the issue is opened by me and I have clearly mentioned I wanna work on it.

**Comment by karandevhub** [comment]
@anishka25  oh ! sorry for that i was testing my Extension

**Comment by anishka25** [comment]
@pankaj-bind why was this closed? may I know the reason?
