### ISSUE TITLE
[NEW ALGORITHM] Sieve of Eratosthenes Algorithm

### ISSUE THREAD

**Issue by 13Sharad** [AlgoGenesis/C#983]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```   Sieve of Eratosthenes Algorithm

### About:  
The Sieve of Eratosthenes is an ancient and efficient algorithm used to find all prime numbers up to a specified integer n. A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. This algorithm eliminates the need for checking divisibility by numbers repeatedly, making it much faster than direct methods like trial division.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [YES ] Contributor in GSSoC-ext
- [YES ] Want to work on it

**Comment by AnkitHazra** [comment]
Can you please assign me this issue? @pankaj-bind
