### ISSUE TITLE
[NEW ALGORITHM] ADD DIFFERENT TYPES OF SEARCHES IN C

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [AlgoGenesis/C#985]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```[NEW ALGORITHM]```  

### About:  
I want to add different types of searches such as linear search and binary search.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest-accepted, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

PLEASE ASSIGN THIS ISSUE TO ME AND ADD THE LABELS

**Comment by crackedmob** [comment]
Hi
Can you please assign me to this issue?
Thank you
