### ISSUE TITLE
[NEW ALGORITHM] Aho-Corasick algorithm¶

### ISSUE THREAD

**Issue by Harishankar14** [AlgoGenesis/C#99]
## Description:
Hey, i actually wanted to work on this Aho-Corasick algorithm, 
 Aho-Corasick algorithm allows us to quickly search for multiple patterns in a text

## Checklist:
- 

- [ yes]  Contributor in GSSoC-ext
``
- [yes ] Want to work on it

## Additional Information:
Majorly this can be used in plagarism checks,keyword matching,typos etc,
Mainly use Trie

Can u please assign me this.

**Comment by pratheekv39** [comment]
@Harishankar14 Aho Corasick is already added in String Algorithms. Kindly , raise other addition of other algorithms

**Comment by pankaj-bind** [comment]
@pratheekv39 you are helping me a lot. Thanks
