### ISSUE TITLE
[NEW ALGORITHM]  MULTISTAGE GRAPH in dynamic programming.

### ISSUE THREAD

**Issue by shuvojitss** [AlgoGenesis/C#990]
### Name:  
```[NEW ALGORITHM]```  MULTISTAGE GRAPH
You are given a directed multistage graph with n nodes. The graph is divided into multiple stages, and you need to find the shortest path from the source node (node 0) to the destination node (node n-1) while passing through intermediate stages. Each node belongs to a particular stage, and edges between nodes have associated costs. Use Dynamic Programming to solve this.

### About:  
One of the most important program in dynamic programming. 
The graph is represented as an adjacency matrix, where graph[i][j] denotes the cost of moving from node i to node j:
graph[i][j] = -1 indicates there is no edge from node i to node j.
graph[i][j] ≥ 0 represents the cost of traveling from node i to node j.

### Input:
The adjacency Cost Matrix.

### Output:
MInimum cost path and Minimum Cost.

![image (2)](https://github.com/user-attachments/assets/874b35a0-7da3-4072-aa42-aeed7f9335b8)

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [ ] Contributor in GSSoC-ext
- [ ] Want to work on it

### Additionl Information:

@pankaj-bind  Please assign me this issue I want to work on it.

**Comment by 2004san** [comment]
i want to work on this issue, @pankaj-bind

**Comment by pankaj-bind** [comment]
@shuvojitss assigned
