### ISSUE TITLE
[NEW ALGORITHM] Add Boundary Traversal in 2-D Arrays

### ISSUE THREAD

**Issue by adwityac** [AlgoGenesis/C#992]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
```Boundary Traversal```  

### About:  
The Boundary Traversal algorithm traverses the perimeter of a 2D matrix and prints its elements in a clockwise direction. This algorithm is useful for problems that require processing or analyzing the outer elements of a matrix.

Algorithm Steps:

Start from the first row and print all its elements.
Print the last element of each row from the second row to the last row.
If the matrix has more than one row, print the last row in reverse order.
If the matrix has more than one column, print the first element of each row from the second-to-last row back up to the second row.
Handle edge cases for single-row or single-column matrices.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [✅] Contributor in GSSoC-ext
- [✅] Want to work on it

**Comment by Lokesh-Bijarniya** [comment]
@pankaj-bind Could u assign me this issue?
