### ISSUE TITLE
[NEW ALGORITHM] master theorem under divide and conquer 

### ISSUE THREAD

**Issue by Anu142004** [AlgoGenesis/C#994]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
master theorem  

### About:  
it is import algo 

---

### Labels:  
 gssoc-ext, hacktoberfest, level1

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by Anu142004** [comment]
shall i work on this

**Comment by pankaj-bind** [comment]
@Anu142004 assigned
