### ISSUE TITLE
[NEW ALGORITHM] :  Myhill-Nerode Theorem-theory of computation

### ISSUE THREAD

**Issue by Anu142004** [AlgoGenesis/C#998]
## Issue will be closed if:

> 1) You mention more than one algorithm. You can create a separate issue for each algorithm once the current one is completed.  
> 2) You propose an algorithm that is already present or has been mentioned in a previous issue.  
> 3) You create a new issue without completing your previous issue.

**Note:** These actions will be taken seriously. Failure to follow the guidelines may result in the immediate closure of your issue.

---

### Name:  
 Myhill-Nerode Theorem

### About:  
The Myhill-Nerode Theorem is a fundamental result in formal language theory, particularly useful in the context of finite automata and regular languages. It provides a method to minimize deterministic finite automata (DFA) and offers a characterization of regular languages.

---

### Labels:  
```new algorithm, gssoc-ext, hacktoberfest, level1```

---

### Assignees:  
- [x] Contributor in GSSoC-ext
- [x] Want to work on it

**Comment by pankaj-bind** [comment]
Do not create a new issue until you complete the previous one.
